### ISSUE TITLE
regtest ww3_tp2.15 : NetCDF _FillValue set to NaN

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#100]
The wind.nc NetCDf file in the ww3_tp2.15 regtest has the FillValue for the U and V variables set to NaN.

For some compilers, this causes a runtime segfault as comparisons with NaNs is undefined which can lead to NaN values entering the source term calculations.

This behavious can also change depending on what compiler optimizations are used.

For the cray compiler. this regtest fails with > -O1 optimization as line 624 of the w3updtmd module allows a NaN to pass through into the U10 array:

           U10 (ISEA) = MAX ( UA(ISEA) , 0.001 )

Modifying the netCDF file data and attributes to use a fill value of 2**15 (or some other exactly representable number) fixed this issue.

**Comment by ukmo-ccbunney** [comment]
@aliabdolali : are you able to update the wind.nc file for ww3_tp2.15 in the data_regtests bundle? Currently U and V look like this:

float U(time, latitude, longitude) ;
	U:_FillValue = NaNf ;
	U:units = "m/s" ;
	U:field = "U, scalar, series" ;
	U:scale_factor = 0.01 ;
	U:long_name = "10-meter wind East component" ;
float V(time, latitude, longitude) ;
	V:_FillValue = NaNf ;
	V:units = "m/s" ;
	V:field = "V, scalar, series" ;
	V:scale_factor = 0.01 ;
	V:long_name = "10-meter wind North component" ;

**Comment by aliabdolali** [comment]
@ukmo-ccbunney 
Hi Chris,
Could you check the attached fixed wind.nc and let me know if it works with cray compiler, if yes, we can replace it on ftp.
Regards
[wind.nc.zip](https://github.com/NOAA-EMC/WW3/files/3643059/wind.nc.zip)

@ajhenrique 
If this fix works on Cray, we need to update ftp.

**Comment by ukmo-ccbunney** [comment]
Hi @aliabdolali ,

Unfortunately, the new file is giving me the same problem...

I think the issue is that the FillValue (9.96920996839e+36) is too large and is not exactly representable as a float. This might make it difficult to match exactly the values in U/V data arrays meaning that it is making it into the WW3 program as a U/V value of 9.96920996839e+36. Futhremore, once this value has been scaled by 0.01, it is too large to fit into a float32 resulting in an "Inf" of "nan" value.

Certinaly, if I load the variable into Python using the NetCDF4 library, the U and V arrays have lots of NaN values over the land where the mask (FillValue) should be.

I recommend a smaller FillValue that is a power of 2. Perhaps 2^15 = 32768.0, or 2^32 = 4294967296.0

If I change the fill value to 3276800 (=2^15 / 0.01), then both Python and WW3 read in sensible values and the wave model doesn't SEGFAULT!

**Comment by aliabdolali** [comment]
Hi @ukmo-ccbunney 
I see what you meant. The attached wind file has _fillvalue of 3276800. Since you have checked this value, as mentioned, I'd ask @ajhenrique to upload it to the ftp, so from now on, the fixed file is used whenever you download it from there.
[wind.nc.zip](https://github.com/NOAA-EMC/WW3/files/3644571/wind.nc.zip)
Regards
AA

**Comment by ukmo-ccbunney** [comment]
Hi @aliabdolali 

Sorry - that file is still not quite right I am afraid. The FillValue is good but the actual values in the U/V arrays don't match it (they are still 9.96e+36). If you run "ncdump -v U wind.nc" it still gives you a bunch of NaN values.

I've emailed you the file I have modified  - have a look and let me know if you are happy with it.

Regards,
Chris.

**Comment by aliabdolali** [comment]
hi @ukmo-ccbunney 
My bad, I modified the pre-filled wind.nc file not the original one. We will add your wind.nc to ftp. Thanks,
AA

**Comment by ajhenrique** [comment]
@ukmo-ccbunney @aliabdolali the new file has been added to the ftp bundle replacing the previous one. Please test and let me know if it works.

**Comment by ukmo-ccbunney** [comment]
Thanks @aliabdolali @ajhenrique 
It's working fine for me.
