### ISSUE TITLE
a few small typos

### ISSUE THREAD

**Issue by jcwarner-usgs** [NOAA-EMC/WW3#1006]
- w3profsmd.F90  line 684  extra ^
#endif^

-w3srcemd.F90  line  1705 my cpp did not like the ! comment
#endif !W3_PDLIB

**Comment by MatthewMasarik-NOAA** [comment]
@jcwarner-usgs, thanks for bringing these to our attention!  Please feel free to submit a fix PR to address them.

**Comment by jcwarner-usgs** [comment]
all good.  happy to send along the stuff i find.
i do not know what you mean by a 'fix PR'

**Comment by MatthewMasarik-NOAA** [comment]
Hi @jcwarner-usgs, I just meant you could submit a pull request (PR) with a 'fix'.  In this case the fix would just be the removal of the '`^`' character and the `!W3_PDLIB` comment.  It is about as easy as they come, so we can certainly do it on our own, though you would get the author credit if you submit.  Either way is OK, just wanted to give you the option to get credit for your efforts.

**Comment by ukmo-ccbunney** [comment]
> all good. happy to send along the stuff i find. i do not know what you mean by a 'fix PR'

Hi @jcwarner-usgs - this page has some info that might help you:
https://github.com/NOAA-EMC/WW3/wiki/Developer-Guide#development-workflow

Although if you prefer not to raise a PR yourself one of the other code managers here will be happy to do it for you.

**Comment by jcwarner-usgs** [comment]
ah, yes.  dont tell anyone i forgot what a pull request was.
if you can take care of it that would be fine.  thanks!
-j

**Comment by MatthewMasarik-NOAA** [comment]
Hi @jcwarner-usgs, that sounds good, I'll make a pull request for it.  Thanks again.  Cheers!
