### ISSUE TITLE
matrix.comp very slow

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#1031]
**Describe the bug**
Since the update to CMake, I have noticed that the `matrix.comp` script is very slow; it can take several hours to complete.
It has always been a bit slow, but the move to cmake has made it worse.

I believe that this line is a particular bottleneck:
https://github.com/NOAA-EMC/WW3/blob/3eb8161fdc999f4046fac7d77febff70c399c4f8/regtests/bin/matrix.comp#L172

It is grepping for `.` (i.e. anything) recursively in all files to check whether grep returns that the file is a "binary file".
This is very inefficient as it is unnecessarily reading the entirety of any text files.
Also, now we are using CMake, there are `build` directories in each regtest work directory that contain many many files - these are also being recursively grepped too (unnecessarily).

A quick manual test on a work directory shows that this single command is taking up to 15 seconds or more to complete. That quickly adds up over a full regression test matrix.

**To Reproduce**
Run matrix.comp on any test.
Add a "time" command around the above line to get timings if wanted.

**Expected behavior**
It's slow!

**Proposed fix**
I propose that we get rid of the line mentioned above and instead perform a `file` test on individual files as they are processed.
The `file` command will return the mime type of the file and we can check the output for the string "text" to check whether it is a text file. Any other kind of file can be considered binary. That should be a lot quicker than a recursive grep.

Example output of `file` command in a regtest directory
```
finished:            ASCII text
ice.ww3:             data
log.ww3:             ASCII text
mod_def.ww3:         MPEG sequence
out_grd.ww3:         data
out_pnt.ww3:         data
restart.ww3:         data
tab50.ww3:           ASCII text
tab51.ww3:           ASCII text
ww3.196806.nc:       NetCDF Data Format data
ww3.196806_spec.nc:  NetCDF Data Format data
ww3.68060600.hs:     ASCII text
ww3.68060601.hs:     ASCII text
ww3.68060602.hs:     ASCII text
ww3.68060603.hs:     ASCII text
ww3.68060604.hs:     ASCII text
ww3.68060605.hs:     ASCII text
ww3.68060606.hs:     ASCII text
ww3.68060607.hs:     ASCII text
ww3.68060608.hs:     ASCII text
ww3.68060609.hs:     ASCII text
ww3.68060610.hs:     ASCII text
ww3.68060611.hs:     ASCII text
ww3.68060612.hs:     ASCII text
ww3_grid.nml.log:    ASCII text
ww3_grid.out:        ASCII English text, with very long lines
ww3_ounf.nml.log:    data
ww3_ounf.out:        ASCII Pascal program text
ww3_ounp.nml.log:    ASCII text
ww3_ounp.out:        ASCII Pascal program text
ww3_outf.out:        ASCII Pascal program text
ww3_outf_file.out:   ASCII Pascal program text
ww3_outf_screen.out: ASCII Pascal program text
ww3_outp_tab50.out:  ASCII Pascal program text
ww3_outp_tab51.out:  ASCII Pascal program text
ww3_prep.out:        ASCII Pascal program text
ww3_shel.nml.log:    ASCII text
ww3_shel.out:        ASCII English text
ww3_strt.out:        ASCII Pascal program text
```

We could also be more robust and check on the mime-type (rather than "human readable description"):
E.G.

```
file -i *
ab50.ww3:           text/plain charset=us-ascii
tab51.ww3:           text/plain charset=us-ascii
ww3.196806.nc:       application/octet-stream
ww3.196806_spec.nc:  application/octet-stream
ww3.68060600.hs:     text/plain charset=us-ascii
ww3.68060601.hs:     text/plain charset=us-ascii
ww3.68060602.hs:     text/plain charset=us-ascii
```

Piping the output through grep would be a good check for binary/text files:

```
if [[ file -i ${FILE} | grep -qi "\<text\>" ]]; then
   # text
else
  # binary
fi
```

**Comment by MatthewMasarik-NOAA** [comment]
@ukmo-ccbunney great catch on the recursive `grep` for '`.`'  Sounds like a good direction forward using `file`.

**Comment by ukmo-ccbunney** [comment]
I'll put together a PR for this soon when I get a chance.
