### ISSUE TITLE
Eliminate deprecated switches

### ISSUE THREAD

**Issue by Ghazal-Mohammadpour** [NOAA-EMC/WW3#1051]
**Describe the bug**
Within the regtests, certain switches are not utilized. Now, it is necessary to eliminate these deprecated switches from the regtests. 

-     F90 DUM: https://github.com/NOAA-EMC/WW3/issues/354

-     BT2 : https://github.com/NOAA-EMC/WW3/issues/573 

-     C90, NEC, SX6, SX8: https://github.com/NOAA-EMC/WW3/issues/357

-     XX0, XXX: https://github.com/NOAA-EMC/WW3/issues/356

-     FLXX, PRX, STX, NLX, BTX, DBX, TRX, BSX: https://github.com/NOAA-EMC/WW3/issues/355 

-     NCC: https://github.com/NOAA-EMC/WW3/issues/353

-     NCEP1: https://github.com/NOAA-EMC/WW3/issues/352

-     NC4: https://github.com/NOAA-EMC/WW3/issues/359 

**To Reproduce**
N/A

**Expected behavior**
Our expectation is that there should be no deprecated switches visible.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ukmo-ccbunney** [comment]
HI @Ghazal-Mohammadpour 
Thanks for raising this issue.
Could you provide some more details in the relevant sections of the issue template please?
