### ISSUE TITLE
Problem to run ww3_shel

### ISSUE THREAD

**Issue by DiegoGutierrez2210** [NOAA-EMC/WW3#106]
Hi everyone

I had this issue when ran ww3_shel (everything compile ok):

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x15272542031a
#0  0x15272542031a
#1  0x15272541f503
#2  0x15272486df1f
#0  0x15272542031a
#1  0x15272541f503
#2  0x15272486df1f
#3  0x55da6da50317
#4  0x55da6da3c4eb
#5  0x55da6da0d494
#6  0x152724e4e95d
#7  0x1527241d36da
#8  0x15272495088e
#9  0xffffffffffffffff
#1  0x15272541f503
#2  0x15272486df1f
#3  0x55da6da50317
#4  0x55da6da3c4eb
#5  0x55da6da0d494
Segmentation fault (core dumped)

I ran another code with the same input files (for period 2017-2018) before this and it was ok.

Anyone anny suggestion on how to solve this?

Switch: F90 NOGRB SHRD OMPG OMPX PR3 UQ FLX0 LN1 ST4 STAB0 NL1 BT4 DB1 MLIM TR1 BS0 IC0 IS0 REF1 XX0 WNT2 WNX1 RWND CRT1 CRX1 TIDE O0 O1 O2 O2a O2b O2c O3 O4 O5 O6 O7

**Comment by ajhenrique** [comment]
Diego, it appears you have opened another issue for the same problem. I'll close this one.
