### ISSUE TITLE
Update regtests modules for latest spack-stack including scotch/7.0.4

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [NOAA-EMC/WW3#1060]
**Is your feature request related to a problem? Please describe.**
Update regression test modules to use the `JCSDA/spack-stack` stack.  The newest spack-stack version should be used which will contain the updated SCOTCH ([v7.0.4](https://gitlab.inria.fr/scotch/scotch/-/tags/v7.0.4)) version.

**Describe the solution you'd like**
The regtests `matrix` scripts should load the latest spack-stack version, containing `scotch/7.0.4`.

**Describe alternatives you've considered**
The alternative is to _not_ update to the `spack-stack` stack, and continue to use the `hpc-stack` -based modules.  This would restrict us to using `scotch/7.0.3`, which does _not_ have the scaling or OpenMPI bug fixes.

**Additional context**
Note that UFS-WM is moving from `hpc-stack` to `spack-stack`.
- depends on jcsda/spack-stack/issues/748

**Comment by JessicaMeixner-NOAA** [comment]
Just a quick note that these are for just the NCEP modules - although other code managers might also want to update to the newest 7.0.4 scotch since it has the bug-fixes.

**Comment by MatthewMasarik-NOAA** [comment]
Close as completed.
