### ISSUE TITLE
Error in w3iosfmd.F90 after run ww3_shel

### ISSUE THREAD

**Issue by DiegoGutierrez2210** [NOAA-EMC/WW3#108]
Hi everyone

I had this issue with WaveWatchIII 5.16 and I did not know how to solve it:
[switch.txt](https://github.com/NOAA-EMC/WW3/files/3687952/switch.txt)

At line 548 of file w3iosfmd.F90 (unit = 34, file = './partition.ww3')
Fortran runtime error: Expected INTEGER for item 8 in formatted transfer, got REAL
(I3,3F8.2,2F9.2,F7.2)
 ^
Error termination. Backtrace:
#0  0x7f4cb9af931a
#1  0x7f4cb9af9ec5
#2  0x7f4cb9afa68d
#3  0x7f4cb9c63a31
#4  0x7f4cb9c702b2
#5  0x7f4cb9c72fb2
#6  0x7f4cb9c7346c
#7  0x7f4cb9c70624
#8  0x555abb22e7a2
#9  0x555abb1ac21a
#10  0x555abb16a01b
#11  0x555abb163c88
#12  0x7f4cb8f29b96
#13  0x555abb163cb9
#14  0xffffffffffffffff

I don't understand the error associated with file partition.ww3, I tried to improve w3iosfmd.F90 but everything was fine in line 548:

542 ! 4.d Process partitions for this point
543 !
544         IOFF   = ICP(JSEA,2)
545 !
546         IF ( FLFORM ) THEN
547             DO IP=0, ICP(JSEA,1) - 1
548               WRITE (NDSPT,942) IP, DTP(:,IP+IOFF)
549               END DO
550           ELSE
551             DO IP=0, ICP(JSEA,1) - 1
552               WRITE (  NDSPT  ) IP, DTP(:,IP+IOFF)
553               END DO
554           END IF
----------------------------------------------------------------------------------
Anybody knows what could be the problem? Please
Regards!
[partition.ww3.txt](https://github.com/NOAA-EMC/WW3/files/3688121/partition.ww3.txt)

**Comment by ajhenrique** [comment]
@DiegoGutierrez2210 are you using the GitHub version of the code or v5.16? If the latter, please update you code to the latest version and verify if the problem persists, then report back under this same issue number ;-)

**Comment by DiegoGutierrez2210** [comment]
@ajhenrique I used v5.16. Ok, so... Do I need download GitHub version and install it again?

**Comment by ajhenrique** [comment]
@DiegoGutierrez2210 please follow the instructions at
https://github.com/NOAA-EMC/WW3/wiki/WAVEWATCH-III-User-Guide

That guide contains all the information you need to upgrade to the latest version. This section (Issues) is reserved for reporting bugs in the code and issues that are being tackled by developers. In the future, please contact us at NCEP.List.WAVEWATCH@noaa.gov if you need help using the code.

**Comment by mubar5656** [comment]
hello, i just compiled the WW3-master from github and am experiencing this same error when i run ww3_shel

[switch.txt](https://github.com/NOAA-EMC/WW3/files/7302409/switch.txt)

[ww3_shel.txt](https://github.com/NOAA-EMC/WW3/files/7302419/ww3_shel.txt)

  WAVEWATCH III calculating for 2020/02/01 00:00:00 UTC at 10:47:15
At line 580 of file w3iosfmd.F90 (unit = 34, file = './partition.ww3')
Fortran runtime error: Expected INTEGER for item 8 in formatted transfer, got REAL
(I3,3F8.2,2F9.2,F7.2)
 ^

Error termination. Backtrace:
#0  0x7fd5b96bb700 in ???
#1  0x7fd5b96bc259 in ???
#2  0x7fd5b98e2cc1 in ???
#3  0x7fd5b98ef9d2 in ???
#4  0x7fd5b98f3085 in ???
#5  0x7fd5b98f37e3 in ???
#6  0x7fd5b98f038d in ???
#7  0x56281500bd12 in __w3iosfmd_MOD_w3iosf
#8  0x562814f940b3 in __w3wavemd_MOD_w3wave
#9  0x562814f3ef3d in MAIN__
#10  0x562814f376d8 in m
