### ISSUE TITLE
[W3SRC4] WHITECAP not initialised before use

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#1085]
The `WHITECAP` variable in W3SDS4 is not initialised before use in the following additive loop:
https://github.com/NOAA-EMC/WW3/blob/7bbdaca7f452b23a52c3a609b03e82204653dc5e/model/src/w3src4md.F90#L2551-L2554

Elements 1 and 2 are zeroed further up in the code, but element 4 is not which can result in an undefined value in the accumulated sum on line 2553 (`WHITECAP(4)`)

Because the variable is `INTENT(OUT)`, zeroing of the WHITECAP array outside this subroutine has no affect.

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi I have assigned this issue to you - I was not sure if this issue is already known to you and fixed in your upcoming ST4 updates?

**Comment by ukmo-ccbunney** [comment]
Thanks for adding this to your branch @mickaelaccensi .

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi - Do you mind if I raise a separate PR for this as it is affecting the B4B reproducibility of some regression tests in my source term refactoring?

(unless you expect your `feature/ST4table` branch to be ready imminently)

**Comment by mickaelaccensi** [comment]
Hi @ukmo-ccbunney , I've run the matrix for ST4table, a few issues to correct and then I do the PR, I hope tomorrow !

**Comment by ukmo-ccbunney** [comment]
OK @mickaelaccensi - I'll wait for your PR. Thanks.
