### ISSUE TITLE
NDS: Array size mismatch?

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#1097]
I think there is a discrepancy between the size of the NDS variable (used to hold file unit numbers) defined in  `w3odatmd` here as size 15:
https://github.com/NOAA-EMC/WW3/blob/eff6686d50a0e034cfe269731da05804f11f4c8b/model/src/w3odatmd.F90#L439

and elsewhere as size 13, e.g.
https://github.com/NOAA-EMC/WW3/blob/eff6686d50a0e034cfe269731da05804f11f4c8b/model/src/ww3_shel.F90#L332

This is resulting in an array bounds mismatch in w3initmd:
https://github.com/NOAA-EMC/WW3/blob/eff6686d50a0e034cfe269731da05804f11f4c8b/model/src/w3initmd.F90#L693
MDS is of size 13 in this case and NDS is size 15.

**Comment by ukmo-ccbunney** [comment]
I think this bug was introduced in #1089 
W3ODATMD was updated to increase the size of NDS to 15, but MDS/NDS is still sized as 13 in the `W3INIT` parameter list and in `ww3_shel.f90`

**Comment by MatthewMasarik-NOAA** [comment]
Very nice catch, @ukmo-ccbunney.  I see you self-assigned, may I ask if you're also working on a fix?  I had many unexpected non-b4b's with matrix.comp for the next PR (#1083), I'm hoping resolving this may help with that.

**Comment by ukmo-ccbunney** [comment]
@MatthewMasarik-NOAA Yes - I'm happy to put a fix together for this. Watch this space :)

**Comment by MatthewMasarik-NOAA** [comment]
Awesome, thanks so much @ukmo-ccbunney !

**Comment by ukmo-ccbunney** [comment]
Also, I think the ASCII output unit numbers are not actually set when running ww3_shel, i.e. NDS(14) and NDS(15) are not defined as far as I can tell.
