### ISSUE TITLE
W3SDB1 - potential return of unitialised values

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#1106]
There is a test in the Depth Induced Breaking source term (W3SDB1) that returns immediately from the subroutine if there is zero(ish) energy:

https://github.com/NOAA-EMC/WW3/blob/8eb35962c396267b56d569ef32a27be0d5bb1657/model/src/w3sdb1md.F90#L236-L240

This is a potential source of uninitialised value errors in the model as `S` and `D` (the source and diagonal arrays) are `INTENT(OUT)` and not initialised prior to the potential return from the function:

https://github.com/NOAA-EMC/WW3/blob/8eb35962c396267b56d569ef32a27be0d5bb1657/model/src/w3sdb1md.F90#L208

The initisliastion of `S` and `D` should be moved above the return statement.

**Comment by MatthewMasarik-NOAA** [comment]
Very nice find!
