### ISSUE TITLE
THRCOU parameter is not correctly set for GQM implementation in w3snl1md

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#1126]
**Describe the bug**
changing the valeur of GQMTHRCOU has no effect with intel compiler with optimized option but it works in debug option or with gnu compiler

**To Reproduce**
./bin/run_cmake_test -f -N -S -T  -w work_ST4_T707GQM  -g ST4_T707 -i input_10ms -N ../model ww3_ts1

**Expected behavior**
it should run in 2s instead of 10s

**Screenshots**

**Additional context**
replacing the code :
```
      DO JT1=1,GQNT1
        DO IQ_OM2=1,GQNQ_OM2
          AAA=TB_FAC(IQ_OM2,JT1,JF1)*TB_TPM(IQ_OM2,JT1,JF1)
          IF (AAA.GT.AUX) AUX=AAA
          CCC=TB_FAC(IQ_OM2,JT1,JF1)*TB_TMP(IQ_OM2,JT1,JF1)
          IF (CCC.GT.AUX) AUX=CCC
        ENDDO
      ENDDO
```

by : 

```
      DO JT1=1,GQNT1
        DO IQ_OM2=1,GQNQ_OM2
          AUX=MAX(AUX,TB_FAC(IQ_OM2,JT1,JF1)*TB_TPM(IQ_OM2,JT1,JF1),TB_FAC(IQ_OM2,JT1,JF1)*TB_TMP(IQ_OM2,JT1,JF1))
        ENDDO
      ENDDO
```

Running with ddt software clearly show that intel has not optimized correctly the do loop and never goes in the if loops except if I add a print statement before to force intel to not optimize the do loop

**Comment by ukmo-ccbunney** [comment]
Nice debugging skills on this one @mickaelaccensi !
