### ISSUE TITLE
Add doxygen to the build

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/WW3#1171]
**Is your feature request related to a problem? Please describe.**
With other EMC packages, we have an ENABLE_DOCS cmake option, which causes the documentation to be built on make all.

This has several advantages, including ease of checking documentation build in CI and the ability to inject the software version into the documentation, which is important.

**Describe the solution you'd like**
Add ENABLE_DOCS option to build, and test the documentation build in CI.

**Describe alternatives you've considered**
When documenting UFS_UTILS, NCEPLIBS, UPP, and soon fv3atm, we have worked out a good way to do this which is easy for programmers.

**Additional context**
Once we are building the documentation, we can use the gh-pages branch to display it on GitHub.

**Comment by MatthewMasarik-NOAA** [comment]
@edwardhartnett, I do have a PR for this capability in the works.

**Comment by edwardhartnett** [comment]
Oh, I have one that works that I was about to put up. It matches the way we do things in the other EMC repos to build doxygen.

It also causes the documentation to be built in CI, and then uploads a copy of the built documentation to GitHub actions, so programmers can download it, in case that is of interest.

We could also arrange to put the develop branch documentation automatically on the gh-pages branch. Typically we use the gh-pages branch for the latest released version of the doxygen docs, but I don't think you have one yet.

**Comment by MatthewMasarik-NOAA** [comment]
Okay let's discuss at our meeting, because I have one worked out as well.
I've also set up hosting on gh-pages in the past as well, so I was going to
have that be a follow on Pr.

**Comment by edwardhartnett** [comment]
We would like all the EMC repos to do this the same way, so let's make sure that we end up with something that looks and works the same way as NCEPLIBS, UPP, UFS_UTILS, and (soon) fv3atm.
