### ISSUE TITLE
DIST and MPI are replaced by SHRD automatically during the compilation

### ISSUE THREAD

**Issue by aribal2018** [NOAA-EMC/WW3#1172]
Dear All,

I am installing WW3 version 6.07.

In the switch that I am using, I actually include  DIST and MPI etc.
However, in the compilation processed, these two switches have been replaced by SHRD automatically.

Now, since I am going to use implicit scheme for unstructured grid, I need to add PDLIB.

Unfortunately, PDLIB needs MPI. On the other hand, MPI is not available in my switch as it has been replace by SHRD automatically.

Is there any way to solve this issue?

I do not need DIST and MPI in my switch to be replaced by SHRD automatically.

Thank you very much.

**Comment by JessicaMeixner-NOAA** [comment]
Is it just being replaced for the pre and post processing routines?  That's expected for programs outside of ww3_multi and ww3_shel, which are the only ones that should have MPI/DIST

**Comment by aribal2018** [comment]
I am not sure where the replacement occur but once I run make_MPI, then the following error messages appear:
[axr3015@login4 bin]$ make_MPI

                ************************************
              ***   WAVEWATCH III compile for MPI  ***
                ************************************

 Exporting WWATCH3_ENV=/nethome/axr3015/WW3v607_intel20/model/bin/wwatch3.env

                *****************************
              ***   WAVEWATCH III make      ***
                *****************************

Main directory    : /nethome/axr3015/WW3v607_intel20/model
Scratch directory : /nethome/axr3015/WW3v607_intel20/model/tmp
Save source codes : yes
Save listings     : yes

[INFO] list of the programs selected : ww3_grid ww3_strt ww3_prep ww3_outf ww3_outp ww3_trck ww3_grib ww3_uprstr ww3_gspl ww3_gint gx_outf gx_outp ww3_systrk ww3_bound ww3_prnc ww3_ounf ww3_ounp ww3_bounc ww3_trnc
WARNING: NC4 is set in WWATCH3_NETCDF but not in the switch file

Making makefile ...

                *****************************
              ***   WAVEWATCH III makefile  ***
                *****************************

switch = /nethome/axr3015/WW3v607_intel20/model/bin/switch

   ***** For PDLIB, we need to have MPI as well.**

**Comment by mickaelaccensi** [comment]
you need to run w3_make instead of make_MPI if you just want to compile with SHRD. The compilation procedure is explained in the README.txt, we encourage you to use cmake now

**Comment by aribal2018** [comment]
Thanks Mickael for very clear instructions.

**Comment by mickaelaccensi** [comment]
I hope you made the compilation successfully with cmake. I close this issue.

Best,
