### ISSUE TITLE
Seg fault for IC4 regtests with namelist ww3_shel and homogeneous input field

### ISSUE THREAD

**Issue by ErickRogers** [NOAA-EMC/WW3#1180]
**Describe the bug**
I get seg faults when running IC4 regtests that are provided with the distribution but not part of the "matrix". More specifically, cases using namelist ww3_shel.nml and homogeneous input field. The ww3_shel.inp versions of the cases run ok. A case w/out homogeneous input field runs ok. Possibly, the bad behavior is more general and extends to all use of ww3_shel.nml with homogeneous input field, but I make my "issue" specific to the scenarios that I have tested myself. 

**To Reproduce**

examples of runtest  :
MODELDIR=$WW3/my_NCEP_github_fork/WW3/model
REGTESTDIR=$WW3/my_NCEP_github_fork/WW3/regtests
cd $REGTESTDIR
./bin/run_test -g 1000m -q ww3_shel -N -i input_IC4_M1 -w work_IC4_M1_NML $MODELDIR ww3_tic1.1 # DNF (uses homogeneous input field)
./bin/run_test -g 1000m -q ww3_shel -N -i input_IC4_M2 -w work_IC4_M2_NML $MODELDIR ww3_tic1.1 # DNF (uses homogeneous input field)
./bin/run_test -g 1000m -q ww3_shel -N -i input_IC4_M3 -w work_IC4_M3_NML $MODELDIR ww3_tic1.1 # DNF (uses homogeneous input field)
./bin/run_test -g 1000m -q ww3_shel -N -i input_IC4_M4 -w work_IC4_M4_NML $MODELDIR ww3_tic1.1 # DNF (uses homogeneous input field)
./bin/run_test -g 1000m -q ww3_shel -N -i input_IC4_M5 -w work_IC4_M5_NML $MODELDIR ww3_tic1.1 # DNF (uses homogeneous input field)
./bin/run_test          -q ww3_shel -N -i input_IC4_M6 -w work_IC4_M6_NML $MODELDIR ww3_tic1.1 # OK (does not use homogeneous input field)
./bin/run_test          -q ww3_shel -N -i input_IC4_M7 -w work_IC4_M7_NML $MODELDIR ww3_tic1.1 # DNF (uses homogeneous input field)

Note 1: DNF=Did not finish
Note 2: run_test script does not actually tell us about the seg-fault. It just creates empty ww3_shel.out and ww3_shel.nml.log files, which is unhelpful, but one can cd to the work dir and then link in the ww3_shel.nml and call the ww3_shel program, and there we see the result:

![segfault](https://github.com/NOAA-EMC/WW3/assets/156342000/67c67079-af99-467e-8a72-974b55262d7c)

**Expected behavior**
The run_test commands for M1,M2,M3,M4,M5,M7 cases should complete normally, similar to the run_test case for M6.

**Comment by ErickRogers** [comment]
@JessicaMeixner-NOAA @mickaelaccensi I'm not sure if I have the ability to assign this issue, but here it is.

**Comment by ErickRogers** [comment]
Results above are with Portland compiler.

**Comment by MatthewMasarik-NOAA** [comment]
Thanks for posting this @ErickRogers 👍

**Comment by ukmo-ccbunney** [comment]
Hi @ErickRogers.
I ran the IC4_M7 test using the PGI compiler and it ran fine for me (on linux).
What version are you using? I am using version 16.10-0.
Chris

**Comment by ErickRogers** [comment]
Hi @ukmo-ccbunney thanks for running the test. I'm using v15.7. I'll check to see if it runs on the gfortran that I'm using.
$ pgf90 --version
pgf90 15.7-0 64-bit target on x86-64 Linux -tp haswell 
The Portland Group - PGI Compilers and Tools
Copyright (c) 2015, NVIDIA CORPORATION.  All rights reserved.

**Comment by ukmo-ccbunney** [comment]
> Hi @ukmo-ccbunney thanks for running the test. I'm using v15.7. I'll check to see if it runs on the gfortran that I'm using. $ pgf90 --version pgf90 15.7-0 64-bit target on x86-64 Linux -tp haswell The Portland Group - PGI Compilers and Tools Copyright (c) 2015, NVIDIA CORPORATION. All rights reserved.

OK - I think I have an older version I can try to see if I can replicate your issue.

**Comment by ErickRogers** [comment]
It runs OK with gfortran.

**Comment by ukmo-ccbunney** [comment]
> It runs OK with gfortran.

I'm not surprised - I find gfortran a lot more tolerant than the other compilers!
My other version of PGFortran is actually v17, so newer, not older unfortunately.

**Comment by ErickRogers** [comment]
I'll try pgi_debug. There's also a -C flag that can be added that sometimes helps with seg faults. I'm not sure if it's in the _debug options. If not, I can test that too.

**Comment by ukmo-ccbunney** [comment]
By the way - does running in debug mode give you any hints as to the origin of the error when running with PGFortran?

To build with debug flags you need to pass `-DCMAKE_BUILD_TYPE=Debug` to cmake. You can do this when using `run_cmake_test` by setting the `CMAKE_OPTIONS` environment variable like this:

`export CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug" `

**Comment by ErickRogers** [comment]
I'm using run_test with -c pgi_debug.
I haven't been able to get run_cmake_test working though I can run with cmake and run_test (separate problem).
In any case, both the default debug flags and using -C flag gave the same unhelpful message (seg fault). 
Since the problem can (apparently) be solved by updating to a new version of pgf90, or (for certain) gfortran, and I don't really need this functionality for my work, I'm ready to throw in the towel on this one.  Maybe I should just close with comment like "possible compiler bug". What do you think?

**Comment by MatthewMasarik-NOAA** [comment]
> I haven't been able to get run_cmake_test working though I can run with cmake and run_test (separate problem).

When using `run_test` you are completely using the gnu make system.

**Comment by ukmo-ccbunney** [comment]
It certainly _feels_ like a compiler bug, especially as the newer version seems to fix it (although I can't replicate your segfault here due to lack of an older compiler version). It _could_ be exposing an issue in the code, but as it seems to be well behaved under other compiler/version, I would be inclined to not spend too much time disappearing down rabbit holes if you have a workaround!

Let's note it and move on, perhaps? :)

**Comment by ErickRogers** [comment]
> > I haven't been able to get run_cmake_test working though I can run with cmake and run_test (separate problem).
> 
> When using `run_test` you are completely using the gnu make system.

Understood. (I didn't know about the association with gnu, but I just think of it as the old/traditional WW3 build system)

**Comment by ukmo-ccbunney** [comment]
> I haven't been able to get run_cmake_test working though I can run with cmake and run_test (separate problem).

Ah - fair enough. It's actually easier to mess around with your flags with the GMake system!
You need a fairly new version of CMake for it to work with the WW3 build system  (I had to install a newer version on my system - "conda" is quite an easy way of doing that if you are familiar with it)

**Comment by MatthewMasarik-NOAA** [comment]
> Understood. (I didn't know about the association with gnu, but I just think of it as the old/traditional WW3 build system)

Okay.  I was under the impression you were moving to cmake.

**Comment by ErickRogers** [comment]
I'm closing this as a possible compiler bug (pgf90 v15.7), and we have at least two workarounds (noted above),... and this is not a pressing issue ATM. Thanks again Chris @ukmo-ccbunney for help with testing.

**Comment by ErickRogers** [comment]
> > Understood. (I didn't know about the association with gnu, but I just think of it as the old/traditional WW3 build system)
> 
> Okay. I was under the impression you were moving to cmake.

Yes, I still can use cmake for compiling outside of the regtest system, so I'm at least halfway ready for the future, as y'all remove the old build system. I will follow up on the remaining issue outside this thread. Thanks @MatthewMasarik-NOAA
