### ISSUE TITLE
Resolve compiler build 'remarks'

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [NOAA-EMC/WW3#1199]
**Describe the bug**
When building WW3 there are a few compiler `remark`s that should be resolved.

**To Reproduce**
Compile WW3 then grep through the build log for `remark`.

**Expected behavior**
Compiling should not produce any error/warning/remark/etc messages.

**Screenshots**
```
[hfe07 WW3(fix-remarks/dev/ufs-weather-model)]$ grep 'remark' build.log 
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3arrymd.F90(2255): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3arrymd.F90(2256): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3arrymd.F90(2253): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3gridmd.F90(6360): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3tidemd.F90(826): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3tidemd.F90(830): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3wavemd.F90(414): remark #6536: All symbols from this module are already visible due to another USE; the ONLY clause will have no effect. Rename clauses, if any, will be honored.   [W3ODATMD]
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/ww3_outf.F90(2426): remark #8291: Recommended relationship between field width 'W' and the number of fractional digits 'D' in this edit descriptor is 'W>=D+7'.
[hfe07 WW3(fix-remarks/dev/ufs-weather-model)]$ 
```

**Additional context**
* Addresses the WW3 component portion of this `ufs-weather-model` issue:  ufs-community/ufs-weather-model/issues/1984.  For WW3 specific see discussion post:  https://github.com/ufs-community/ufs-weather-model/issues/1984#issuecomment-1836658184.

**Comment by MatthewMasarik-NOAA** [comment]
**Status**

I've currently resolved all the remarks except the two in file, `w3tidemd.F90`, which involve the field width on a `READ`.

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA can we address these in the develop branch and then merge to dev/ufs-weather-model?

**Comment by MatthewMasarik-NOAA** [comment]
@mickaelaccensi, I was curious if you could comment on the following code.  For the two `READ`s below, would it be OK with you to adjust the field width for the `E` descriptors so they satisfy '`W>=D+7`'?

https://github.com/NOAA-EMC/WW3/blob/e085bcfa4e735100dcb5a7185cd3cb655f0673e3/model/src/w3tidemd.F90#L824-L832

Satisfying the equality would take `E16.10` to `E17.10`, and change the two READs to this:
```
READ(KR1,'(4X,A5,E17.10,i5)')TIDE_KONAN(K),TIDE_SIGAN(K),TIDE_NINF(k)
```
and
```
read(kr1,'(4X,A5,E17.10,2F10.3)') TIDE_KONIN(K,k2),TIDE_SIGIN(K,k2),TIDE_R(K,k2),TIDE_ZETA(K,k2)
```

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA can we address these in the develop branch and then merge to dev/ufs-weather-model?

@JessicaMeixner-NOAA, yes I think that should be straightforward.  I'll confirm the compiler output for the `develop` branch and update the header accordingly.

**Comment by mickaelaccensi** [comment]
it should be fine. You can double check it works by running ww3_tp2.18.

Further in the code, it is even written in F12.9 format ....

```
            write(lp,79) TIDE_KONIN(k,k2),TIDE_SIGIN(k,k2),TIDE_ampci(k,k2,idef), &
                 TIDE_phgi(k,k2,idef)
79          format(5x,a5,4x,f12.9,15x,f10.4,5x,f10.4)
```

**Comment by MatthewMasarik-NOAA** [comment]
that's great to hear.  thanks @mickaelaccensi for your quick reply.  I'll do the check of ww3_tp2.18 -- thanks for that suggestion!

**Comment by MatthewMasarik-NOAA** [comment]
**update** 

'`dev/ufs-weather-model` branch' has be taken out of the title and header.  A PR with fixes for this issue will be submitted to the `develop` branch first, then synced from `develop` into `dev/ufs-weather-model`.

**Comment by MatthewMasarik-NOAA** [comment]
**note**

The `USE` statement that generate this `remark` in `dev/ufs-weather-model`

```
/scratch1/NCEPDEV/climate/Matthew.Masarik/projs/UFS/support/WW3/model/src/w3wavemd.F90(414): remark #6536: All symbols from this module are already visible due to another USE; the ONLY clause will have no effect. Rename clauses, if any, will be honored.   [W3ODATMD]
```

is _not_ found in the `develop` branch, so will need to be added in when syncing into `dev/ufs-weather-model`.
