### ISSUE TITLE
Triads

### ISSUE THREAD

**Issue by aronroland** [NOAA-EMC/WW3#12]
Triads do not alter the results in the right direction and magnitude (2019). Looking into things I did some rewrite and found that the explicit part of the source term was off by a factor of 2. Moreover, reallocation would cause issues and run-time penalty. I rewrote following the WWM implementation

**Comment by ajhenrique** [comment]
@aronroland is working with @thesser1 on this + solving lateral boundary conditions issues.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland @thesser1 is this work that's still ongoing or should we go ahead and close this issue?
