### ISSUE TITLE
Update NCEP regtest modules for Rocky8 transition on hera

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#1205]
**Is your feature request related to a problem? Please describe.**
Need to update modules to use rocky8 builds on hera.  Will also use this opportunity to update to the newest spack-stack 1.6.0 

**Describe the solution you'd like**
Updates to regression tests to run on rocky8 nodes. 

**Describe alternatives you've considered**
none. 

**Additional context**
Will need intel (and ideally gnu) builds of METIS on hera for rocky8.

**Comment by JessicaMeixner-NOAA** [comment]
I am planning to add the update for transition to my branch here: https://github.com/JessicaMeixner-NOAA/WW3/tree/feature/gnu 

@MatthewMasarik-NOAA we do need SpackStack 1.6.0+rocky for METIS with intel at a minimum.  Ideally we need this for gnu on hera as well, but we could wait.  For orion and hercules, I can see if the old build of metis with spack-stack 1.5 is working or we can rebuild with 1.6.0.  What is your preference?

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA I can do both compiler builds (intel, gnu) for each machine (hera, orion, hercules) with rocky8 + spack-stack 1.6.0.  It may be helpful for us to track each machine individually to help managing this transition.  The timeline for the builds to be finished is early next week.  Let me know if you have an order preference with respect to compiler and machine and I will prioritize to process those first.

>For orion and hercules, I can see if the old build of metis with spack-stack 1.5 is working or we can rebuild with 1.6.0. What is your preference?

I'm not sure if I understand the intent here, but I think just building with 1.6 may be the cleanest way forward.  Let me know if I missed something, though.

**Comment by JessicaMeixner-NOAA** [comment]
@MatthewMasarik-NOAA builds with 1.6 on orion and hercules are the preferable but if time was an issue, seeing if the 1.5 builds work was  an option.     

Early next week for the builds will be great!

**Comment by MatthewMasarik-NOAA** [comment]
> @MatthewMasarik-NOAA builds with 1.6 on orion and hercules are the preferable but if time was an issue, seeing if the 1.5 builds work was an option.
> 
> Early next week for the builds will be great!

@JessicaMeixner-NOAA okay, good deal.  I'll proceed to get 1.6 based builds on each machine, for early next week.
