### ISSUE TITLE
ww3_ounf.ftn, subroutine W3EXNC declaration of NCIDS

### ISSUE THREAD

**Issue by CarstenHansen** [NOAA-EMC/WW3#121]
I am trying to understand how output of different variables may be divided to individual NetCDF files and noticed this issue:

In ww3_ounf.ftn the list of possible individual NetCDF file ID's is allocated as:
https://github.com/NOAA-EMC/WW3/blob/39d1fb73d8ffde828e3070eafc49f6fd5951dfdb/model/ftn/ww3_ounf.ftn#L385

In SUBROUTINE W3EXNC the argument `NCIDS` should then be declared as either:
`INTEGER, INTENT(INOUT) :: NCIDS(NOGRP,NGRPP,NOSWLL + 1)`
or with an assumed shape (I think) as:
`INTEGER, INTENT(INOUT) :: NCIDS(:,:,:)`

The present code assumes `NOSWLL == 5`:

https://github.com/NOAA-EMC/WW3/blob/39d1fb73d8ffde828e3070eafc49f6fd5951dfdb/model/ftn/ww3_ounf.ftn#L760

**Comment by CarstenHansen** [comment]
Close this issue, as the suggested bug fix was quickly incorporated by @ajhenrique  in the feature PR #119 and thereafter merged into develop, commit https://github.com/NOAA-EMC/WW3/commit/5ab43010002d0a4e175e7647828fbf9e989ab5f7

**Comment by ajhenrique** [comment]
Indeed @CarstenHansen , after asking if you had mistakenly added that comment to another thread I noticed that change would benefit applications at NCEP where we have NOSLL = 3. Serendipity. Thank you.
