### ISSUE TITLE
WW3 FTP data not available

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [NOAA-EMC/WW3#1217]
**Describe the bug**
The FTP data (ww3_from_ftp.v7.14.1.tar.gz) currently cannot be retrieved from the server.

**To Reproduce**
Clone the WW3 repository, then run the FTP download step.  From the root directory, `./model/bin/ww3_from_ftp.sh`.

**Expected behavior**
The data should be available and be downloaded to a local gzip file.

**Screenshots**
NA.

**Additional context**
NA

**Comment by JessicaMeixner-NOAA** [comment]
Issues with ftp have been resolved and data is present.

**Comment by MatthewMasarik-NOAA** [comment]
> Issues with ftp have been resolved and data is present.

Thanks for following up on this @JessicaMeixner-NOAA!
