### ISSUE TITLE
Cannot find mww3_case_0[1-3] & input data in repo

### ISSUE THREAD

**Issue by alexandrefierro** [NOAA-EMC/WW3#1227]
Greetings:

The NOAA documentation for this version of the model (6.07) alludes to the following files/directories below, which are nowhere to be found in this repo. Could thus someone point me toward the location where users can get access to these files? Thank you! 

Finally, the cases directory hold the real-world test cases as described below.
mww3_case_01 Atlantic case with five grids focusing on Trondheim. 
mww3_case_02 Pacific case with three grids focusing on Alaska. 
mww3_case_03 Original multi-grid case used as global model at NCEP.

Each of these cases is a single script executing the entire model run. Before executing the script, compile the model with the switches indicated in the documentation at the head of the script. Additional data used by these scripts is contained in the directories:

mww3_data_00 Wind fields and ice data used by all example cases. 
mww3_data_nn Specific data needed for script mww3 case nn.

**Comment by JessicaMeixner-NOAA** [comment]
Hi @alexandrefierro  We have stopped supporting the cases in the develop branch  (please see issue: https://github.com/NOAA-EMC/WW3/issues/653 for some additional details).
