### ISSUE TITLE
OMP flags not generated when using cmplr.env

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#124]
Reference: issue #19 

I think there is an issue with the way that OMP settings are handled in the `cmplr.env` file.

Currently, OMP compiler flags are only enabled if the `$omp_mod` environment variable is set to "yes", but this is not set anywhere in the file, or in `w3_setup` which uses `cmplr.env` file to produce the `comp` and `link` scripts.

This means that if you set up a comp/link script using `w3_setup` and an entry in `cmplr.env`, it will never contain any OMP flags. `w3_make` will set the `omp_mod` environment variable depending on the program being built, but this will not have any affect as the generated comp/link files do not contain any tests on `$omp_mod`.

Unless I am mistaken, the comp.tmpl and link.tmpl files need to contain a section like the following:
```
if [ "$omp_mod" = 'yes' ]
  then
    opt="$opt $opt_omp"
fi
```

where `$opt_omp` is set in the cmplr.env file. 

The references to `$omp_mod` in cmplr.env should then be removed and the OMP flags should always merged into the comp/link files by `w3_setup`.

**Comment by ukmo-ccbunney** [comment]
See following UKMO/bf_gencomp branch: cb01247
@mickaelaccensi and @ajhenrique - what do you think?

**Comment by mickaelaccensi** [comment]
I agree with your way to handle the OMP flag, it's sounds good to me
