### ISSUE TITLE
Grid Generation Error for Indian Ocean in WW3 v6.07 

### ISSUE THREAD

**Issue by CHARANJULURI** [NOAA-EMC/WW3#1241]
Dear WW3 Community Members,

I am the new user of WaveWatch III (WW3) version 6.07. I am currently facing difficulties in generating a grid for the Indian Ocean region. Despite following the recommended procedures, I am encountering an error during the grid generation process. The specific error message I receive is: [W3DIMX]
![Screenshot (1)](https://github.com/NOAA-EMC/WW3/assets/171133560/f00c87bd-4f8e-4411-a7ce-1b34ce02d48f)
[ww3_grid.nml.txt](https://github.com/user-attachments/files/15546394/ww3_grid.nml.txt)

To aid in diagnosing this issue, I have attached my current namelist file to this email. I am hopeful that someone in the community might be able to shed light on the cause of this error and provide suggestions for resolving it.

In particular, I would be grateful for assistance in understanding the meaning of the error message and identifying any potential problems with my namelist file.  Additionally, any general tips or troubleshooting steps specific to grid generation for the Indian Ocean region would be immensely helpful.

Thank you in advance for your time and consideration. I look forward to your valuable insights and expertise in overcoming this hurdle.

Sincerely,
J.CHARAN KUMAR

**Comment by mickaelaccensi** [comment]
Dear J.CHARAN KUMAR,

The error message is provided by WW3 when 
```
   IF ( MX.LT.3 .OR. (MY.LT.3.AND.GTYPE.NE.UNGTYPE) .OR. MSEA.LT.1 ) THEN
      WRITE (NDSE,1003) MX, MY, MSEA, GTYPE
      CALL EXTCDE (3)
    END IF
```
which means that you have either:
-less than 3 points along x-axis
-less than 3 points along y-axis
-less than 1 point which is considered a sea point

Looking at your configuration, it is probably the sea point the issue, especially the scale factor apply at -1 on the depth file. The depth value must have negative values under the mean sea level.

Look into the depth file to see if values are negative, if yes, just set the scale factor at 1.

Let us know if it solve your issue

Best,

Mickael

**Comment by CHARANJULURI** [comment]
Dear Mickael Sir,

I would like to extend my sincere thanks to the Wave Watch III community, especially Mickael Sir, for their invaluable assistance in responding to my problem statement. Your collective insights, advice, and solutions were instrumental in resolving the issue I faced. I truly appreciate the time and effort each of you invested in helping me. Your willingness to share your expertise and support demonstrates the strength and generosity of this community. Thank you once again for your invaluable assistance.

Sincerely,
J.CHARAN KUMAR

**Comment by mickaelaccensi** [comment]
you're welcome !
