### ISSUE TITLE
The recent commit 629d27a has added a Github actions file (regtest_gnu) that fails with a syntax error message

### ISSUE THREAD

**Issue by CarstenHansen** [NOAA-EMC/WW3#1251]
**Describe the bug**
I update WW3 on my repository with:
> git pull https://github.com/NOAA-EMC/WW3.git develop
> git push origin develop # where origin is git@github.com:CarstenHansen/WW3.git

Upon push to my own Github repositoty, three 'Actions' are run, of which the third (regtest_gnu) is a new one in commit 629d27a and fails with the annotation:

"Invalid workflow file: .github/workflows/regtest_gnu.yml#L95
You have an error in your yaml syntax on line 95"

**To Reproduce**
I update WW3 on my repository with:
> git pull https://github.com/NOAA-EMC/WW3.git develop
> git push origin develop # where origin is git@github.com:CarstenHansen/WW3.git

Then Github runs the thee 'Actions' _GNU Linux Build_, _Intel Linux Build_, and _regtest_gnu_.

**Expected behavior**
I wouldn't care if the file regtest_gnu.yml was omitted. But it should not have a syntax error.

**Screenshots**

**Additional context**
I am not familiar with Spack, but I tried to check the file regtest_gnu.yml file with [https://rhysd.github.io/actionlint/](https://rhysd.github.io/actionlint/) . It seems that lines 95 and 94 have no syntax errors, and hence there may be a complex of other code errors.

**Comment by MatthewMasarik-NOAA** [comment]
Thanks for catching this @CarstenHansen, I'm looking into it now.

**Comment by MatthewMasarik-NOAA** [comment]
@CarstenHansen - I found two small bugs that when fixed, get you passed the failure.  This allows the regtest to complete successfully, but then it fails later in the commands that try to compare output files after the run.  I have a branch with the two fixes, and that also comments out those last file check commands, which just passed all github CI successfully.   I'll push this as a draft PR now, given the federal holiday tomorrow, and Jessica is also on leave.  I'd like to let her and @edwardhartnett have a chance to weigh in on whether this is a reasonable fix.  If no big changes are suggested, which I don't foresee, we should be able to process this on Thursday.

**Comment by MatthewMasarik-NOAA** [comment]
Draft PR:  https://github.com/NOAA-EMC/WW3/pull/1253

**Comment by CarstenHansen** [comment]
The draft PR #1253 solves this issue perfectly.
