### ISSUE TITLE
w3_automake bug

### ISSUE THREAD

**Issue by Jialunx** [NOAA-EMC/WW3#1265]
w3_automake does not run in full on the newest WW3 version.

Screenshots

Exporting WWATCH3_ENV=/home/ww3/WW3/model/bin/wwatch3.env
Shared Object : No

[INFO] list of the programs selected : ww3_strt ww3_bound ww3_outf ww3_outp ww3_trck ww3_grib ww3_gint gx_outf gx_outp ww3_uprstr ww3_systrk ww3_gspl ww3_prep ww3_shel

[INFO] SEQ progs : ww3_strt ww3_bound ww3_outf ww3_outp ww3_trck ww3_grib ww3_gint gx_outf gx_outp ww3_uprstr ww3_systrk ww3_gspl ww3_prep ww3_shel

            *****************************
          ***   WAVEWATCH III make      ***
            *****************************
Main directory : /home/ww3/WW3/model
Scratch directory : /home/ww3/WW3/model/tmp
Save source codes : yes
Save listings : yes
Shared Object : No

[INFO] list of the programs selected : ww3_strt ww3_bound ww3_outf ww3_outp ww3_trck ww3_grib ww3_gint gx_outf gx_outp ww3_uprstr ww3_systrk ww3_gspl ww3_prep ww3_shel
Making makefile ...

            *****************************
          ***   WAVEWATCH III makefile  ***
            *****************************
switch = /home/ww3/WW3/model/work_SEQ/switch.SEQ
Checking all subroutines for modules (this may take a while) ...

The operation crash here.

**Comment by JessicaMeixner-NOAA** [comment]
Hi @Jialunx - for the newest version of WW3 develop, we recommend using cmake instead of w3_automake

**Comment by Jialunx** [comment]
Thank you, @JessicaMeixner-NOAA.

**Comment by Rach3025** [comment]
Hello, I am having the same problem, have you solved it?  I really want to know how to solve it specifically, thanks.
