### ISSUE TITLE
Extra line in ww3_shel.ftn

### ISSUE THREAD

**Issue by AndresSepulveda** [NOAA-EMC/WW3#13]
I had an error runinng ww3_shel, it complained about a problem reading ww3_shel.inp

Diving in the code, seems this can be fixed by commenting an extra READ in line 1303

From
              READ (NDSI,*,END=2001,ERR=2002) IPRT, PRTFRM
!/DEBUGINIT              write(740+IAPROC,*), 'Before reading IPRT'
!/DEBUGINIT              write(740+IAPROC,*), 'Before read 2002, case 10'
              READ (NDSI,*) IPRT, PRTFRM
!/DEBUGINIT              write(740+IAPROC,*), ' After read 2002, case 10'

to
              READ (NDSI,*,END=2001,ERR=2002) IPRT, PRTFRM
!/DEBUGINIT              write(740+IAPROC,*), 'Before reading IPRT'
!/DEBUGINIT              write(740+IAPROC,*), 'Before read 2002, case 10'
!!!              READ (NDSI,*) IPRT, PRTFRM
!/DEBUGINIT              write(740+IAPROC,*), ' After read 2002, case 10'

**Comment by JessicaMeixner-NOAA** [comment]
To be able to help, we need to know what switch you used to compile the code and what your ww3_shel.inp file is.

**Comment by AndresSepulveda** [comment]
Hi, thanks for the help. Here are the files

[switch.txt](https://github.com/NOAA-EMC/WW3/files/3095548/switch.txt)

[ww3_shel.inp.txt](https://github.com/NOAA-EMC/WW3/files/3095550/ww3_shel.inp.txt)

**Comment by ajhenrique** [comment]
@AndresSepulveda it looks like this was an issue introduced in revision [4994ca](https://github.com/NOAA-EMC/WW3/commit/4994ca64545d39b871ffbc229119046b66b8f9d8). @mickaelaccensi could you please check? It looks like line [1300](https://github.com/NOAA-EMC/WW3/blame/master/model/ftn/ww3_shel.ftn#L1300) was introduced with the intention of replacing line [1303](https://github.com/NOAA-EMC/WW3/blame/master/model/ftn/ww3_shel.ftn#L1303), but line 1303 was never deleted?

**Comment by mickaelaccensi** [comment]
the line 1300 must be deleted :
            READ (NDSI,*,END=2001,ERR=2002) IPRT, PRTFRM

**Comment by AndresSepulveda** [comment]
ok, thanks.

**Comment by ajhenrique** [comment]
@mickaelaccensi do you think this bugfix would warrant a HF to the master? IOW, would this cause the code to fail in a way that would significantly affect usage of ww3_shel? In any case, could either you or @AndresSepulveda create a BF branch from your fork, fix the issue and submit a pull request?

**Comment by mickaelaccensi** [comment]
ok I'll do it next week

**Comment by mickaelaccensi** [comment]
@AndresSepulveda can you close this issue since it has been integrated into master and develop branches. thanks
