### ISSUE TITLE
Better handling of error/warning grepping when using cmplr.env

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#130]
When compiling a particular source file, the compiler erros and warnings are grepped from the file in the "comp" script. When using the `cmplr.env` file to generate the comp/link files, the grep pattern is hardcoded to the simple strings "error" and "warning".

For some compilers this is not specific enough to capture _only_ the specific compiler messages. 

For instance, the cray compiler adds it's own summary message that includes the words "error" and "warning" and these are incorrectly being counted as actual error messages.

Therefore, I propose that the search pattern used in the generated `comp` file can be specified in the `cmplr.env` file. It should default to "error" / "warn" and be overriden where necessary.

**Comment by ukmo-ccbunney** [comment]
Commit 46ff3ef4 details implementation on UKMO bf_gencomp branch.
@mickaelaccensi - do you approve?

**Comment by mickaelaccensi** [comment]
I fully approve !

**Comment by ukmo-ccbunney** [comment]
Thanks @mickaelaccensi !  Could you also cast your expert eye over #124 and let me know if you agree with the changes proposed there too? Thanks.
