### ISSUE TITLE
Nonliear wave interaction source term using wave spectra

### ISSUE THREAD

**Issue by Jialunx** [NOAA-EMC/WW3#1311]
Dear WW3 team,

I would like to know if there is an option to input multiple wave spectra (i.e., at different time steps) in WaveWatch III and obtain their corresponding nonlinear wave interaction source terms as output.

Thank you very much for your help.

**Comment by stefanzieger** [comment]
You can use a single point model as in `regtests/ww3_ts1`, prescribe the spectra in ww3_strt.inp `ITYPE=4` and ouput the first time step. The request source terms in point output post-processor (`ITYPE=3`).

Alternatively, you can write your own `pnt_out.ww3` file with spectra and run point output. The structure of the binary file is described in `ww3_outp.inp` under transfer file.

**Comment by Jialunx** [comment]
Hi @stefanzieger,
Thank you very much for your help. For the second approach, I am wondering if there is any example of pnt_out.ww3 file?
