### ISSUE TITLE
./model/bin/ww3_from_ftp.sh  - missing 'tempor'-folder

### ISSUE THREAD

**Issue by oleaarnes** [NOAA-EMC/WW3#1326]
When trying to setup WW3, i.e. running './model/bin/ww3_from_ftp.sh' the folder 'tempor'  seems to be non-existing
![Capture](https://github.com/user-attachments/assets/a872f695-48f9-4be2-8911-3c285a244486)

**Comment by Crystal5172117** [comment]
Hello,olearnes! Regarding the “missing ‘tempor’-folder” issue, how did you end up resolving it? Appreciate your insight.
