### ISSUE TITLE
WAVEWATCH III Developer Meeting Wed 22 Jan 2020 2:30pm ET

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#153]
WAVEWATCH III Developer Meeting

Quasi-Bi-Monthly Call to discuss the development of WAVEWATCH III

During this first 2020 meeting (Jan 22nd) we will have a presentation by Dr Tom Durrant from Oceanum (Ocean Numeric) focusing on advanced applications of WAVEWATCH III in the MetOcean consultancy industry. 

We will also present a summary of recent developments included in our GitHub repository. The meeting will end with an open forum where all developers can express their ideas and suggestions as well as ask any questions relevant to the development community. 

This meeting will be hosted by NCEP.

Join Hangouts Meet
meet.google.com/pwq-vnuq-ady

Meeting ID
meet.google.com/pwq-vnuq-ady

Phone Numbers
(‪US‬)
‪+1 669-220-6039‬
PIN: ‪938 966#‬

@12cm103
@ADevisM
@Adraak
@aejester
@ajhenrique
@ajkammerer93
@alessandrodbt
@aliabdolali
@anhcanh2002
@AntoniosMekhiel
@apchoi79
@bauj0001
@benoitp-cmc
@bgin
@bohlinger
@BoWeiWu2019
@brackins-john
@brandaodeco
@breichl
@CarstenHansen
@cecastro
@ChloeSarah13
@chrishalbert
@Clarenburg
@cqhhting
@DiegoGutierrez2210
@djcrowley4
@djtitze
@dongming007
@dsadova
@elhou76
@emezac63
@erinconv
@fabio-p-piccoli
@FCOO
@ferthal
@flampouris
@fmlokt
@fradscnr
@GabySalgado
@graig-sutherland
@GumpDong
@hansroyer
@hellais
@hkershaw-brown
@huangynj
@hyunslife
@j-gonzalezlopez
@janepen
@JeffOskamp
@jessicaborgesp
@JessicaMeixner-NOAA
@jianhuaqi
@JoaoGRRodrigues
@kayo-ide
@krsteffen
@lauryrenac
@lhaftc
@lileipku00
@ling2019
@Maria0806
@mary-chen
@MarziehDerkani
@menta78
@Miazhi
@MicahDavid
@MichelCF
@mickaelaccensi
@mincrt
@mithundeb
@mjtp
@mmuscato
@nacbrother
@nikolovai
@paoelvirtual
@QingxiangLiu
@randobucci
@RCayetanoM
@RichardMGorman
@rickyspaceguy
@RobertoPadilla-NOAA
@royabc760
@sahammhd
@SallyDillon12
@seglion
@smcsweeney101
@SMoorthi-emc
@tiagofaro
@tomdurrant
@ukmo-ccbunney
@vaduraes
@vieirarc
@wangtlum
@wavespotter
@wenfanwu
@XianwuXue-NOAA
@xuexianwu
@xychengso
@YoungjaeYu
@yuemaaa
@yuwana1989
@zhangliangl
@zhongtouwang2019

**Comment by ajhenrique** [comment]
This was a great meeting, thanks to Tom Durrant for a great presentation on dockers, and to all present!

**Comment by janepen** [comment]
Hi @ajhenrique , I am sorry to miss this meeting. Would you please be able to share the PPTs? Thank you.

**Comment by ajhenrique** [comment]
Hi @janepen PPts have been added as link to our News page: https://github.com/NOAA-EMC/WW3/wiki/WW3-News
