### ISSUE TITLE
Variable declarations missing/wrong in OMP loops 

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#159]
Several variables/arrays used in OpenMP loops are not declared PRIVATE or declared PRIVATE when they should be shared etc. NCEP is reviewing. Many affect output of gridded/point data. A regtest with all possible parameter output options should be created to be run with MPI/OMP and subsequent runs to test for b4b reproducibility which would assert the least that variables have been initialized and OMP loops have proper declarations.

**Comment by ajhenrique** [comment]
Add DEFAULT NONE to OMP loops to check if variables are properly declared.

**Comment by JessicaMeixner-NOAA** [comment]
The specifics of this isssue have been lost over time.  It's unclear if these have already been addressed or there are still open issues.  We're closing the issue for now but it can be reopened or new issues can be created.
