### ISSUE TITLE
ST4 TEST500 : variable SSDSC misused

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#164]
misused of SSDSC(1) which is used to switch from ST4 parameterization T570 to T500
initially SSDSC(1) was filled by SDSC1 from SDS4 namelist. Now it is filled by SDSLFGEN variable
see branch bugfix/T500 on https://github.com/umr-lops/WW3

**Comment by ardhuin** [comment]
This is fixed in the ST4tail branch.
