### ISSUE TITLE
Issue running ww3_shel in v6.07

### ISSUE THREAD

**Issue by iman-j** [NOAA-EMC/WW3#171]
Hi all,

When running ww3_shel I hit the following error (almost instantly when ww3_shel is run):
------------------------------------
free(): invalid pointer

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7fd2fc78e31a
#1  0x7fd2fc78d503
#2  0x7fd2fbbdbf1f
#3  0x7fd2fbbdbe97
#4  0x7fd2fbbdd800
#5  0x7fd2fbc26896
#6  0x7fd2fbc2d909
#7  0x7fd2fbc34e1b
#8  0x560f667e8102
#9  0x560f667a8e97
#10  0x560f667a3108
#11  0x7fd2fbbbeb96
#12  0x560f667a3139
#13  0xffffffffffffffff
------------------------------------

Here are the switch and ww3_shel.inp files for reference

[switch.txt](https://github.com/NOAA-EMC/WW3/files/4248238/switch.txt)
[ww3_shel.inp.txt](https://github.com/NOAA-EMC/WW3/files/4248239/ww3_shel.inp.txt)

Also just noting that I am using the latest version and can confirm that as suggested by Issue #13, line 1300 (READ (NDSI,*,END=2001,ERR=2002) IPRT, PRTFRM) is removed from ww3_shel.ftn before building the binaries.

Any help you can provide is much appreciated!

**Comment by iman-j** [comment]
For anyone else having this issue, it appears that the point outputs was responsible for this error. 
When I removed my original points, the ww3_shel proceeded to evaluate the model as expected.

**Comment by aliabdolali** [comment]
@iman-j It seems it has been resolved. Please reopen a new issue if it hasn't.

**Comment by iman-j** [comment]
Please re-open this issue. This is a bug in WW3 and the only way to circumvent the issue is to reduce the number of output points. The points are valid but somehow a unknown number of points causes this error. The limit seem to be arbitrary, or at least to me.
