### ISSUE TITLE
Speed up initialization   

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#176]
In multiple operational systems at NCEP, the WW3 initialization is slow and causing the other components in coupled models to wait. 

In GFSv16
WW3 initialization is taking at least double the initialization time than ATM is. A major part of this according to @ajhenrique  is the reading and initializing the remapping/grid reconciliation coefficients. 

For HWRF,  IBM noticed:
>>Informed user that WW3 is reading input files from all MPI ranks (192), 8 nodes, and
>>       that this is inefficient on surge/luna.  This probably has negative impact
>>       on entire system for the first 3 or 4 minutes of HWRF run.

This issue is to track causes and potential fixes for the slow initialization of WW3 in general with the specific goals of speeding up initialization in coupled applications at NCEP. 

* A suggestion from @arunchawla-NOAA is to implement parallel netcdf read/write optimization utilized in GSI.

**Comment by JessicaMeixner-NOAA** [comment]
From Erick Rogers via email: 

MAPBDI and .nc steps are separate, so we should isolate which it is causing the slow down. 

If it is MAPBDI...there is a switch (MPIBDI) option to activate parallel compute of this. I remember that it was causing issues at least for some compilers (seg faults, maybe?), so we stopped using it.

MAPBDI is a loop which computes distances between boundary points and computational points. This gives a lot of combinations (lot of loop nesting), so it can be very slow.

If the MPI-MAPBDI thing doesn't work, here are two other thoughts
1) pre-compute the distance arrays and save in .nc files?
2) optimize the distance calcs, e.g. by being smarter about it. esp. I
don't think the distance needs to be computed for all points. "far away"
is enough info, without giving an actual number.

Another thought: 
Instead of pre-computing MAPBDI, it may be possible to compute the downstream variable instead (i.e. the source grid selection). This would be a smaller piece of data.

The trouble is, this code is already quite messy with if-then statements, and adding new precompute capability will just make that worse. (i.e. code readability and debugability will suffer)

**Comment by JessicaMeixner-NOAA** [comment]
@ajhenrique put timing statements in /gpfs/dell2/emc/modeling/noscrub/WAVE_glopara/global-workflow_gfsv16b/sorc/fv3gfs.fd/WW3/model/tmp/wmgridmd.F90 and the output can be found in /gpfs/dell3/stmp/emc.glopara/RUNDIRS/waveiau768z/2020030300/gdas/waveiau768z_gdasfcst_00.18673365/fort.55

From @ajhenrique email:

> Look for "WMGHGH, BEGINNING BOTTLENECK LOOP AT" near line 1373, that is where the target section starts. The first loop starts being set up near line 1428 of the ftn file, and begins near line 1454. The second loop which in our case takes more time starts near line 1483. The entire loop section ends near line 3188 (a lot of comment lines). Relevant parts of the code that make it to the compiled .F90 file we use are labeled with switches  !/SCRIP, !/SCRIPNC, !/DIST, !/MPI. You will see sections with previous parallelization attempts labeled !/MPIBDI.

**Comment by JessicaMeixner-NOAA** [comment]
@ajhenrique  said the reading of the netcdf files for the remapping only took 10 seconds.  On top of that @CoryMartin-NOAA said that moving to a parallel read only provides an advantage for large files (say >500MB)  and the rmp_src_to_dst_conserv_*.nc files in the GFSv16 case are only 38MB.

**Comment by ajhenrique** [comment]
@JamesAbeles-NOAA` has provided a solution that reduces significantly the initialization time when using OpenMP as follows. In experiments at NCEP the initialization time for a three-grid mosaic with 1/6 deg global core and two 9km polarstereographic grids came down from ~240s to ~70s.

From @JamesAbeles-NOAA: "_I added the 2 highlighted lines in wmgridmd.ftn. Please use these and make sure they work for you._"

**_`!/OMPH/!$OMP parallel do private(idst,jdst,dd),SCHEDULE(dynamic)`_**
                        DO IDST=NX_BEG(IMPROC), NX_END(IMPROC)
                           DO JDST=1, NY
                              IF (ABS(MAPSTA(JDST,IDST)) .EQ. 1) THEN
                                 !....find distance to this boundary point.
                                 DD=FACTOR*W3DIST(FLAGLL,XGRD(JDST,IDST), &
                                    YGRD(JDST,IDST),XGRD(JBND,IBND), &
                                    YGRD(JBND,IBND))
! Notes: The origin of "0.58 * GRAV" is to translate from distance (in meters)
! to time (in seconds) required for a wave to travel from the boundary to point
! JDST,IDST based on a specific group velocity 0.58*grav would be the group  
! velocity of a 7.3 s wave in deep water. Significance of T=7.3 s is explained
! in notes by HT below.                                 
                                 DD=DD/ ( 0.58 * GRAV )
                                 MAPBDI(JDST,IDST)=MIN(MAPBDI(JDST,IDST),DD)
                              ENDIF
                           END DO ! DO JDST
                        END DO ! DO IDST
**_`!/OMPH/!$OMP END PARALLEL DO`_**

**Comment by JessicaMeixner-NOAA** [comment]
This issue was addressed for v16 of GFS which was the initial motivation of this issue.  As work for that has completed I am going to close this issue.  However, initialization can always continue to be sped up.
