### ISSUE TITLE
RWND switch is not in manual

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#179]
The RWND switch does not appear to be in the manual (at least when you grep fro RWND in the manual directory, there are no results).

**Comment by ukmo-ccbunney** [comment]
@JessicaMeixner-NOAA It's in `impl/switch.txt` at line 345. It's in lowercase, which is maybe why your grep failed?

https://github.com/NOAA-EMC/WW3/blob/7823bd245ed98df295ac8b6c437903e131101666/manual/impl/switch.tex#L345

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @ukmo-ccbunney  I din't -i in the grep... oops :D Thanks!
