### ISSUE TITLE
Merge Hotfix HF_ounfpart branch to NOAA-EMC/WW3 master and develop 

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#18]
The following hotfixes will be merged to NOAA-EMC/WW3 master and develop:
* Bugfix in ww3_ounf.ftn: NBIPART check against NOSWLL. See #2.
* Updating link files for grib compile, change to ww3_uprstr for clean compile with OMPH OMPG flags,
* Option for writing to fixed netcdf gridded output file with NCO switch (more appropriate fix in v7, see #8).
* DB1 depth-breaking_bugfix: added proper scaling coefficients for radian freq. [radHz]. See #7.

The update affects the following downstream forks:
@ajhenrique ajhenrique / WW3
@aliabdolali aliabdolali / WW3
@erdc erdc / WW3
@flampouris flampouris / WW3
@hellais hellais / WW3
@huangynj huangynj / WW3
@j-gonzalezlopez j-gonzalezlopez / WW3
@JessicaMeixner-NOAA JessicaMeixner-NOAA / WW3
@lileipku00 lileipku00 / WW3
@rickyspaceguy rickyspaceguy / WW3
@sahammhd sahammhd / WW3
@tomdurrant tomdurrant / WW3
@ukmo-waves ukmo-waves / WW3
@umr-lops umr-lops / WW3
@wavespotter wavespotter / WW3
@xuexianwu xuexianwu / WW3
@yuemaaa yuemaaa / WW3
@yuwana1989 yuwana1989 / WW3
@zhongtouwang2019 zhongtouwang2019 / WW3

**Comment by ajhenrique** [comment]
HF_ounfpart containing the hotfixes was merged to master on 19 April 2019:
https://github.com/NOAA-EMC/WW3/commit/b582f8cbc82aec6f13a66a58c661fba4ae24e4ee

HF_ounfpart was merged to develop on 23 April 2019:
https://github.com/NOAA-EMC/WW3/commit/2b1ea78a34183d0c17d4802487dcfa856141730b

**Comment by flampouris** [comment]
Hi @ajhenrique,
What was the issue with the ww3_uprstr? The only apparent difference to the ww3_uprstr code is the removal of the "$" from the comments.

**Comment by ajhenrique** [comment]
Hi @flampouris! 
The '$' were being interpreted by the openmp compiler as OMP instructions and the compilation was crashing. Removing the '$' fixed the issue.
Cheers!

**Comment by flampouris** [comment]
Thank you.

**Comment by flampouris** [comment]
Thank you!
