### ISSUE TITLE
Generalization of comp/link scripts -> cmplr.env + [comp|link].tmpl

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#19]
A multitude of comp/link scripts for specific applications/machines, some deprecated, populates the model/bin directory. @mickaelaccensi has whipped up a set of template comp/link files with and env-setting script that is lined up to replace individual comp/link files, inc association with the w3_setup script. The work will require collaboration between users to make sure the new approach works across platforms. An idea is to include modulefiles use in compilation across machines to help users and developers in their initial model setup.

**Comment by ajhenrique** [comment]
@ajhenrique will update esmf directory scripts and start a new branch for generalization work.

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi @aliabdolali is the only remaining to do for this to delete the comp & link files for specific platforms that still remains?

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi your comment on PR https://github.com/NOAA-EMC/WW3/pull/284 was that the next steps were to "the next step would be clean up w3_setup and probably move the variables comp_seq and comp_mpi from cmplr.env to wwatch3.env"  Is that part of this issue or is this issue closed and we need to make a new issue for the above?

**Comment by mickaelaccensi** [comment]
we can close it
