### ISSUE TITLE
Can not compile NetCDF enabled programs in ww3 v6.07

### ISSUE THREAD

**Issue by datpthus** [NOAA-EMC/WW3#192]
Dear all,

I can not compile NetCDF enabled programs (ww3_prnc, ww3_ounc...) on uni system for ww3 v6.07. I did export WWATCH3_NETCDF=NC4 and export NETCDF_CONFIG as guided and I also checked nc-config --has-nc4 and it says "yes". However, I always get the below errors:

Processing ww3_prnc
---------------------
ad3 : processing w3nmlprncmd 
mv: cannot stat `w3nmlprncmd.o': No such file or directory
ad3 : processing ww3_prnc 
mv: cannot stat `ww3_prnc.o': No such file or directory
      Linking ww3_prnc
      *** file ww3_prnc.o not found ***
      *** file w3nmlprncmd.o not found ***
*** Missing object files ***
make: *** [/data/datpt/WW3/model/exe/ww3_prnc] Error 3

here is my wwatch3.env file:
#
# Environment variables for wavewatch III
# ---------------------------------------
#
 
WWATCH3_LPR      printer
WWATCH3_F90      gfortran
WWATCH3_CC       gcc
WWATCH3_DIR      /data/datpt/WW3/model
WWATCH3_TMP      /data/datpt/WW3/model/tmp
WWATCH3_SOURCE   yes
WWATCH3_LIST     yes

Does anyone know how to fix this issue? I am really appreciated if you can give me a hint because it has been a long time and I have not figured out yet. 

Many thanks.

Dat Pham

**Comment by ukmo-ccbunney** [comment]
Hello Dat Pham,

This question should really be raised on the **WAVEWATCH-III Model Users Discussion Mailing List**
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.discussion-group

Issues in this GitHub repository are primarily for reporting bugs or problems with WW3 from a code development perspective.

Requests for help with running or setting up the model should be directed to the above mailing list. That way, your question will gain a wider audience and other users may benefit from the replies.

Kind regards,
Chris.

P.S. with your particular problem, it would be worth inspecting any error files generated in your `/data/datpt/WW3/model/tmp` directory to see if that gives you any clues.

**Comment by datpthus** [comment]
Hello Chris, 
Sorry for this. I will ask other users in the mailing list. 
Thank you!

Dat Pham
