### ISSUE TITLE
NUOPC cap unstructured updates

### ISSUE THREAD

**Issue by awest-noaa** [NOAA-EMC/WW3#198]
Creating feature branch "nuopc_unstruc" to improve efficiency of NUOPC field exchanges on unstructured grids. Changes to be made to wmesmfmd.ftn.

To add a build command for ww3_bound in ESMF Makefile, to allow wave boundary conditions in nearshore NUOPC apps.

**Comment by aliabdolali** [comment]
@awest-noaa Could you give me an update on this issue?

**Comment by awest-noaa** [comment]
@aliabdolali Ali, this branch has become deprecated, since I will be adding my updates to the scalability branch instead, as we discussed. But the CA NEMS app still points to this branch at present, so please keep it alive for another 2 weeks. Once the NEMS app .gitmodules is updated and fully tested, we can remove this branch.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali did @awest-noaa updates for the wmesmf cap get reintegrated into the code with the rest of scalability?  We should make sure to not lose these updates even if current efforts are being put elsewhere.

**Comment by JessicaMeixner-NOAA** [comment]
There are NUOPC cap options in both wmesmf and in the mesh cap in the dev/ufs-weather-model.  If anyone feels that this issue should be reopened, please reopen it or create a new issue.
