### ISSUE TITLE
Optimisations for coupled modelling performance (OASIS)

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#207]
Enhancements to improve performance and MPI communications for coupled atmosphere-wave-ocean modelling. Changes based on Met Office work using a UM-WWIII-NEMO modelling framework coupled via OASIS

**Comment by ukmo-juan-castillo** [comment]
It may be possible to include some performance modifications to the MPI calls and coupling infrastructure, following the lines of similar changes to the WWIII vn4.18 code branch for coupled configurations used at the Met Office. These changes include the removal of unnecessary MPI calls, reorganization of loops, and change the 'block' by the 'points' coupling decompositon. It is unkown the impact these changes will have in terms of model performance, but each change will be assessed independently and accepted only if it improves model performance, even if only by a small amount.

**Comment by ukmo-ansaulter** [comment]
@ukmo-juan-castillo will be the main developer for these changes

**Comment by ukmo-juan-castillo** [comment]
I have not finished working on this ticket yet. I was waiting until having other issues solved first, and I believe the last staging branch will contain everything we need to start.

**Comment by JessicaMeixner-NOAA** [comment]
Can this issue now be closed @ukmo-juan-castillo @ukmo-ccbunney ?

**Comment by ukmo-juan-castillo** [comment]
I still want to add some optimizations in the coupling code, but I did not have time yet to do so. I guess we can close this issue and I can open new issues for each of the changes I was planning, if you prefer this approach.

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-juan-castillo I'm going to close this issue then and look forward to your new issues when you're ready to return to this work!
