### ISSUE TITLE
Error checking of SMC grid input files in ww3_grid

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#208]
The `ww3_grid` program would benefit from some error checking of the SMC input files (cell and i/j side inputs) to ensure all cells are bound by the underlying regular grid.

**Background**
Recent experience has highlighted that an erroneous cell location outside the defined model domain can be successfully read in to `ww3_grid`. The calculated `IX/IY` indices results in an out-of-bounds array write causing (silent) corruption of surrounding arrays. This later causes a model crash when running `ww3_shel`

**Example**
An incorrect IX value in the `ww3Cels.inp` file that is outside of the underlying regular grid longitude range results in an out-of-bounds array access at lines 4419 - 4421 which corrupts the data in the `MAPSF` array.

https://github.com/NOAA-EMC/WW3/blob/3085d9f146cf5150ec11fe2a6cddce5fa8fa180c/model/ftn/ww3_grid.ftn#L4419-L4424

A basic check would be to ensure that the calculated IX/IY values at line 4411/4412 are within the range [1,NX] and [1,NY] respectively:
https://github.com/NOAA-EMC/WW3/blob/3085d9f146cf5150ec11fe2a6cddce5fa8fa180c/model/ftn/ww3_grid.ftn#L4411-L4412

**Comment by UKMO-lsampson** [comment]
As suggested by Andy Saulter and Chris Bunney I will be looking into this issue.

**Comment by ukmo-ccbunney** [comment]
Fixed in https://github.com/ukmo-waves/WW3/pull/6
