### ISSUE TITLE
Enable model to run based on a climate simulation 360 day calendar

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#209]
Add an input namelist option to switch between 365 day + leap year, and 360 day calendars

**Comment by ukmo-juan-castillo** [comment]
I will be in charge of implementing the changes.

**Comment by ukmo-ansaulter** [comment]
Thanks @ukmo-juan-castillo 

Anticipating that changes will be provided to (at least):

- w3timemd.ftn
- ww3_grid.ftn
- ww3_ounf.ftn

For ww3_ounf we will need to ensure that the time metadata will be updated in compliance with CF conventions, see http://cfconventions.org/cf-conventions/cf-conventions.html#calendar

We also need to consider whether adding the 360 day calendar is in scope for the grib conversion software and point spectral formats

**Comment by ukmo-juan-castillo** [comment]
This change will be implemented in the branch fb_360_calendar. A new flag in the RUN_NML namelist called F360CAL will be used to decide if the 360-day calendar is to be used or not.

**Comment by ukmo-juan-castillo** [comment]
It was decided that the flag indicating the 360-day calendar will be moved to the MISC namelist for ww3_grid, at the same location where the NOLEAP flag is placed. There will be a check to avoid setting the NOLEAP and the new CAL360 flags to .TRUE. at the same time, as they determine different calendars (365-day without leap year, and 360-day respectively)

**Comment by ukmo-juan-castillo** [comment]
A new regtest has been included in ww3_ts1 to check that the new 360-day calendar is behaving as expected.

**Comment by ukmo-juan-castillo** [comment]
This enhancement has already been successfully implemented, tested, and merged in the staging branch of the ukmo-waves repository.
