### ISSUE TITLE
Transferring branches Vlab-> github

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#21]
After the successful transition of the master and develop branches from NOAA VLab to GitHub, a few branches need to be cleaned up or transferred across to forks or institutional repos.

**Comment by ajhenrique** [comment]
@mickaelaccensi will check at Ifremer if any branches left that need deletion.
@aliabdolali will check with @thesser1 to figure out what has been ported or restarted from scratch (then delete branches on vlab).
@aliabdolali and @JessicaMeixner-NOAA have a who/where shared spreadsheet with branches that need to be transferred.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali I assume we've done this or don't need to do this anymore at this point, so am closing this issue.
