### ISSUE TITLE
run ww3_shel makes corrupted size vs. prev_size error

### ISSUE THREAD

**Issue by DiegoGutierrez2210** [NOAA-EMC/WW3#220]
Hi everyone

I need help with this segmentation error after run ww3_shel:

corrupted size vs. prev_size: 0x0000559f7f821690 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7ff4a7491bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7ff4a7497fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x773b8)[0x7ff4a74983b8]
/lib/x86_64-linux-gnu/libc.so.6(+0x77ed8)[0x7ff4a7498ed8]
/home/matlab/WW3/exe_aysen/ww3_shel(+0x46a5c)[0x559f7e5b1a5c]
/home/matlab/WW3/exe_aysen/ww3_shel(+0xdfb5)[0x559f7e578fb5]
/home/matlab/WW3/exe_aysen/ww3_shel(+0x6749)[0x559f7e571749]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7ff4a74412e1]
/home/matlab/WW3/exe_aysen/ww3_shel(+0x677a)[0x559f7e57177a]
======= Memory map: ========
559f7e56b000-559f7e685000 r-xp 00000000 103:03 4769403                   /home/matlab/WW3/exe_aysen/ww3_shel
559f7e884000-559f7e887000 r--p 00119000 103:03 4769403                   /home/matlab/WW3/exe_aysen/ww3_shel
559f7e887000-559f7e888000 rw-p 0011c000 103:03 4769403                   /home/matlab/WW3/exe_aysen/ww3_shel
559f7e888000-559f7e8a5000 rw-p 00000000 00:00 0 
559f7f80b000-559f81a48000 rw-p 00000000 00:00 0                          [heap]
7ff484000000-7ff484021000 rw-p 00000000 00:00 0 
7ff484021000-7ff488000000 ---p 00000000 00:00 0 
7ff489efa000-7ff4a721d000 rw-p 00000000 00:00 0 
7ff4a721d000-7ff4a7220000 r-xp 00000000 103:01 525070                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ff4a7220000-7ff4a741f000 ---p 00003000 103:01 525070                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ff4a741f000-7ff4a7420000 r--p 00002000 103:01 525070                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ff4a7420000-7ff4a7421000 rw-p 00003000 103:01 525070                    /lib/x86_64-linux-gnu/libdl-2.24.so
7ff4a7421000-7ff4a75b6000 r-xp 00000000 103:01 525065                    /lib/x86_64-linux-gnu/libc-2.24.so
7ff4a75b6000-7ff4a77b6000 ---p 00195000 103:01 525065                    /lib/x86_64-linux-gnu/libc-2.24.so
7ff4a77b6000-7ff4a77ba000 r--p 00195000 103:01 525065                    /lib/x86_64-linux-gnu/libc-2.24.so
7ff4a77ba000-7ff4a77bc000 rw-p 00199000 103:01 525065                    /lib/x86_64-linux-gnu/libc-2.24.so
7ff4a77bc000-7ff4a77c0000 rw-p 00000000 00:00 0 
7ff4a77c0000-7ff4a77d8000 r-xp 00000000 103:01 525082                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ff4a77d8000-7ff4a79d7000 ---p 00018000 103:01 525082                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ff4a79d7000-7ff4a79d8000 r--p 00017000 103:01 525082                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ff4a79d8000-7ff4a79d9000 rw-p 00018000 103:01 525082                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7ff4a79d9000-7ff4a79dd000 rw-p 00000000 00:00 0 
7ff4a79dd000-7ff4a7a1b000 r-xp 00000000 103:04 131336                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7ff4a7a1b000-7ff4a7c1a000 ---p 0003e000 103:04 131336                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7ff4a7c1a000-7ff4a7c1b000 r--p 0003d000 103:04 131336                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7ff4a7c1b000-7ff4a7c1c000 rw-p 0003e000 103:04 131336                    /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7ff4a7c1c000-7ff4a7c32000 r-xp 00000000 103:01 524394                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff4a7c32000-7ff4a7e31000 ---p 00016000 103:01 524394                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff4a7e31000-7ff4a7e32000 r--p 00015000 103:01 524394                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff4a7e32000-7ff4a7e33000 rw-p 00016000 103:01 524394                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7ff4a7e33000-7ff4a7e5f000 r-xp 00000000 103:04 132438                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7ff4a7e5f000-7ff4a805e000 ---p 0002c000 103:04 132438                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7ff4a805e000-7ff4a805f000 r--p 0002b000 103:04 132438                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7ff4a805f000-7ff4a8060000 rw-p 0002c000 103:04 132438                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7ff4a8060000-7ff4a8163000 r-xp 00000000 103:01 525071                    /lib/x86_64-linux-gnu/libm-2.24.so
7ff4a8163000-7ff4a8362000 ---p 00103000 103:01 525071                    /lib/x86_64-linux-gnu/libm-2.24.so
7ff4a8362000-7ff4a8363000 r--p 00102000 103:01 525071                    /lib/x86_64-linux-gnu/libm-2.24.so
7ff4a8363000-7ff4a8364000 rw-p 00103000 103:01 525071                    /lib/x86_64-linux-gnu/libm-2.24.so
7ff4a8364000-7ff4a8488000 r-xp 00000000 103:04 132463                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7ff4a8488000-7ff4a8687000 ---p 00124000 103:04 132463                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7ff4a8687000-7ff4a8688000 r--p 00123000 103:04 132463                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7ff4a8688000-7ff4a868a000 rw-p 00124000 103:04 132463                    /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7ff4a868a000-7ff4a86ad000 r-xp 00000000 103:01 525001                    /lib/x86_64-linux-gnu/ld-2.24.so
7ff4a86b0000-7ff4a882c000 rw-p 00000000 00:00 0 
7ff4a888b000-7ff4a888f000 rw-p 00000000 00:00 0 
7ff4a88a9000-7ff4a88ad000 rw-p 00000000 00:00 0 
7ff4a88ad000-7ff4a88ae000 r--p 00023000 103:01 525001                    /lib/x86_64-linux-gnu/ld-2.24.so
7ff4a88ae000-7ff4a88af000 rw-p 00024000 103:01 525001                    /lib/x86_64-linux-gnu/ld-2.24.so
7ff4a88af000-7ff4a88b0000 rw-p 00000000 00:00 0 
7ffcc1982000-7ffcc19a3000 rw-p 00000000 00:00 0                          [stack]
7ffcc19d2000-7ffcc19d4000 r--p 00000000 00:00 0                          [vvar]
7ffcc19d4000-7ffcc19d6000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7ff4a837fd1d in ???
#1  0x7ff4a837ef7d in ???
#2  0x7ff4a745405f in ???
#3  0x7ff4a7453fff in ???
#4  0x7ff4a7455429 in ???
#5  0x7ff4a7491bff in ???
#6  0x7ff4a7497fc5 in ???
#7  0x7ff4a74983b7 in ???
#8  0x7ff4a7498ed7 in ???
#9  0x559f7e5b1a5b in __w3initmd_MOD_w3init
	at /home/matlab/WW3/tmp/w3initmd.F90:749
#10  0x559f7e578fb4 in w3shel
	at /home/matlab/WW3/tmp/ww3_shel.F90:795
#11  0x559f7e571748 in main
	at /home/matlab/WW3/tmp/ww3_shel.F90:229
-- -- -- -- -- -- -- -- --
SWITCH: F90 NOGRB NOPA LRB4 SHRD OMPG OMPX NC4 PRE UNO FLX2 LN1 ST2 STAB2 NL1 BT1 DB1 MLIM TR1 BS0 IC0 REF1 XX0 WNT1 WNX1 CRT1 CRX1 IS0 TIDE O0 O1 O2 O3 O4 O5 O6 O7 O10 O11 O14

Linux version: 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian

kernel version:
4.9.0-5-amd64

I appreciate the help provided to solve this error

Atte Diego

**Comment by aliabdolali** [comment]
Hi @DiegoGutierrez2210 
your issue is not exactly a code development issue and is not clearly explained, it is more like a user needing help with a problem in executing the code. Please refer to the user forum to get help with such issues and note that this section of our GitHub repository is reserved for issues that require bugfixing in the code, or new features that are being planned/suggested to be added to the WAVEWATCH III package. Please send questions like this to our user forum/listserv at:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users
