### ISSUE TITLE
Adding latitude, longitude information and time dimension

### ISSUE THREAD

**Issue by strandwg** [NOAA-EMC/WW3#221]
CESM2 has had WW3 active for some of our more recent runs, and I've noticed that the output files are lacking the necessary coordinates for latitudes and longitudes, and are entirely lacking any time information.

Can these be added in a future version? Thanks!

**Comment by aliabdolali** [comment]
Hi @strandwg 
The NetCDF outputs, including point and field outputs, include longitude, latitude, and time. What kind of outputs you are referring to?
AA

**Comment by strandwg** [comment]
The output that WW3 writes in netCDF format. CESM2 gets files called

runname.ww3.hi.1850-01-01-00000.nc

That are very small (~90 kB) and contain only

dimensions:
        NX = 90 ;
        NY = 50 ;
        NOSWLL = 3 ;
variables:
        float UAX(NY, NX) ;
                UAX:_FillValue = 1.e+30f ;
                UAX:units = "m/s" ;
                UAX:long_name = "Mean wind, x-component" ;
        float UAY(NY, NX) ;
                UAY:_FillValue = 1.e+30f ;
                UAY:units = "m/s" ;
                UAY:long_name = "Mean wind, y-component" ;
        float HS(NY, NX) ;
                HS:_FillValue = 1.e+30f ;
                HS:units = "m" ;
                HS:long_name = "Significant wave height" ;
        float TMN(NY, NX) ;
                TMN:_FillValue = 1.e+30f ;
                TMN:units = "s" ;
                TMN:long_name = "Mean wave period" ;
        float THM(NY, NX) ;
                THM:_FillValue = 1.e+30f ;
                THM:units = "rad" ;
                THM:long_name = "Mean wave direction" ;
}

**Comment by aliabdolali** [comment]
@strandwg 
What is your grid? and could you share your ww3_ounf.inp with me?

**Comment by mickaelaccensi** [comment]
@strandwg 
Are you sure this output comes from WW3 ? We don't have this kind of dimensions neither variable names.

**Comment by strandwg** [comment]
Apologies for the post; there were some internal miscommunication. I consider the issue closed.
