### ISSUE TITLE
Grid integration of partitioned data does not conserve energy

### ISSUE THREAD

**Issue by SanderHulst** [NOAA-EMC/WW3#227]
### Description
We reconstruct 2D spectra from the partitioned data so it is important that the energy in the partitions adds up to the energy in the original spectrum.

We run a global 30 minute grid with seven 6 minute regional grids as a multigrid. In order to make life a bit more easy for data consumers we unify the field output into one global 6 minute grid. 

![wavewatch_global_6min_st4_gfs_fields_20200707_1200](https://user-images.githubusercontent.com/37443533/86839792-2bc83f00-c0a2-11ea-8bd8-d43f4230f33f.png)
The figure above shows the overall significant waveheight on the top pane and the root of the sum of the squared significant waveheights of six partitions. It shows lines of unrealistic, increased waveheight in the roaring forties. On this time particularly South of Australia. The hypothesis is that it is caused by "bleeding" of the energy as a result of linear interpolation between a zero energy gridpoint (partition not there) and a non-zero gridpoint (partition there). This added energy is artificial. Bleeding would be prevented by using a nearest neighbor interpolation.

After adding nearest neighbor interpolation to ww3_gint.ftn, the lines of spurious energy dissappear as shown in the figure below.
![wavewatch_global_6min_st4_gfs_fields_20200707_0600_nearest](https://user-images.githubusercontent.com/37443533/86841004-ae9dc980-c0a3-11ea-814c-f796287db239.png)

### Affected regression tests
Perhaps we can reproduce and test for in mww3_case03. First check that overall Hs and partitions do not agree. Then redo with nearest.

### Notes
Some energy is always lost as only the first 6 partitions are outputted and the rest discarded. This effect can be noticable in the Pacific. But this is another story.

**Comment by SanderHulst** [comment]
Edit: removed figure which was created with an old executable. Everything works just fine as can be seen in figure below
![wavewatch_global_6min_st4_gfs_fields_20200710_1200](https://user-images.githubusercontent.com/37443533/87066831-7ddca200-c213-11ea-8aea-e3a792d3fe73.png)

**Comment by aliabdolali** [comment]
Hi @SanderHulst 
This is a great demonstration of the problem and solution. I am going to merge the development into your feature branch and run our full regtest cases. Do you need any change before I do it? Then I will share the list of non- identical cases for your review.
Regards
AA

**Comment by SanderHulst** [comment]
No, no changes required. We reimplemented the grid unification in python but still use nearest for partition parameters.
