### ISSUE TITLE
Bugfix homogeneous ice condition in ww3_shel

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#235]
When switched to use homogeneous fields, ww3_shel presently attempts to read in wind data, where it should be reading in an ice concentration. The lines needing to be changed are as follows:

! ICE : ice conc.
            ELSE IF ( J .EQ. 4 ) THEN
              IF ( FLH(J) ) THEN
                CALL W3FLDH (J, NDST, NDSEN, NX, NY, NX, NY,    &
                             TIME0, TIMEN, NH(J), NHMAX, THO, HA, HD, HS,&
                             TW0, WX0, WY0, DT0, TWN, WXN, WYN, DTN, IERR)

should be changed to:

! ICE : ice conc.
            ELSE IF ( J .EQ. 4 ) THEN
              IF ( FLH(J) ) THEN
                CALL W3FLDH (J, NDST, NDSEN, NX, NY, NX, NY,    &
                             TIME0, TIMEN, NH(J), NHMAX, THO, HA, HD, HS,&
                             TTT, XXX, XXX, XXX, TIN, XXX, BERGI, ICEI, IERR)

**Comment by ukmo-ccbunney** [comment]
Fixed in #285
