### ISSUE TITLE
Faulty oasis coupling condition

### ISSUE THREAD

**Issue by ukmo-juan-castillo** [NOAA-EMC/WW3#238]
One of the conditions that determine if in a particular time step oasis coupling is to be performed or not is problematic. While the present code works using the GNU compiler, when using for example the Cray compiler this condition is only met at the first time step, and therefore the model does not advance in time and falls in an infinite loop. We believe this happens due to the precision of operations in different compilers, and the different behaviour of the MOD function when using real numbers as parameters. The problematic condition can be simplified so that it can be easier to understand, and to make it work in any compiler.

**Comment by ukmo-juan-castillo** [comment]
https://github.com/NOAA-EMC/WW3/blob/10208f1b430a484458c2ee1c670b573bece8d3e9/model/ftn/ww3_shel.ftn#L1910-L1912

The problematic condition is the second one.

**Comment by aliabdolali** [comment]
@ukmo-ccbunney can we close it?

**Comment by ukmo-ccbunney** [comment]
@aliabdolali Yes! :)

**Comment by aliabdolali** [comment]
@ukmo-ccbunney Thanks
