### ISSUE TITLE
Add-in functions + instrumenting for model optimization

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#24]
Andy Saulter with @ukmo-ccbunney will work to add these enhancements.

**Comment by ukmo-ccbunney** [comment]
I am thinking that this issue can probably be closed. The UKMO did look at instrumentation of the WW3 code with DrHook calls, but I think there are probably better and more comprehensive solutions available from compiler vendors. For instance, there is a project currently underway at the UKMO to investigate the acceleration of WW3 using GPU and openACC. The diagnostics provided (automatically) by the nVidia profiler are significantly more useful than the DrHook diagnostics. I think focussing on the use of compiler vendor provided profiling tools is likely a better route.
