### ISSUE TITLE
file ww3_trnc.o not found [develop branch]

### ISSUE THREAD

**Issue by knutaros** [NOAA-EMC/WW3#245]
This happens with and without TRKNC defined. Other active switches are NC4 and F90 DIST MPI.

Processing ww3_trnc
---------------------
ad3 : processing w3nmltrncmd 
ad3 : processing ww3_trnc 
mv: cannot stat 'ww3_trnc.o': No such file or directory
      Linking ww3_trnc
      *** file ww3_trnc.o not found ***
*** Missing object files ***
makefile:326: recipe for target '/media/work/tools/ww3/code/model/exe/ww3_trnc' failed

**Comment by knutaros** [comment]
/media/work/tools/ww3/code/model/tmp_MPI$ cat ww3_trnc.err 
ww3_trnc.F90:795:9:

       END CASE
         1
Error: Expecting END SELECT statement at (1)
ww3_trnc.F90:1051:9:

       END SUBROUTINE W3CRNC
         1
Error: Expecting END SELECT statement at (1)
ww3_trnc.F90:1055:6:

       SUBROUTINE CHECK_ERR(IRET)
      1
Error: Unclassifiable statement at (1)
ww3_trnc.F90:1057:16:

       USE NETCDF
                1
Error: Unexpected USE statement at (1)
ww3_trnc.F90:1058:30:

       USE W3ODATMD, ONLY: NDSE
                              1
Error: Unexpected USE statement at (1)
ww3_trnc.F90:1059:32:

       USE W3SERVMD, ONLY: EXTCDE
                                1
Error: Unexpected USE statement at (1)
ww3_trnc.F90:1061:19:

       IMPLICIT NONE
                   1
Error: Duplicate IMPLICIT NONE statement at (1)
ww3_trnc.F90:1063:18:

       INTEGER IRET
                  1
Error: Symbol ‘iret’ at (1) already has basic type of INTEGER
ww3_trnc.F90:1073:9:

       END SUBROUTINE CHECK_ERR
         1
Error: Expecting END SELECT statement at (1)
ww3_trnc.F90:1081:9:

       END PROGRAM W3TRNC
         1
Error: Expecting END SELECT statement at (1)
f951: Error: Unexpected end of file in ‘ww3_trnc.F90’

**Comment by aliabdolali** [comment]
Hi @knutaros  your issue is not exactly a code development issue and is not clearly explained, it is more like a user needing help with a problem for an application. Please refer to the user forum to get help with such issues and note that this section of our GitHub repository is reserved for issues that require bugfixing in the code, or new features that are being planned/suggested to be added to the WAVEWATCH III package. Please send questions like this to our user forum/listserv at:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users

**Comment by mickaelaccensi** [comment]
Hi @knutaros and @aliabdolali, actually this is a bug introduced with the last PR from UKMO
 ukmo-waves#8: 360 day climate calendar

in ww3_trnc.ftn
END CASE
should be replaced by
 END SELECT

I've done a PR

**Comment by ukmo-ccbunney** [comment]
Thanks @mickaelaccensi .
Odd how this didn't get picked up in the regtests.

Edit: Ah - actually, the only regtest that has an input file for `ww3_trnc` is `ww3_tp2.2`, and this is set to **not** run netCDF output programs (no `-o` switch), so it never gets compiled. This is why the bug never got picked up in the regtests.

Perhaps we should add a `-o both` switch to one of the tp2.2 regtests so ww3_trnc gets tested in the regtest matrix?

**Comment by knutaros** [comment]
Dear Mickael,

thanks a lot for re-opening this issue. With the changes from your PR
the compilation is fine.

Cheers, Knut

**Comment by aliabdolali** [comment]
@mickaelaccensi can we close it?
