### ISSUE TITLE
bug in wmesmfmd

### ISSUE THREAD

**Issue by knutaros** [NOAA-EMC/WW3#247]
commit: 49157a4
file: wmesmfmd.ftn 
subroutine: GetImport()

There is no endif for the "if (firstCall) then" from line 2283.
https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/wmesmfmd.ftn#L2283

I assume, the WRST switch from line 2305 should be removed?
https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/wmesmfmd.ftn#L2305

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @knutaros I'll admit I haven't tested wmesmf without WRST.  So I don't this bug was introduced with the latest PR for commit 49157a4, but has likely been an issue for a while.  I think you're correct in your assumption about the WRST switch needing to be removed for line 2305.

**Comment by JessicaMeixner-NOAA** [comment]
@knutaros the fix is in the develop branch.  I'm closing this issue.  Please reopen if this did not solve the issue.
