### ISSUE TITLE
ST4 b4b reproduciblity issue

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#249]
As of commit 77f9291 I have been having issues with bit-for-bit reproducibility of the `out_grd.ww3` file in some of the `ST4` based regtests.

For instance, `ww3_ts1/work_ST4` regtest and all of the `ww3_ta1` regtests are not b4b comparable.

A test of develop at commit 19f3126 shows that these regtests were B4B at this revision.

This is the case both on our Cray HPC and my linux desktop.

**Comment by aliabdolali** [comment]
@ukmo-ccbunney is it solved? can we close it?

**Comment by ukmo-ccbunney** [comment]
> 
> 
> @ukmo-ccbunney is it solved? can we close it?

@aliabdolali - no, this is still an open issue. I think that @mickaelaccensi was going to see if he could reproduce it.

**Comment by mickaelaccensi** [comment]
I'm able to reproduce the b4b problem on regtest ww3_ts1 with ST4 by comparing results between debug and optimized compilation options. The problem comes from the variable wcf. I'll dig into the code to find where the bug is

**Comment by aliabdolali** [comment]
@mickaelaccensi please close it if it is addressed in your last PR.
