### ISSUE TITLE
'ww3_ounf' segmentation fault occurred for global model

### ISSUE THREAD

**Issue by GM-Ling** [NOAA-EMC/WW3#251]
When I tried to convert result to netcdf file using 'ww3_ounf', I got the following error messages:
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
ww3_ounf           000000000062FE3D  for__signal_handl     Unknown  Unknown
libpthread-2.17.s  00007F5A659E1630  Unknown               Unknown  Unknown
ww3_ounf           0000000000587940  Unknown               Unknown  Unknown
ww3_ounf           000000000040BF33  Unknown               Unknown  Unknown
ww3_ounf           000000000040BD8E  Unknown               Unknown  Unknown
libc-2.17.so       00007F5A65626555  __libc_start_main     Unknown  Unknown
ww3_ounf           000000000040BCA9  Unknown               Unknown  Unknown
Just wondering anyone knows about this issue? 
Do I need any special setting in 'ww3_ounf.inp' when doing global model?

**Comment by aliabdolali** [comment]
Hi @GM-Ling 
Have you checked if the ITYPE and the grid size (IX, IY range) are defined correctly in ww3_ounf.inp?
i.e. 
$ ITYPE = 4, Netcdf Files
$            S3: number of characters in date
$            IX, IY range
$
ww3.
4
 1 360 1 180 3 2
AA

**Comment by GM-Ling** [comment]
Hi Ali,

Thank you so much for replying.
I have a global grid as following,
       Number of longitudes      :      1440
       Number of latitudes       :       721
So I defined ww3_ounf.inp as follow,
$ WAVEWATCH III - Output fields netcdf
$
  20111022 000000 7200 360
$
  N
$
  HS SXY
$
    4 4
    0 1 2
    T
$
ww3.
 4
 1 1440 1 721 1
Is anything wrong with it?

**Comment by aliabdolali** [comment]
@GM-Ling It looks ok to me. You might have a memory issue. Are you executing it on a HPC? on login node or compute node? Usually, the compute nodes have larger memory, so try to submit a job and allocate one compute core.

**Comment by GM-Ling** [comment]
> @GM-Ling It looks ok to me. You might have a memory issue. Are you executing it on a HPC? on login node or compute node? Usually, the compute nodes have larger memory, so try to submit a job and allocate one compute core.
Awesome! The suggestion solved my problem. I really appreciate it!

**Comment by aliabdolali** [comment]
@GM-Ling I am glad to hear it, WW3 always works :)>
