### ISSUE TITLE
Update input definitions for ww3_uprstr modules

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#255]
This enhancement is a minor technical change to improve the way in which input data is read in and logged by the ww3_uprstr program.

The changes should:

- read in variables specific to the update process selected
- output the values provided in the ww3_uprstr.out log file
- update the .inp template file and regtests to improve clarity and work with the changes
- add capability to read inputs from a namelist (ww3_uprstr.nml) file

**Comment by ukmo-ansaulter** [comment]
@mickaelaccensi , I'm doing this work in preparation for the enhancement you are making with the use of .nml files for all modules/regtests. The work won't take long, will this time in with you OK?

There is an option for me to try and code the namelist input for ww3_uprstr up if that would be helpful? At the moment I have concentrated on .inp as there is no namelist option currently

**Comment by ukmo-ansaulter** [comment]
Completed initial regtests on the updated code/input files. These will write a more verbose output to ww3_uprstr.out and have also bugfixed incorrectly set cap values in tests UPD2_U_CAP and UPD3_U_CAP

As a result, new regtest outputs will be revised compared to previous branches; as per the summary below (NB the critical unchanged files for the regtest are the restart files in all tests except UPD2_U_CAP and UPD_3_CAP; the changed out_grd.ww3 is a known issue and does not affect these tests for ww3_uprstr.ftn):

 
       ******************************************************
     ***  compare WAVEWATCH III matrix of regression tests  ***
       ******************************************************
 
base directory : /home/d01/frxs/Git_WW3/working/WW3/regtests
comp directory : /home/d02/frey/WW3/REGTESTS_GNU/regtests_96e3f3a_20200923
test(s)        : 
ww3_ta1
 
 
**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
ww3_ta1/./work_UPD0F_O                     (2 files differ)
ww3_ta1/./work_UPD5_U                     (2 files differ)
ww3_ta1/./work_UPD3_U                     (2 files differ)
ww3_ta1/./work_UPD3_O                     (2 files differ)
ww3_ta1/./work_UPD2_O                     (2 files differ)
ww3_ta1/./work_UPD0F_U                     (2 files differ)
ww3_ta1/./work_UPD5_O                     (2 files differ)
ww3_ta1/./work_UPD2_U_cap                     (3 files differ)
ww3_ta1/./work_UPD5_U_cap                     (2 files differ)
ww3_ta1/./work_UPD6_U_cap                     (2 files differ)
ww3_ta1/./work_UPD3_U_cap                     (3 files differ)
ww3_ta1/./work_UPD6_U                     (2 files differ)
ww3_ta1/./work_UPD2_U                     (2 files differ)
ww3_ta1/./work_UPD6_O                     (2 files differ)
 
**********************************************************************
************************ identical cases *****************************
**********************************************************************
 
**********************************************************************
******************** summary of comparison ***************************
********** only results of non-identical cases are listed ************
****** if less than 10 files differ for a case, they are listed ******
**********************************************************************

* test case: ww3_ta1; test run: ./work_UPD0F_O
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD5_U
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD3_U
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD3_O
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD2_O
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD0F_U
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD5_O
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD2_U_cap
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  10 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  3 files differ
ww3_uprstr.out restart001.ww3 (binary) out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD5_U_cap
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD6_U_cap
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD3_U_cap
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  10 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  3 files differ
ww3_uprstr.out restart001.ww3 (binary) out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD6_U
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD2_U
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

* test case: ww3_ta1; test run: ./work_UPD6_O
*********************************************************
  found 15 files in base directory
  found 15 files in compare directory
  11 files are identical
  2 files skipped
  0 files in base directory only
  0 files in comp directory only
  2 files differ
ww3_uprstr.out out_grd.ww3 (binary)

**Comment by mickaelaccensi** [comment]
I can give you some help on namelist if needed. Just add me on your development branch

**Comment by ukmo-ansaulter** [comment]
Thanks @mickaelaccensi . I think I'm almost there, so will add you as a reviewer for the PR :-)

**Comment by ukmo-ansaulter** [comment]
Updates now have the namelist option available and this has been used in 5 regtests:

- ww3_ta1/./work_UPD0F_O                     (3 files differ)
- ww3_ta1/./work_UPD5_U                     (3 files differ)
- ww3_ta1/./work_UPD2_U                     (3 files differ)
- ww3_ta1/./work_UPD6_O                     (3 files differ)
- ww3_ta1/./work_UPD3_U_cap                     (4 files differ)

The differences in the regtests are an expected outcome of the changes. Details of the differences are attached.

[matrixDiff.out.TXT](https://github.com/NOAA-EMC/WW3/files/5332213/matrixDiff.out.TXT)
