### ISSUE TITLE
comparison between ver.4.18 and ver.6.07.1

### ISSUE THREAD

**Issue by mincrt** [NOAA-EMC/WW3#265]
Recently, I am trying to apply the latest version of WW3. 
Before that, we have a test to verify the reproducibility between ver.4.18 and ver.6.07.1.
![results](https://user-images.githubusercontent.com/53882905/98338638-d0a55980-204d-11eb-9fdc-e2b973ce25ea.png)

This is the comparison result of significant wave height by using ver.4.18 and ver.6.07.1.  significant wave height. They are slightly different during forecasting lead time, especially, around the boundary. The difference range is approximately 50cm ~ 1m. 
Both versions are ST4 physical package, and almost parameters are the same settings.

I would like to know why the differences may caused by WW3 versions, if the differences is caused by the model versions what kind of source file affect the result. 

Thank you for your time.

**Comment by JessicaMeixner-NOAA** [comment]
There's probably been a significant amount of changes and minor bug fixes for sure, but if you are getting 1m differences, I'd be curious what the parameter differences you do have since you say they are almost the same? I wonder if the difference is important?    The manual about sections for versions 5.16 and 6.0.7 both list the major updates that came with each release.

**Comment by aliabdolali** [comment]
In addition to Jessica's points, some fixes were done to improve physics. So, even if you see ~1 m difference, you should compare with observations (satellite/buoy) to see the model performance.

**Comment by mincrt** [comment]
Thank you very much for your comments. 
In my test case, I found that the different physical parameters used to create the nesting file before the main simulation.  It fixed and simulated again for the same condition. The simulation result was considerably improved and the differences between the models has decreased slightly. In the future, I will confirm the model performance, compared to using buoy and satellite date. 
Also, I will check first versions 5.16 and 6.0.7 manual.  
Thank you very much for your time.
