### ISSUE TITLE
Isolation of Wind Waves Data

### ISSUE THREAD

**Issue by irfanafi** [NOAA-EMC/WW3#268]
Good afternoon,

I am currently working on extraction of values from the NOAA database for my school project. When I have successfully extracted for a particular date or a range of dates, there is a particular output that interest me: Significant_height_of_combined_wind_waves_and_swell_surface.

I would like to isolate or calculate the values of Wind Waves only instead of the combine values of wind waves and swell surfaces. Is there a formula that was used to arrive this output value? I have tried searching in the manual but I was not able to find anything. Any help would be great.

Thank you.

![Screenshot 2020-11-26 at 2 46 38 PM](https://user-images.githubusercontent.com/75062121/100316824-3c983380-2ff6-11eb-80f9-efabd84bec6f.png)

**Comment by aliabdolali** [comment]
In the model the "significant wave height of combined seas/swell" value is calculated for every wet grid point and the spectral partition algorithm used in WW3 is described in:
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.594.4263&rep=rep1&type=pdf

**Comment by aliabdolali** [comment]
@irfanafi does it answer your question? can we close this issue?

**Comment by MatthewMasarik-NOAA** [comment]
Closing as @aliabdolali provided a reference for the question, and no posts since.  @irfanafi, if this issue has not been resolved, please feel free to re-open it.
