### ISSUE TITLE
OASIS - UNST

### ISSUE THREAD

**Issue by papez** [NOAA-EMC/WW3#269]
Hi all,
is anyone out there working on, or planning to, upgrade w3oacpmd.ftn for unstructured grids?
Just asking for a friend :)

Cheers,
P

**Comment by aliabdolali** [comment]
@mickaelaccensi could you help with it?

**Comment by aliabdolali** [comment]
@mickaelaccensi could you help with it? is there any plan for this?

**Comment by mickaelaccensi** [comment]
Hi Papez,

The OASIS coupling for unstructured grid is not planned for the coming months but it's definitely something to do and we may have some projects for 2021 on it, so I'll keep you updated. Papez, I close this issue but feel free to reopen it if you plan to work on it.

Mickael
