### ISSUE TITLE
Fix small bug on temp NCO switch fixed-file ounf option

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#27]
@ajhenrique has created a temporary fix to allow usage of ounf in NCEP's GLWU system. A more consistent solution for this problem will be provided under issue #23.

**Comment by ajhenrique** [comment]
@RobertoPadilla-NOAA this is the issue for the fixed file bugfix.

**Comment by ajhenrique** [comment]
This has been taken up within #23.

**Comment by juanliria** [comment]
The NCO switch for ww3_ounf contains a bug that overwrites the ww3.gridded.nc file on the turn of year.
so on a forecast that goes from the 26th of december 2020 to the 2nd of January 2021. ww3_ounf will write a ww3.gridded.nc file for 2020 and then overwrite the same file with the 2021 data, as a result there will be a single ww3.gridded.nc file containing data from 2021 and the 2020 data will be lost
