### ISSUE TITLE
ww3_ounf inconsistency?

### ISSUE THREAD

**Issue by papez** [NOAA-EMC/WW3#274]
Any particular reason for VMIN=0 for field 'water level' WLV?

Cheers
P

**Comment by ukmo-ccbunney** [comment]
@papez - You're right, the vmin/vmax should be symmetrical about zero for WLV (to handle cases where tidal inputs are referenced to mean sea level, or similar).

I am working on WW3_OUNF at the moment and will add a fix for this in the develop branch.

Thanks for raising this.

**Comment by papez** [comment]
Thank you @ukmo-ccbunney , i'm just too lazy to fork and push :D

You might also wish to set VMAX for Stokes transports. Looks like it is undefined within the ELSE IF block, thus picking up the value from the previous call.

**Comment by ukmo-ccbunney** [comment]
>  i'm just too lazy to fork and push

Fair enough!

> You might also wish to set VMAX for Stokes transports. Looks like it is undefined within the ELSE IF block, thus picking up the value from the previous call.

Yes - thanks for that. I've already spotted that one and it is marked TODO in my list of WW3_OUNF updates.
