### ISSUE TITLE
ww3_grib build on NOAA HPC (i.e. hera)

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#275]
The following should be added to model/bin/link.tmpl to add opt and libs required for ww3_grib compilation. After (_# netcdf library dir_) 

```
# NCEP grib creation
  if [ "$ncep_grib_compile" = 'yes' ]
  then
# GRIB libraries for this one
    opt="$opt -convert big_endian -assume byterecl -prec-div -prec-sqrt -ip"
    libs="$libs ${G2_LIB4} ${W3NCO_LIB4} ${BACIO_LIB4} ${JASPER_LIB} ${PNG_LIB} ${Z_LIB}"
  fi
```

**Comment by JessicaMeixner-NOAA** [comment]
Is this an issue with the hera modules themselves or an issue with the order of linking?   Since we can run with the current order on other platforms I was curious.  At first I thought we were just totally missing them, but they do seem to be there.  Also for other versions of the code and with different modules the code has run successfully on hera/orion before.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA Roberto reported that he had to use the link and comp from UFS/WW3 to generate compile ww3_grib on hera. When I compared the WW3/develop and the one Roberto referred to, I realized that the lines I mentioned are missing in link.tmpl.
`# NCEP grib creation
  if [ "$ncep_grib_compile" = 'yes' ]
  then
# GRIB libraries for this one
    opt="$opt -convert big_endian -assume byterecl -prec-div -prec-sqrt -ip"
    libs="$libs ${G2_LIB4} ${W3NCO_LIB4} ${BACIO_LIB4} ${JASPER_LIB} ${PNG_LIB} ${Z_LIB}"
  fi`
Also NCEP2 is not in model/esmf/switch, so even if we could be able to compile ww3_grib with that switch, it was not generating grib files. Once we add NCEP2, then the aformentioned lines are required.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA Roberto reported that he had to use the link and comp from UFS/WW3 to generate compile ww3_grib on hera. When I compared the WW3/develop and the one Roberto referred to, I realized that the lines I mentioned are missing in link.tmpl.
```
# NCEP grib creation
if [ "$ncep_grib_compile" = 'yes' ]
then
opt="$opt -convert big_endian -assume byterecl -prec-div -prec-sqrt -ip"
libs="$libs ${G2_LIB4} ${W3NCO_LIB4} ${BACIO_LIB4} ${JASPER_LIB} ${PNG_LIB} ${Z_LIB}"
fi
```
Also NCEP2 is not in model/esmf/switch, so even if we could be able to compile ww3_grib with that switch, it was not generating grib files. Once we add NCEP2, then the aformentioned lines are required.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali the NCEP2 switch is added to the switch file before compiling grib.  In the production/gfsv16 branch it's done via the makefile in the esmf directory: https://github.com/NOAA-EMC/WW3/blob/develop/model/esmf/Makefile#L187-L190 
and now that the pre-and post- processing exes for WW3 are not processed via the esmf makefile, the switch is added in the build script here: https://github.com/NOAA-EMC/global-workflow/blob/feature/coupled-crow/sorc/build_ww3prepost.sh#L78-L81 

The NCEP grib creation lines seem to be in the develop branch: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/bin/link.tmpl#L108-L112

They also seem to be in the WW3 version used for UFS prototype 5 (tag:  https://github.com/ufs-community/ufs-s2s-model/tree/s2s_prototype5.0 ) WW3 link: https://github.com/NOAA-EMC/WW3/blob/96e3f3a8fa0389a4b110b0fa23e7a414f6d92038/model/bin/link.tmpl#L107-L112

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA You are right, I might clone a different version of code. I checked it now on hera and orion and it looks ok.
