### ISSUE TITLE
puzzle about the calculation of roughness length z0 in the ST4 and ST2

### ISSUE THREAD

**Issue by Rachel201810** [NOAA-EMC/WW3#277]
HI,
Sorry to be a bother. I have a puzzle about the calculation principle of the roughness length z0 in the ST4 and ST2 source terms.  

I can see from the code that it is calculated directly from the logarithmic wind profile: 
![image](https://user-images.githubusercontent.com/55370370/101981247-6748e400-3ca6-11eb-8b03-679ae56182ec.png)
However, most of the studies use the Charnock relationship z0=Ch*u^2/g or its deformation to calculate z0. I wonder why it is not used here? Or is the Charnock relation implicit in the calculation of these source terms?

Appreciate your help.

Best regards!

**Comment by ukmo-ansaulter** [comment]
Hi, 

Both ST2 and ST4 describe a Charnock(-like) parameter in their z0 calculations; this is denoted as alpha in the relevant sections of the manual.

For ST2 this isn't described as a Charnock parameter directly, but uses a relationship between alpha and the inverse wave age (eq. 2.71)

In ST4, the reader is referred to ST3 (WAM Cycle 4 ECWAM) for a basis for the input source term Sin. In both ST3 and ST4 the Charnock parameter is calculated based on relationships in eq. 2.102-2.104.

Apologies if the manual wasn't particularly clear in this regard. If you have any helpful suggestions for how we might improve the text we'd be very happy to hear them.

Hope that helps
Andy

**Comment by Rachel201810** [comment]
> Hi,
> 
> Both ST2 and ST4 describe a Charnock(-like) parameter in their z0 calculations; this is denoted as alpha in the relevant sections of the manual.
> 
> For ST2 this isn't described as a Charnock parameter directly, but uses a relationship between alpha and the inverse wave age (eq. 2.71)
> 
> In ST4, the reader is referred to ST3 (WAM Cycle 4 ECWAM) for a basis for the input source term Sin. In both ST3 and ST4 the Charnock parameter is calculated based on relationships in eq. 2.102-2.104.
> 
> Apologies if the manual wasn't particularly clear in this regard. If you have any helpful suggestions for how we might improve the text we'd be very happy to hear them.
> 
> Hope that helps
> Andy

Thanks for your help, Andy!!!
