### ISSUE TITLE
Confusion about the Table 2.6 in the manual v5.16

### ISSUE THREAD

**Issue by Rachel201810** [NOAA-EMC/WW3#281]
HI,

Sorry to be a bother. I have a confusion about the Table 2.6 in the manual v5.16 on page 46.

The description of Table 2.6 says "TEST471 generally provides... TEST451f corresponds to a retuning for CSFR wind reanalysis from NCEP/NCAR...". But based on what's in the table should this be "TEST471f" instead of "TEST451f"?

Appreciate your help.

Best regards!

**Comment by thesser1** [comment]
@Rachel201810 yes, I believe you are correct.  The text has a typo.  @mickaelaccensi can you confirm that TEST471f is the CFSR tuned ST4 setup?

**Comment by Rachel201810** [comment]
> @Rachel201810 yes, I believe you are correct. The text has a typo. @mickaelaccensi can you confirm that TEST471f is the CFSR tuned ST4 setup?

Thanks for your help!
