### ISSUE TITLE
error while running ./model/bin/w3_setup model -c <comp> -s <switch>

### ISSUE THREAD

**Issue by RajeshKillampalli** [NOAA-EMC/WW3#282]
Hi, I'm Rajesh installing WW3 through Quick start WW3 after the (sh model/bin/ww3_from_ftp.sh) run all files are correctly resorted and while running the w3_setup (./model/bin/w3_setup model -c <comp> -s <switch> this error is showing in terminal (**-bash: syntax error near unexpected token `newline'**)
can any one help me how to fix this.

**Comment by thesser1** [comment]
@RajeshKillampalli w3_setup requires more input.   model = the absolute path to the model directory usually under the WW3 directory.  -c needs a compiler, for instance if running gnu, there are prebuilt compiler flags for gnu if you put gnu after -c.  -s is the switch file, the code comes with some examples of prebuilt switch files in the bin directory.   An example of this code setup running from the ~/WW3/model/bin directory:  "./w3_setup ~/WW3/model -c gnu -s NCEP_st4".      I hope this helps.

**Comment by RajeshKillampalli** [comment]
thank you sir, model path and this code is cleared installation model successfully  ~/WW3/model/bin directory: "./w3_setup ~/WW3/model -c gnu -s NCEP_st4". but can have any test cases regarding to test the model running successfully.

**Comment by thesser1** [comment]
@RajeshKillampalli

**Comment by thesser1** [comment]
@RajeshKillampalli I reopened this issue to answer your question.  The model has a number of regression tests that are described in the Developers guide at https://github.com/NOAA-EMC/WW3/wiki/Developer-Guide.  I hope this helps.
