### ISSUE TITLE
 How to calculate the peak wave length for the whole wave spectrum

### ISSUE THREAD

**Issue by Rachel201810** [NOAA-EMC/WW3#286]
HI,

Sorry to be a bother. I have a confusion about how to get the peak wave length for the whole wave spectrum. 

I found that only the peak wave length of partitions of the spectra is provided in the output data. I wonder if there is a way to calculate the peak wave length for the whole wave spectrum from the output peak frequency or other output variables?

Appreciate your help.

Best regards!

**Comment by CarstenHansen** [comment]
If there are no strong currents in your model, you may solve the dispersion relation for the wavenumber K from a given the *intrinsic* angular frequency of the peak and the water depth. The wave length is 2 PI / K. You may adopt one of the two Fortran subroutines in w3dispmd.ftn, WAVNU2 (iterative procedure) or WAVNU3 (approximate formula). With currents, the dispersion relation is more complicated, although I think currents normally can be ignored for long peak wave lengths.

**Comment by Rachel201810** [comment]
> If there are no strong currents in your model, you may solve the dispersion relation for the wavenumber K from a given the _intrinsic_ angular frequency of the peak and the water depth. The wave length is 2 PI / K. You may adopt one of the two Fortran subroutines in w3dispmd.ftn, WAVNU2 (iterative procedure) or WAVNU3 (approximate formula). With currents, the dispersion relation is more complicated, although I think currents normally can be ignored for long peak wave lengths.

@CarstenHansen Thanks for your help!  And I have another question about the WAVNU2. This function also requires input EPS (Wanted max. difference between K and Kold) and NMAX (Max number of repetitions in calculation). I find that in some cases they are set to 1.E-6, 25, and in others they are set to 1E-7, 15. So I I'm not sure which set of values should be used if I use the water depth DW and the angular frequency calculated by peak frequency FP0?

**Comment by CarstenHansen** [comment]
@Rachel201810 I think the setting of the iteration convergence and the max number of iteration steps controls the accuracy, and the max number of iteration steps controls how fast the individual calculation should run. In parallel model runs NMAX must not be too high, but you may set a much higher value if you run a serial post-processing script.

**Comment by Rachel201810** [comment]
> @Rachel201810 I think the setting of the iteration convergence and the max number of iteration steps controls the accuracy, and the max number of iteration steps controls how fast the individual calculation should run. In parallel model runs NMAX must not be too high, but you may set a much higher value if you run a serial post-processing script.

@CarstenHansen Thanks a lot!!
