### ISSUE TITLE
Confusion about high frequency tail of Stokes drift

### ISSUE THREAD

**Issue by Rachel201810** [NOAA-EMC/WW3#287]
HI,

Sorry to be a bother. I have a confusion about the output Stokes drift at the sea surface. 

From the eq. 2.247, it seems that the addition of a high frequency tail is not considered in the calculation? But I found  that there is a corresponding calculation in w3iogomd.ftn, and it says "Tail for surface stokes drift is commented out: very sensitive to tail power". I wonder if I can get the right Stokes drift with high frequency tail after uncommenting these?

Appreciate your help.

Best regards!

**Comment by CarstenHansen** [comment]
Hi @Rachel201810

At our GEOMETOC Support Centre we have for some years run WW3 with an extended tail to get reasonable magnitudes of the surface Stokes drift in situations of a young sea state. We need this for oil drift estimation in Coast Guard operations. Unfortunately there has been no sound scientific base for estimating the accuracy of this calculation. We cannot say that it is the 'right' value of the high-frequency contribution to the Stokes drift. The same issue applies to the wave contribution to 'Leeway drift' calculations in Search and Rescue operations.

However, I think very recent scientific results may help in solving this, and which are now implemented as WW3 source term packages ST4 and ST6 (see the develop version of the User Manual and the References): Liu et al., 2019  ( ST6 ) and L. Romero, 2019 (ST4 - Romero). For young waves model parameters for the frequency-dependent first spectral directional moment (ETUSCX, ETUSCY) may be estimated from a wider spectral band, and a model for the omni-directional spectrum may be assumed to decay with frequency as FREQ^{-4}.

If you just uncomment the two lines for tail contribution to USSX, USSY, then I think this corresponds to assume that the product of the directional moment and the spectral level decays as FREQ^{-5}.

**Comment by Rachel201810** [comment]
> Hi @Rachel201810
> 
> At our GEOMETOC Support Centre we have for some years run WW3 with an extended tail to get reasonable magnitudes of the surface Stokes drift in situations of a young sea state. We need this for oil drift estimation in Coast Guard operations. Unfortunately there has been no sound scientific base for estimating the accuracy of this calculation. We cannot say that it is the 'right' value of the high-frequency contribution to the Stokes drift. The same issue applies to the wave contribution to 'Leeway drift' calculations in Search and Rescue operations.
> 
> However, I think very recent scientific results may help in solving this, and which are now implemented as WW3 source term packages ST4 and ST6 (see the develop version of the User Manual and the References): Liu et al., 2019 ( ST6 ) and L. Romero, 2019 (ST4 - Romero). For young waves model parameters for the frequency-dependent first spectral directional moment (ETUSCX, ETUSCY) may be estimated from a wider spectral band, and a model for the omni-directional spectrum may be assumed to decay with frequency as FREQ^{-4}.
> 
> If you just uncomment the two lines for tail contribution to USSX, USSY, then I think this corresponds to assume that the product of the directional moment and the spectral level decays as FREQ^{-5}.

@CarstenHansen  Thanks for your help!
