### ISSUE TITLE
bug in writing the restart file when requesting some output fields with ww3_multi

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#291]
this bug has been introduced with the update from Juan, actually he wrotes a note in wmiopomd and this need to be updated.

I'll find a regtest to confirm it works in multigrid with ice field mpi exchanges

corrections must be done in wmiopomd:
-ITO must be changed from 7 to 10 and update also the line after for SEND and RECEIVED
-uncomment lines for ICEO ICEFO ICEHO and rename to ICRO and so on

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi can you point to the PR with the update that this bug happened?

**Comment by mickaelaccensi** [comment]
this happens only when :
IOSTYP=2 or =3
PSHARE = T
and an output restart file is requested
and some output fields are requested

I'm not able to reproduce exactly the same error message with the regtest but still ww3_multi is crashing on array index which seems to be correctly instantiate when requesting a restart file and some output fields

To test it with a regtest :

add a restart output in mww3_test_04/input/ww3_multi_grdset_d.nml

```
&OUTPUT_DATE_NML
  ALLDATE%FIELD          = '19680606 000000' '1200' '19680608 000000'
  ALLDATE%POINT          = '19680606 000000' '3600' '19680608 000000'
  ALLDATE%RESTART        = '19680606 020000' '3600' '19680606 020000'
/
```

and add more output fields :
`  ALLTYPE%FIELD%LIST       = 'WND UST HS FP LM DIR SPR'`

then run the regtest :

`./bin/run_test -o both -N -f -S -T -c datarmor_intel_debug -s PR1_MPI -w work_PR1_MPI_d -m grdset_d -f -p $MPI_LAUNCH -n 28 ../model mww3_test_04`

it will crash with the following message :

```
forrtl: severe (408): fort: (2): Subscript #2 of the array VAAUX has value 17 which is greater than the upper bound of 16

Image              PC                Routine            Line        Source             
ww3_multi          00000000015B4770  Unknown               Unknown  Unknown
ww3_multi          00000000012C1329  w3iorsmd_mp_w3ior         559  w3iorsmd.F90
ww3_multi          0000000000DAA78D  w3wavemd_mp_w3wav        1413  w3wavemd.F90
ww3_multi          00000000008BA751  wmwavemd_mp_wmwav         871  wmwavemd.F90
ww3_multi          0000000000405363  MAIN__                    150  ww3_multi.F90
```

line 559 in w3iorsmd.F90 is WRITEBUFF(1:NSPEC) = VAAUX(1:NSPEC,JSEA,IP) :

```
                    IF ( IAPROC .EQ. NAPRST ) THEN
!
                        IH     = 1 + NRQ * (IB-1)
                        CALL MPI_WAITALL                         &
                           ( NRQ, IRQRSS(IH), STAT1, IERR_MPI )
                        IF ( IB .LT. NBLKRS ) THEN
                            IH     = 1 + NRQ * IB
                            CALL MPI_STARTALL                    &
                               ( NRQ, IRQRSS(IH), IERR_MPI )
                          END IF
!
                        DO ISEA=ISEA0, ISEAN
                          NREC   = ISEA + 2
                          CALL INIT_GET_JSEA_ISPROC(ISEA, JSEA, IP)
                          RPOS   = 1_8 + LRECL*(NREC-1_8)
                          WRITEBUFF(:) = 0.
                          IF ( IP .EQ. NAPRST ) THEN
                              WRITEBUFF(1:NSPEC) = VA(1:NSPEC,JSEA)
                            ELSE
                              JSEA   = JSEA - 2*((IB-1)/2)*RSBLKS
                              WRITEBUFF(1:NSPEC) = VAAUX(1:NSPEC,JSEA,IP)
                            END IF
```



bug introduced by commit e756361

@ukmo-ccbunney , @ukmo-juan-castillo , @ukmo-ansaulter, could you correct this bug ?

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi One of us will try and replicate the bug on our system and investigate.

**Comment by mickaelaccensi** [comment]
Hi Guys,

cold you please look at this bug ? I'm not able to upgrade my forecast system with the last version of ww3 due to this bug. thanks

**Comment by ukmo-juan-castillo** [comment]
After some investigation, it looks like this bug is fixed after fixing issue #290, so the present issue can be safely removed. Please send new tests once #290 is resolved and check if the problem is still present.

**Comment by aliabdolali** [comment]
@mickaelaccensi is this issue solved?

**Comment by ukmo-juan-castillo** [comment]
It should be now fixed, please send a new test with the latest version of develop to make sure.

**Comment by mickaelaccensi** [comment]
yes it worked for me with the last version of develop branch. I close the issue
