### ISSUE TITLE
Extra gridded output fields required

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#296]
As part of adopting WW3 version 7 as our operational wave model (from vn 4.18) we require some extra gridded output fields to be generated by ww3_ounf. The internal data for these fields already exist, but just needs outputting in a different convention or unit:

  - Peak period (from peak freq)
  - Wind speed and direction (from U and V components)
  - Current speed and direction[ (from U and V components)

My proposed solution to do this is to add new output field identifier/flags for these but internally reference the existing variables (so no extra I/O or memory allocation is performed by w3iogo et al.) It is then simple to add an extra output in ww3_ounf (and the other gridded output post-processors) to generate the required fields.

For example, requesting "peak period", will cause the "peak freq" (FP0) to be written out by w3iogo. The reciprocal of this will then be output by ww3_ounf as peak period. The same goes for wind speed/dir and current speed/dir where they will be written in a magnitude/direction convention.

I propose the following new flags/IDs

  - IFI=1, IFJ=11, ID='CURD' : Current speed and direction
  - IFI=1, IFJ=12, ID='WNDD' : Wind speed and direction
  - IIFI=2, IFJ=18, ID='TP' : Peak period

Before I start working on this, does anyone have any objections or thoughts on a different solution?

**Comment by ukmo-ccbunney** [comment]
Tagging @mickaelaccensi  @thesser1  @aliabdolali  @JessicaMeixner-NOAA  @ukmo-ansaulter  for their opinions.

**Comment by JessicaMeixner-NOAA** [comment]
I like the idea of not adding extra memory requirements to the code itself. That's a great idea. 

I know in ww3_grib when you request WND (at least with a certain combo of switches) you already get 4 variables: uwind,vwind, wind speed, wind direction.  Same for currents.  So one thought would just be to add that to the netcdf & other output to match for wind and currents.  However, I suspect others have space issues as well and might not want extra variables unless explicitly requested.

**Comment by mickaelaccensi** [comment]
ok for the idea
do you keep the possibility to output both uwnd, vwnd and wnd, wnddir ?
I would prefer WNDDIR for the ID, same for current CURDIR. I know this variable name is used in other numerical models, so it would be consistent

**Comment by aliabdolali** [comment]
@ukmo-ccbunney I am ok with calculating WND and WNDDIR (CUR and CURDIR) from the UWND, VWND and UCUR, VCUR in ww3_ounf.

**Comment by aliabdolali** [comment]
@ukmo-ccbunney will you add it to one of our existing regtests (both options)?

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi 
> do you keep the possibility to output both uwnd, vwnd and wnd, wnddir ?

Yes - I intend it to be possible to output both, if required, by specifying both flags/IDs.

> I would prefer WNDDIR for the ID, same for current CURDIR. I know this variable name is used in other numerical models, so it would be consistent

Sounds sensible; I'm happy with that.

**Comment by ukmo-ccbunney** [comment]
@aliabdolali
> 
> @ukmo-ccbunney will you add it to one of our existing regtests (both options)?

Yes - once implemented I can modify an existing regtest to output both.

**Comment by ukmo-ccbunney** [comment]
@JessicaMeixner-NOAA 

> I know in ww3_grib when you request WND (at least with a certain combo of switches) you already get 4 variables: uwind,vwind, wind speed, wind direction. Same for currents. So one thought would just be to add that to the netcdf & other output to match for wind and currents. However, I suspect others have space issues as well and might not want extra variables unless explicitly requested.

I would prefer it to not be an "all or nothing" approach if possible. Reducing the amount of disk space usage in our operational suite of models is always something that we strive for!

**Comment by ukmo-ccbunney** [comment]
Thanks all for your input - it sounds like there are no particular objections. I will prepare a branch with the changes in due course.

**Comment by ukmo-ansaulter** [comment]
Nice one @ukmo-ccbunney , definitely no objections from me!

**Comment by ukmo-ccbunney** [comment]
After discussing with the rest of the repo managers, it is decided that the direction/magnitude output for directional fields will be controlled via a `VECTOR` flag in the input/nml file, similar to as in `ww3_outf`.

**NOTE**: This new VECTOR flag will only be available via the `.nml` file. It will default to True (as current behaviour) for the `.inp` file.

This means the proposed `CURDIR` and `WNDDIR` fields will no longer be implemented.
However, the new `TP` field will still be implemented as described above.

I will raise a new PR for this.
