### ISSUE TITLE
add sea/swell correction options for ww3_uprstr method

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#30]
Add in  wave spectrum update method, following Lionello et al (1992), to ww3_uprstr.ftn

**Comment by ukmo-ansaulter** [comment]
For assignment to @ukmo-ansaulter

**Comment by ukmo-ansaulter** [comment]
Code has now been updated and tested with Met Office regular and SMC grid trials suites, plus new regtests. Summary of changes is as follows:

- Added UPD5 option; bulk change to wind-sea or full spectrum based on proportion of wind-sea
- Added UPD6 option; as per UPD5 but wind-sea energy distribution is shifted in frequency space using Toba (1973)
- WRST switch is used to read wind data from restart file for UPD5 and UPD6; this is the recommended option, although the facility to read from the anl.XXX file (SWH, WSPD, WDIR) is available
- Regtests have been added for UPD5 and UPD6 options
- The code in ww3_uprstr.ftn has been tidied to make the style for each option a little more consistent

Regtests with the updated code introduce changes in ww3_uprstr.out files; these are correcting a typo for the module name

**Comment by ukmo-ansaulter** [comment]
Review and pull request open on UKMO trusted repo: https://github.com/ukmo-waves/WW3/pull/1

@ukmo-ccbunney assigned for review

**Comment by ukmo-ansaulter** [comment]
UKMO review complete and feature branch merged into UKMO repository develop branch
https://github.com/ukmo-waves/WW3/tree/develop

UKMO pull request to NOAA repository pending other UKMO develop updates

**Comment by aliabdolali** [comment]
@ukmo-ccbunney can we close it?

**Comment by ukmo-ansaulter** [comment]
Yes we can @aliabdolali 👍
