### ISSUE TITLE
Error when cloning project:  "Clone succeeded, but checkout failed" - model/aux folder missing

### ISSUE THREAD

**Issue by basepot** [NOAA-EMC/WW3#301]
Dear all,

I'm a student Offshore engineering at the TU Delft and I want to use WAVEWATCH III for my master thesis. When cloning the project via either GitHub or the Git terminal I keep getting the same error: "Clone succeeded, but checkout failed"

When I try it via the zip file, the 'model/aux' and 'model/bash' folder just do not copy where I get the error 'Can not make .... because system cannot find the specified path'.

I fear that it has something to do with the fact that my OS is Windows and that these extentions are in the Linux domain, however my knowledge of Linux is close to nihil. Can someone help me how I can solve this issue?

Kind regards

**Comment by ukmo-ccbunney** [comment]
Hi @basepot ,

That error sounds like perhaps you don't have enough disk space? Or perhaps incorrect write permissions on that directory?
Can you try cloning to a different directory?

I don't know of anyone running WW3 on Windows - you might have some problems with all the supporting scripts (which use bash) unless you are using the Windows Linux Subsystem, or something similar...

P.S. you might get a better response for questions like this from the WW3 users mailing list:
https://www.lstsrv.ncep.noaa.gov/mailman/listinfo/ncep.list.wwatch3.users

**Comment by JessicaMeixner-NOAA** [comment]
There is an issue cloning on a window's machine because we have a folder called "aux" and windows OS does not like this.  I also don't know of anyone who has successfully built and ran WW3 on a windows platform.

**Comment by basepot** [comment]
Thank you both for answering. It seems that I have to re-evaluate my plan to use WW3 since I have no Linux experience...  :/

Back to the wave buoys it is

**Comment by JessicaMeixner-NOAA** [comment]
I am closing this issue, however please feel free to re-open it or open a new issue if you have further questions.
