### ISSUE TITLE
Looking for help with ww3_grib

### ISSUE THREAD

**Issue by MicahDavid** [NOAA-EMC/WW3#309]
Hi, 

I see in the docs that grib packaging isn't fully supported in the code, and user has to provide routines.  Can anyone guide me to accomplishing the task of providing the routines? I see the NCEP grib libraries here: 
https://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/

How can I link the appropriate libraries?
Thank you. 

PS. Ultimately, my goal is transform the model output to mercator projection, and it looks like the easiest way is to use the wgrib2 utiltiy to do this. Of course I need grib files in order to use the wgrib2 utility.

**Comment by JessicaMeixner-NOAA** [comment]
You will need the following variables from modules/libraries defined when building ww3_grib: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/bin/link.tmpl#L111
    libs="$libs ${G2_LIB4} ${W3NCO_LIB4} ${BACIO_LIB4} ${JASPER_LIB} ${PNG_LIB} ${Z_LIB}"

**Comment by MicahDavid** [comment]
Thank you Jessica. I understand the idea now, but just not sure how to appropriately set the G2_LIB4, W3NCO_LIB4, ... variables. For example, I downloaded the g2 library, and there is a bunch of files.  Is G2_LIB4 the path to the library files? And, similar for the rest of the required libraries?

**Comment by MicahDavid** [comment]
I see that there are makefile's included in each library, so it looks like I need to do a `make` to compile the libraries, and then link to the compiled library file.

**Comment by JessicaMeixner-NOAA** [comment]
Yes, you will need to have all of the libraries built and then link to them if you don't have access to another build.   If you do not have a requirement that your output has to be in grib (other than to use a wgrib2 function), an easier path might be to go for netcdf and see if a python or other tool can replicate the wgrib2 function for you.  

I will give you a heads up there's an issue with the latest release of Jasper, so I'd recommend using a 1.9 version or the master version of jasper.

**Comment by MicahDavid** [comment]
Hi Jessica, I was able to compile all libraries, as well as ww3_grib, and run successfully. Thanks so much for your help. I downloaded all the libraries from the NCEP grib resource page: https://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/, and everything looks to run properly.  

The biggest difficulties for anyone else who may run across this thread, was just properly configuring the libraries with the appropriate options for my system.  Once configured, I changed the NOGRB in the switch file to NCEP2, and added the appropriate libs that were mentioned above in the link file.  

Having all of the outf variables in a gribfile will be very convenient for me.

**Comment by JessicaMeixner-NOAA** [comment]
@MicahDavid I'm so happy that you were able to successfully produce grib2 files.  It's not necessarily a straightforward process or easy, so I'm glad it went relatively smoothly for you!  Hopefully we'll be able to provide  more detailed information about this in the future.  I'm going to close this issue, but feel free to re-open this or another issue if you run into any other problems.
