### ISSUE TITLE
optimization/scaleability of ww3psmcmod

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#31]
Re-structured SMC propagation code for improved scaleability in hybrid MPI-OpenMP mode

**Comment by ukmo-ansaulter** [comment]
For assignment to Jian-Guo Li (once he gets his GitHub account)

**Comment by ukmo-ccbunney** [comment]
SMC Hybrid MPI/OMP code was added whilst the codebase was hosted in VLab.
#183 also covers some updates.
