### ISSUE TITLE
COMSTR is defined in ftn/wminitmd.ftn but not in ww3_shel.ftn.

### ISSUE THREAD

**Issue by CarstenHansen** [NOAA-EMC/WW3#313]
I would like COMSTR to be defined (with the usual value '$') in `ww3_shel.ftn`, so that I can place commenting lines in the `points.list` file that accompanies the namelists input file `ww3_shel.nml`.

Just after
https://github.com/NOAA-EMC/WW3/blob/c758e87e9b2025cc9af5ebb4745adedef6a00001/model/ftn/ww3_shel.ftn#L555
insert:

!
      COMSTR = '$'

**Comment by ukmo-ccbunney** [comment]
I agree that this sounds like a sensible addition, @CarstenHansen 
Would you like me to raise a PR for it in our repo?

**Comment by CarstenHansen** [comment]
Thank you @ukmo-ccbunney, that would be very fine. I have tested that the addition works as expected.
