### ISSUE TITLE
ww3_tp2.18, ww3_prnc.out from regtest has differences 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#319]
When comparing two outputs from the test: 
`./bin/run_test -b slurm -c hera -S -T -s TIDE_MPI     -w work_TIDE_MPI -o netcdf       -f -p mpirun -n 12 ../model ww3_tp2.18
`with matrix.comp, the file ww3_prnc.out is reported as different (sometimes between runs, sometimes when using different MPI tasks).  These do not appear to be meaningful differences, so I think matrix.comp and/or the output to prnc.out needs to be updated so that these differences are not flagged.

**Comment by ukmo-ccbunney** [comment]
Possibly a duplicate of issue #225 ?

**Comment by JessicaMeixner-NOAA** [comment]
Closing issue since this is a duplicate of #225
