### ISSUE TITLE
ww3_ounf to use user defined variable name/metadata options

### ISSUE THREAD

**Issue by ukmo-ansaulter** [NOAA-EMC/WW3#32]
Restructure ww3_ounf code to use alternative, user defined varaible name and metadata packages, e.g. CF-1.7 compliant data and variable names used by Copernicus Marine Environment Monitoring System and Met Office ServiceHub

**Comment by ukmo-ansaulter** [comment]
For assignment to @ukmo-ccbunney and/or @ukmo-ansaulter

**Comment by ukmo-ccbunney** [comment]
I would be good to start a discussion here regarding ideas for how to make the meta-data in ww3_ounf more configurable.
The fact that each output is (represented by a IFI, IFJ combination) can have more than one field complicates matters somewhat. So does the fact that the partitioned parameters can have a variable number of output fields.

I have played around with having a whole separate module to set different (hard-coded) meta-data values for each variable. However, a more preferable solution would be to be able the user to override/add extra meta-data for each variable. How to achieve this cleanly is the question I would appreciate some thoughts on!

**Comment by ukmo-ansaulter** [comment]
@ukmo-ccbunney 3 possible options come to mind?

1. move the existing if-then-else construct looped within IFI,IFJ to a separate module/subroutine which could then be duplicated for the Copernicus variable set-up, and we simply call one or the other based on a logical for using 'standard' or 'copernicus' variable types. I don't like this option as its not very elegant and doesn't clean the code up particularly and requires duplicate code for any new variables(?), but it is an option nonetheless

2. create a module/subroutine that sets all the existing metadata fields into arrays (including empty strings for the additional dimensions) and pulls data from these in the existing if-then-else construct. For an alternative variable set, we can make a call to overwrite specific fields in the 'standard' arrays with the metdata specific to our alternative (e.g. for copernicus, update the relevant variable names and set the globwave fields to empty)

3. A bit like 2, but instead of using arrays use namelists (for each field type). This would be more subtle as (in the long run) the code could be implemented in the namelist module and the user then has control of the metadata at the lowest level (instead of just throwing a 'copernicus' switch for example). It might also be a bit clearer as to what metadata is set for each field type (the arrays could get a bit confusing?)

A hybrid of option 1/2 and 1/3 might be sensible in that maybe the navigation of the code would be easier if the giant if-then-else construct was in its own space?

In saying this, I haven't looked too hard at the edge cases such as partitioned wave data and the 1D spectra...

**Comment by CarstenHansen** [comment]
Hi Folks

Maybe this can help. I have constructed a modification to ww3_ounf.ftn (Feature 18c8294) which is a kind of solution to the complication that Chris mentions of different kind of output fields for the various parameters. It appears that two specific parameters (P2S and BED) are the only ones that was not conforming to a simple rule for the output field structure. After the present modification these are divided in sub-parameters and now the configuration parameter NFIELD indicates if the output fields form a scalar (NFIELD=1), a horizontal vector (NFIELD=2) or a tensor (NFIELD=3). I think a step like this will also help in constructing Andy's suggested hybrid construction.

There remains a little confusion in using the terms 'field' and 'parameter', but I hope my explanation is clear enough.

I have worked on this from time to time over the last year with the purpose of introducing another type of third dimension: a vertical level for load on ship's hull or Stokes drift of small particles.

**Comment by ukmo-ccbunney** [comment]
Hi @CarstenHansen,

Thanks for your input. 

I have just pushed up a first attempt (still a work in progress at the moment) of configurable meta-data for ww3_ounf here: 
https://github.com/ukmo-waves/WW3/commits/fb_ounf_config
The `w3nmlounfmeta.ftn` file contains the main functionality and provides meta data to ww3_ounf packaged in a derived type.

I like your idea of grouping the outputs as scalar, vector and tensor fields.  I might try and implement a similar grouping in my code to reduce unnecessary array allocations.

**Comment by ukmo-ccbunney** [comment]
Hello all,

So - I think I have a working solution to the configuration of netCDF meta-data for `ww3_ounf`. Please see `w3ounfmetamd.ftn` in my `fb_ounf_config_v2` branch:

 https://github.com/ukmo-waves/WW3/blob/fb_ounf_config_v2/model/ftn/w3ounfmetamd.ftn

Meta data for each WW3 output variable is now stored as arrays of META_T derived types (grouped by output group).

Default meta data is set by the WW3 code (as per the original ww3_ounf module). These metadata entreis can be overriden using a `ounfmeta.inp` text file with the following format:

```
$ comment line
$ (blank lines are ignored)
$ tabs are converted to spaces
$
  META [ IFI [ IFJ ]  |  FLDID ]   [ IFC ]
       attr_name = attr_value
       attr_name = attr_value
       extra_attr = extra_value [type]

  META .... repeat
  .
  .
```

Each `META` line selects a WW3 output field either by its `IFI, IFJ` (group, field) value, or the output tag name (e.g. HS, WND, etc).
An optional extra IFC value selects the component for multi-component fields (e.g. wind).

The attributes are then set using `name = value` pairs.

If and attr_name does not match one of those defined in the META_T, then it is assumed to be an option "user" or "extra" metadata pair. In this case, you can set an optional "type" to be "c", "i", or "f" for character, integer or real to specify how the value will be written to the netCDF file.

Meta data for partitioned parameters have a special `<IPART>` placeholder that will be merged in with the current partition number when output.

Here's an example of what our CMEMS input file might look like:
```
META HS
$ Could also be specified as 'META 2 1`
  varnm="VHM0"
  varnl="Spectral significant wave height (Hm0)"
  
META FP
  varnm="VTPK"
  varns="sea_surface_wave_period_at_variance_spectral_density_maximum"
  varnl="Wave period at spectral peak / peak period (Tp)"
  
META T0M1
  varnm="VT0M1"
  varns="sea_surface_wave_mean_period_from_variance_spectral_density_inverse_frequency_moment"
  varnl="Wave period at spectral peak / peak period (T0M1)"

META PHS
  varnm="VHM0_<IPART>"
  varnl="Spectral significant wind wave height"
```

@thesser1 - tagging you here as you expressed an interest in this.
@mickaelaccensi  - I would be very interested in your opinion on how I have implemented this.

-------------
### Note
We did discuss using a NAMELIST approach to this problem, and my first version did indeed use a namelist as input. It used an input namelist with the following format:
```
&NML_META
   ! Select by field name...
   META(1)%FLDID = ‘HS’
   ! ... or IFI, IFJ combination:
   META(1)%IFI = 2
   META(1)%IFJ = 1
   META(1)%VARNL = ‘sig wave height’
   META(1)%VMAX = 30.0

   META(2)%FLDID = 'WND'
   META(2) .... etc
```

However, I found this sub-optimal for a several reasons:
 1. The way the output fields (and meta data) are arranged in "groups" makes this difficult. To enable a "flat" namelist file and provide a flexible way of selecting an output field (e.g. using field name tags) it was not possible to modify the META data arrays directly using a namelist. Therefore I had to perform the merging of modified data manually which negated the benefit of using a NAMELIST in the first place.
 2. Having to specify the arbitrary array index of each META entry in namelist is prone to error
 3. I have run into compiler implementation issues with the handling of DERIVED TYPES in namelists...

The branch for that implementation is here if you are interested (changes are mostly in the same module):
https://github.com/ukmo-waves/WW3/blob/fb_ounf_config/model/ftn/w3ounfmetamd.ftn

**Comment by thesser1** [comment]
@ukmo-ccbunney I can definitely make this format work for my needs.  It reminds me a lot of the yaml files we have been using up to this point without the required libraries.

**Comment by ukmo-ccbunney** [comment]
@thesser1 - Great, I'm glad you approve.
A proper YAML parser would be nice, but I don't fancy writing one!

**Comment by CarstenHansen** [comment]
@ukmo-ccbunney this is a brilliant solution to the issue. Being a small information services group we benefit from the good accessibility of forecast and monitoring products from Copernicus and other data hubs.

It could be extended with user input for global attributes?

PS. There is a 'scale_factor' attribute for netCDF variables with datatype short (not 'scale_value').

**Comment by ukmo-ansaulter** [comment]
@CarstenHansen thanks for the input, Chris has been working hard on this so its great good that the changes look valuable :)

For global attributes, ww3_ounf already allows additional user defined input to be read in via text file; see the lines referencing the file 'NC_globatt.inp' around line 5107. From memory we've managed to use this to meet Copernicus/Met Office requirements for global attributes so far, but possibly it's worth thinking about amalgamating the two functions??

Also quite aware that ww3_ounf might need some review for general CF compliance. The CF conventions and standard_name tables have moved on quite a way since the code was originally conceived. Hopefully we will do that alongside getting this additional functionality in place.

**Comment by chrisbunney** [comment]
Thanks for the encouraging feedback  @CarstenHansen . I will update the incorrectly named “scale_value” - good spot! I was already thinking of adding support for the global attributes via the same input file with a special “META global” section that parses a list of the “extra” types; I will make some updates for this next week.

**Comment by ukmo-ccbunney** [comment]
@CarstenHansen I've updated the [w3oufmetamd.ftn]( https://github.com/ukmo-waves/WW3/blob/fb_ounf_config_v2/model/ftn/w3ounfmetamd.ftn ) module to handle user configuration of the "global" meta data. I've also factored out some common functionality to achieve this into separate subroutines. The incorrect "scale_value" attribute has also been fixed.

If there are not objections to this approach from anyone, I will polish off the code and raise a PR for the change.

C

**Comment by CarstenHansen** [comment]
@ukmo-ccbunney I don't want to anticipate the review process, and I am not an expert in netCDF datasets. But I am not sure of the implications of writing real values for valid_min, valid_max. Will they be converted automatically to datatype short if the netCDF variable is a short?

**Comment by ukmo-ccbunney** [comment]
@CarstenHansen That's a good point. I overlooked the fact that the valid_min and valid_max are written as integers. I don't think it will matter as the field data itself can be written as a REAL or a SHORT, so the comparison between the two different types will still end up occurring. However, I will follow the original design of WW3_OUNF and set it as a short.

I am considering allowing the user to set "unscaled" vmin and vmax values, e.g. 0 - 64 for Hs rather than 0 - 32000, and then scaling that value appropriately by the `scale_factor` when writing (although 64m seems a little big for Hs!)

Thanks for the useful comments!

**Comment by ukmo-ccbunney** [comment]
The most recent version now writes `valid_min` and `valid_max` as integer values, as per the original WW3_OUNF behaviour.
The values in the `ounfmeta.inp` file are now floating point values in the units specified for the variable; they will be scaled by `scale_factor` and converted to integers values when written out.

**Comment by aliabdolali** [comment]
@ukmo-ccbunney can we close it?
