### ISSUE TITLE
Update to NetCDF libraries linked for use with NOAA hpc-stack

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#332]
When using NOAA's hpc-stack, the NetCDF libraries were not linking properly (see issue https://github.com/NOAA-EMC/hpc-stack/issues/193).  To fix this, in link.tmpl: 

```
       NC4) if [ "$mpi_mod" = 'no' ]; then comp="`$NETCDF_CONFIG --fc`"; fi
-           libs="$libs `$NETCDF_CONFIG --flibs`" ;;
+           libs="$libs `$NETCDF_CONFIG --flibs` `$NETCDF_CONFIG --libs`" ;;
```

Note, adding the extra $NETCDF_CONFIG --libs did not break the compile/linking for libraries not using hpc-stack.

**Comment by JessicaMeixner-NOAA** [comment]
Another suggestion from @aerorahul: 

```
You may also want to change Line 86 in bin/comp.tmpl to:

opt="$opt `$NETCDF_CONFIG --cflags`" ;;
```

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA Are you going to make a FB for this fix?

**Comment by JessicaMeixner-NOAA** [comment]
Yes I will make a PR with fixes for this.  Testing the comp.tmpl changes now.  

I could also update our regression tests to point to hpc-stack modules with this PR or wait for a follow up one.  I believe that would require a new parametis to be built.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA Great,
I do not know how to compile a library under hpc-stack, if you refer me to the right place/guide, I can do it and update regtests in your feature branch.

**Comment by JessicaMeixner-NOAA** [comment]
Well, right now PARMETIS is in your directory, so instead of compiling it with the modules currently used in the regtests for WW3 which on hera are: 
intel/18.0.5.274 impi/2018.0.4 netcdf/4.6.1 
and then we have: 
/scratch2/COASTAL/coastal/save/Ali.Abdolali/parmetis-4.0.3

if you build parmetis, with the hpc-stack: 

```
module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-intel/18.0.5.274
module load hpc-impi/2018.0.4
module load netcdf/4.7.4

```
then we could point to that new parmetis and be using the hpc-stack version of modules instead of the non-hpc-stack modules for when we run regression tests.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA I can do it now. Where do we want to compile it? still under
/scratch2/COASTAL/coastal/save/Ali.Abdolali/parmetis-4.0.3
or somewhere else? if somewhere else, then I might need a write permission.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali I personally would not recommend over-writing your current parametis installation, but somewhere in your directory space is fine for now in my opinion.

**Comment by aliabdolali** [comment]
> @aliabdolali I personally would not recommend over-writing your current parametis installation, but somewhere in your directory space is fine for now in my opinion.

I meant in my directory, not overwrite :)
BTW, here is the path to METIS with hpc-stack
/scratch2/COASTAL/coastal/save/Ali.Abdolali/hpc-stack/parmetis-4.0.3
please modify regrests/bin/matric_ncep

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali is there a path for parmetis w/hpc-stack on orion?

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA 
I compiled them on Orian using the following

module use /apps/contrib/NCEP/libs/hpc-stack/modulefiles/stack
module load hpc/1.1.0
module load hpc-intel/2019.5
module load hpc-impi/2019.6

and the path is 
/work/noaa/marine/ali.abdolali/Source/hpc-stack/parmetis-4.0.3

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @aliabdolali   I have 3 sets of regression tests running: 
1 w/just the comp/link updates 
1 w/the new hpc-stack libraries 
1 w/new hpc-stack libraries + changing the number of ranks  (I started this when I thought we were changing the versions of intel, so that would perhaps change answers and be a good opportunity for this change too, on second glance we are not doing this so maybe I should hold off on this part?) 

I also am running a small subset of tests on orion, just for a functionality test. 

I'll push the PR when I have the regression test results.  My branch is here: https://github.com/JessicaMeixner-NOAA/WW3/tree/NetCDFcomplink

**Comment by YanJia1** [comment]
Hi all,
Intel compiler cannot compile through when including `$NETCDF_CONFIG --libs`. It cannot find ww3_prnc.
Following the hint of an older version of WW3 in COAWST, I switched back to libs="$libs `$NETCDF_CONFIG --flibs`". 
Thank you,
Yan

**Comment by mickaelaccensi** [comment]
Hi Yan,
You should set your environment variable NETCDF_CONFIG to nc-config instead of nf-config. This change of setting is described in the manual. The reason to have changed it was due to incompatibility on various HPC system.
Can you please confirm me that it works for you using NETCDF_CONFIG=nc-config and linking with $NETCDF_CONFIG --libs

**Comment by YanJia1** [comment]
Hi Mickael,
It does not work. I have tried that before this post and tried it again today 100% following your suggestions.
I am using netcdf-c-4.8.1 and netcdf-fortran-4.5.3. My ifort version is 16.0.3, which is relatively old.
Thank you,
Yan
