### ISSUE TITLE
w3triamd fails to build with gnu compiler

### ISSUE THREAD

**Issue by thesser1** [NOAA-EMC/WW3#339]
**Describe the bug**
The w3triamd code fails to build with gnu compiler on develop branch.

**To Reproduce**
Compile ww3_grid with develop branch when using gnu compilers.  

**Expected behavior**
Looks to be caused by using SIGN with real(4) and real(8) variables.

**Comment by aliabdolali** [comment]
@thesser1 
Just from a conversation we had, a fix would be converting 360.0 to 360.0d0 to make it a real(8) instead of real(4) in:
https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/w3triamd.ftn#L2823-#L2828
So I keep it for the record here.
