### ISSUE TITLE
v16 branch: port to comet 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#343]
the production v16 branch was ported to comet, however this means it does not match what is in operations.  To limit changes that are needed in operations to just what is relevant to an upcoming change, the comet porting was reverted.  Either a new branch w/comet porting needs to be added or another solution needs to be determined.  Due to the time crunch, the branch the changes are going to be reverted for now until a better solution can be found.  FYI: @MinsukJi-NOAA @aliabdolali

**Comment by aliabdolali** [comment]
@MinsukJi-NOAA Do we need to add it to the Develop?

**Comment by MinsukJi-NOAA** [comment]
@aliabdolali thanks for checking. That will not be necessary since the wave component is not used on Comet. This issue can be closed.
