### ISSUE TITLE
grib encoding issues for PolarStereo grid

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#345]
For the polar stenographic grid in ww3_grib when GDTN = 20 
KGDS( 1) should be 5 not 6 

KGDS( 1) = 5  means Earth assumed represented by WGS84 see https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-2.shtml

**Comment by JessicaMeixner-NOAA** [comment]
Still need to merge this update to the develop branch.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA, it requires grib regtests, so the one I made for GFSv16 has this already. Do you think it should be on a separated PR?
i can make grib regtest totally separate + this fix.

**Comment by JessicaMeixner-NOAA** [comment]
Awesome, glad this is include in that PR. That PR would close this issue then.
