### ISSUE TITLE
Make ww3_grid a callable subroutine 

### ISSUE THREAD

**Issue by sbrus89** [NOAA-EMC/WW3#348]
I wanted to suggest and socialize the possibility  of making `ww3_grid.ftn` into a new module (e.g. `w3gridmd`). The main program code of `ww3_grid` would be put into a subroutine (e.g. `w3grid`) that could be called in other places after using the module. 

Having the new `w3grid` subroutine means it could be called from a coupler initialization routine so that the `mod_def.ww3` file would be created from an ascii `.msh` file and `ww3_grid.nml` at runtime.  Also, this could help simplify building the wave component library for a coupled model, since the `w3gridmd` module would be compiled as a part of the wave component build. It would eliminate the need to  have a separate step for building and running the `ww3_grid` executable.

The current functionality of the `ww3_grid` executable would be unchanged since it would now use `w3gridmd` and call `w3grid`

Here is a schematic of the proposed changes:
![Screen Shot 2021-04-09 at 10 45 41 AM](https://user-images.githubusercontent.com/3514023/114206223-bcc59280-9920-11eb-9bb6-a4c29ec3554c.png)

Here are some links to examples of the proposed code modifications:

WW3 changes:
https://github.com/sbrus89/WW3/compare/d30e4e90..5dd1375
(note that this involves an initial file rename:  `model/ftn/ww3_grid.ftn` → `model/ftn/w3gridmd.ftn`)

Coupler use case:
https://github.com/E3SM-Project/OceanNGD/pull/1/files#diff-b63f62e5f1e5b431031bf57a14f745b71c8c6304de33a9281cb949fc93b234fb
(specifically relevant lines are: 166,  314-321 of  `wav_comp_mct.F90` on the right)

Let me know if this is a viable option for a possible PR in the future. I'm sure there are other considerations for current and planned future workflows that need to be accounted for, so I appreciate any feedback. Thanks for your consideration!

**Comment by JessicaMeixner-NOAA** [comment]
For this current use case, I would say the most important test would be to make sure that you can run the model the current way and then run your coupled model with this new function call and make sure that you get the same answers.  The cause for concern there is that ww3_grid is built with SHRD switch while your coupled model is likely build with DIST MPI switches and therefore there is potential for errors there. 

@aliabdolali @thesser1 is there any current development with unstructured grids and ww3_grid that would potentially conflict with this?   I remember something about making ww3_grid parallelized that could potentially cause an issue?

**Comment by sbrus89** [comment]
@JessicaMeixner-NOAA, I've made sure this function call produces the same results as before. I've always used the DIST and MPI switches for compiling ww3_grid and ww3_shel. This is also how the .F90 files are being generated (via w3_source) for building the wave component of the coupled model, which now includes ww3_grid and ww3_shel source code.

**Comment by JessicaMeixner-NOAA** [comment]
Thats great @sbrus89 -- I'd recommend submitting a PR then assuming @aliabdolali @thesser1 or someone else can think of a reason this would not be okay.

**Comment by aliabdolali** [comment]
Hi @sbrus89 
This idea is great. Are you using ww3_shel or ww3_multi for your coupled application?
Have you checked it with ww3_multi?
We need a regression test for it. What about ww3_tp2.21?
I'd be more than happy to help and add a proper regression test for it.

**Comment by sbrus89** [comment]
Hi @aliabdolali, I'm using ww3_shel. Unfortunately, I don't have any experience with ww3_multi, so I haven't checked that yet. I'll take a look at ww3_tp2.21, but might need some help from you when you have time.

**Comment by aliabdolali** [comment]
Do I have the write permission for this PR? if yes, I can add ww3_Multi for ww3_tp2.21 and you try it. I am available to help.

**Comment by sbrus89** [comment]
I haven't made a PR yet, but I can do that today.

**Comment by JessicaMeixner-NOAA** [comment]
Collaboration can be done without write permission through PR to other forks.
