### ISSUE TITLE
Remove support for NetCDF version 3 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#358]
Currently, WW3 has two build options, either NetCDF version 3 or 4.  NetCDF version 4 was released in 2008.  At this time, we plan to remove options for NetCDF 3 in WW3. 

This work would be planned for the end of May 2021.

**Comment by JessicaMeixner-NOAA** [comment]
Does anyone (@mickaelaccensi) know if this is still an issue with NC4 for ww3_ounp? 
https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/ww3_ounp.ftn#L636-L644 
I guess having this be NCTYPE=3 could still be supported but, ideally we could move to just having NC4 be the default and then we would have no need for NCTYPE either.

**Comment by mickaelaccensi** [comment]
Depending on some netCDF4 library versions, there are memory leaks that impact the program ww3_ounp. I know that some colleagues are still using netCDF3 for postprocessing so it should be good to keep it

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi  good to know!   For clarification, are they using NCTYPE=3 or using NetCDFv3.x ?

**Comment by JessicaMeixner-NOAA** [comment]
Another follow up question: Do we know which netCDF4 library version this is an issue for? Or is it random ones or say past version 4.x it is fixed?

**Comment by mickaelaccensi** [comment]
it's compiled with netcdf4 but only requesting NCTYPE=3 which that only limited functions and dependencies are called.
It's not directly linked to the netCDF4 library but from what I saw it's linked to hdf5 library. It's very sensitive to the version, memory leaks have been found before v1.8.14 and I know some recent versions were not fully stable.. so it's still good to work with NCTYPE=3 sometimes

**Comment by JessicaMeixner-NOAA** [comment]
So if we keep NCTYPE=3, but remove the build support for NetCDFv3 would that be okay?

**Comment by mickaelaccensi** [comment]
yes, it's fine for me
