### ISSUE TITLE
Make NC4 the default switch 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#359]
After support for NetCDF 3 is removed (Gith Hub issue), the NC4 switch could then be made the default option and the switch itself would no longer be necessary. 

This work is planned for the end of May 2021 and would be completed after the support for NetCDF 3 is removed (Issue #358).

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi based on your comments on the other issue, wanted to point this out and see if you thought this might be an issue? By making this the default, my thought is you just remove any !/NC4 and always compile with that.

**Comment by mickaelaccensi** [comment]
so it won't be possible to compile ww3 with netcdf3 ? it think it's an issue to remove it now. since netcdf4 needs a lot of dependencies which are not always well linked, it would be safe to keep the possibility to compile with netcdf3 (which does not use hdf5, zlib, ..). The default should be netcdf4 and a cpp key should be set to disable netcdf4 feature (nf90_create and and nf90_deflate)

**Comment by JessicaMeixner-NOAA** [comment]
Correct, we are hoping to remove support for NetCDFv3.  NetCDFv4.0 was introduced in 2008, so NetCDFv3 is fairly old.  We could keep the different compression options, but from a code management perspective I think moving to only supporting NetCDFv4+ is a good simplification.

**Comment by JessicaMeixner-NOAA** [comment]
We could keep the NC4 switch and still remove NetCDFv3 build support and keep the ability for NCTYPE=3.  So basically not remove NC4 switch, but continue with removal of NetCDFv3 (so not do this issue, but continue with https://github.com/NOAA-EMC/WW3/issues/358)

**Comment by mickaelaccensi** [comment]
it's fine for me

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi I have started looking at the NC4 switch a little more, and most of the lines with an NC4 switch have: 
`!/NC4        IF (NCTYPE.EQ.4) 
`
so the switch is really just protecting compilation with NetCDFv3.  If I make sure anything that was behind a NC4 is instead behind the "IF (NCTYPE.EQ.4)" would you be okay if we removed the NC4 switch? 
I've started some of this work here: 
https://github.com/JessicaMeixner-NOAA/WW3/tree/feature/removeNC4switch

If it doesn't work/pass regression tests, we can keep the NC4 switch, but I think we're keeping the functionality you want which is the NCTYPE=3 and 4 even removing !/NC4

**Comment by mickaelaccensi** [comment]
it sounds to be a good start. We have to check that some regtests exist with NCTYPE=3 and NCTYPE=4

**Comment by JessicaMeixner-NOAA** [comment]
There are regression tests that use NCTYPE=3 and  others that use NCTYPE=4 (based on my random search making sure we had both, I'd say a vast majority are NCTYPE=3).
