### ISSUE TITLE
zlib version from install_netcdf4_gnu.sh.gz incompatible with X.org on Ubuntu 20.04?

### ISSUE THREAD

**Issue by caiostringari** [NOAA-EMC/WW3#363]
**Describe the bug**

After executing the [netcdf installation script](https://github.com/NOAA-EMC/WW3/wiki/files/install_netcdf4_gnu.sh.gz), Ubuntu 20.04's default zlib is overwritten, the system becomes unstable and after you reboot your graphical interface is gone.

**To Reproduce**

1) Have a working graphical install of Ubuntu 20.04.
2) Install the netcdf libraries with the provided script from the FAQ.
3) Reboot and you going to be stuck in a black screen.
4) Login to a different tty (ctrl+alt+f4),
5) try to re-start X: `startx`
6) You are going to see this error: /usr/local/lib/libz.so.1: version `ZLIB_1.2.9' not found

How to fix:
Download libz1.2.9, compile, install it. 

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**

This is not really a WW3 bug.

**Comment by mickaelaccensi** [comment]
Hi Caio,

thanks for this feedback. Anyway I won't recommend to install netcdf libraries from source on ubuntu distribution. There are official repos available through aptitude. This installation is probably recommended only for installation on HPC or specific cases. @aliabdolali could you confirm or explain the context of this installation script ?

**Comment by aliabdolali** [comment]
Hi @Caio and @mickaelaccensi 
I think Michael is right, these scripts are working as long as other dependencies, like zlib, the compiler, ... are also available. 
Michael, could you provide me the link to the "official repos available through aptitude", so I can update our wiki page.

**Comment by mickaelaccensi** [comment]
# prerequisites
apt install  gcc g++ gfortran build-essential
# netcdf4 library
apt install libhdf5-serial-dev libnetcdff-dev libnetcdf-dev
# netcdf tool (ncview, nco)
apt install netcdf-bin netcdf-doc ncview libudunits2-0 libgsl0-dev nco


I also have a very detailed script to install all the netcdf libraries and dependencies depending on the available compiler (gnu, mpt, intel, pgi) that you could share but with no support on it since this task should be done by IT guys on HPC and not ww3 users themselves.

**Comment by aliabdolali** [comment]
@mickaelaccensi Awesome,
Please share your scripts and I'll add a note about "no support on it" as it is not a part of WW3 but as requirements.

**Comment by mickaelaccensi** [comment]
here it is. Once unzipped, it should be a bash script

[install_netcdf.zip](https://github.com/NOAA-EMC/WW3/files/6377831/install_netcdf.zip)

**Comment by aliabdolali** [comment]
@mickaelaccensi thanks for providing the script and aptitude guide. I added them to our wiki page with the note that this is not a part of WW3 distribution and no support is available. 
@caiostringari i hope the guide provided by Mickael was helpful. I am closing the issue now.
