### ISSUE TITLE
how to solve this issue?

### ISSUE THREAD

**Issue by garimss** [NOAA-EMC/WW3#364]
(project1) D:\noaa>git clone https://github.com/garimss/WW3.git
Cloning into 'WW3'...
remote: Enumerating objects: 21241, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 21241 (delta 7), reused 4 (delta 0), pack-reused 21219R
Receiving objects: 100% (21241/21241), 61.01 MiB | 3.76 MiB/s, done.
Resolving deltas: 100% (15728/15728), done.
error: invalid path 'manual/run/aux.tex'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by JessicaMeixner-NOAA** [comment]
@garimss are you cloning on a windows machine?  We use a folder named "aux" and that's a protected name on windows machines.

**Comment by garimss** [comment]
@JessicaMeixner-NOAA  yes I am cloning on windows machine. Is it possible to use on windows or should I move to mac?

**Comment by JessicaMeixner-NOAA** [comment]
@garimss I would recommend moving to your HPC, linux or Mac environment.  I don't know of anyone who's successfully used WW3 on windows. 

I'm going to close this issue, but feel free to reopen if you do not think this issue has been resolved or create a new issue when needed.
