### ISSUE TITLE
"valid_max" incorrect for "latitude" variable in ww3_ounf

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#376]
**Describe the bug**
The `valid_max` attribute for the "latitude" variable in WW3_OUNF is set to `180.0`
I'm fairly sure this is a typo! :)

There are a few instances of this in `ww3_ounf.ftn`, for example:
https://github.com/NOAA-EMC/WW3/blob/9708edcb3641a34019f03274ebe1d4b8758ad8b8/model/ftn/ww3_ounf.ftn#L3555

**To Reproduce**
Run ww3_ounf for any grid and ncdump output file.

**Expected behavior**
`valid_max` should be 90.0

**Comment by ukmo-ccbunney** [comment]
@aliabdolali Do we want to sneak a fix for this into my PR #305 before you merge?

**Comment by aliabdolali** [comment]
@ukmo-ccbunney that's quite relevant and does not change answers as we do not have lat>90 :), so please do it.

**Comment by ukmo-ccbunney** [comment]
Fixed in #305
