### ISSUE TITLE
OASIS send condition

### ISSUE THREAD

**Issue by ukmo-juan-castillo** [NOAA-EMC/WW3#390]
**Describe the bug**
When running a coupled configuration, there is a series of conditions that have to be fulfilled before calling the oasis_send routine. One of this conditions is problematic, as when the run length is three days or more this condition is not fulfilled when it should. Such condition is:

MOD(ID_OASIS_TIME/DTOUT(7),1.0)

**To Reproduce**
Any coupled configuration sending information from the wave to other model via coupling running for three days or longer.

**Expected behavior**
The run crashes with an OASIS error after more than two days saying that the order of coupling is not fulfilled, as one call to oasis_send has been skipped.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by mickaelaccensi** [comment]
Hi Juan,
this condition is important to avoid approximation errors. could you explain more in detail why you want to change it to (MOD(ID_OASIS_TIME,NINT(DTOUT(7))) .EQ. 0

**Comment by ukmo-juan-castillo** [comment]
I precisely had issues with approximation errors using the original condition. This only happened to me when I run one of our operational configurations which runs the model continuously for three days. Just before the third day finished, at ID_OASIS_TIME = 234000 and DTOUT(7) = 3600., the condition for sending coupling fields was incorrectly not satisfied, but the condition for receiving was. The result of this send condition was MOD(ID_OASIS_TIME/DTOUT(7),1.0) = 0.9997...., so it was clearly not satisfied, might be something to do with the MOD operation for a division of an integer and real number.

Please notice that the send and receive conditions are not the same, what I did in this branch was making them the same, choosing the one that looked better (and that works as it is supposed to do). I see sensible to make the test depending on integer numbers rather than in the precision of a real number.

**Comment by mickaelaccensi** [comment]
ok thanks for the explanation. could you add in the PR that you changed the condition for send to be consistent with the condition for receive
