### ISSUE TITLE
rename model/aux

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#393]
Cloning WW3 to Windows machines is not possible as aux is a protected name.
This folder contains preprocessing tools (nml conversion/switch tools), so we would like to rename this folder to:
_tools_
or
_preproc_
What is your preferred name?
@JessicaMeixner-NOAA @thesser1 @ukmo-ccbunney @mickaelaccensi

**Comment by JessicaMeixner-NOAA** [comment]
Either tools or preproc is fine with me.

**Comment by mickaelaccensi** [comment]
I prefer tools to keep the possibility to add other extra tools (python, ...) in this directory which are not necessarily for preprocessing
