### ISSUE TITLE
Basics issues with WW3 - Installation - How could i get started?

### ISSUE THREAD

**Issue by gabriel-aig** [NOAA-EMC/WW3#404]
Hello!

I just started using WW3 and the github. I entered in a Scientific Iniciation at my college and i really don't know how to get started using this model. I'm having problems to install the software at my Linux Ubuntu. It's a simple problem, but i didn't find anything to help me on the internet, just this site. I need to learn how to use the WW3 to start my researches about ocean-atmosphere interection. 
By the way, I'm Gabriel Almeida an Oceanography stutend from Universidade do Estado do Rio de Janeiro - Brazil. 

Thank you all

**Comment by JessicaMeixner-NOAA** [comment]
I would start with looking at these two wiki pages: 
https://github.com/NOAA-EMC/WW3/wiki/WAVEWATCH-III-User-Guide
and 
https://github.com/NOAA-EMC/WW3/wiki/Quick-Start-for-Users

**Comment by JessicaMeixner-NOAA** [comment]
@gabriel-aig I am going to close this issue for now. Please re-open or start a new issue if you have additional questions!
