### ISSUE TITLE
ww3_prnc for tidal analysis crashed with gnu compiler

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#407]
**Describe the bug**
gnu compiler detect some bad points related to fillvalue which are not correctly read 

**To Reproduce**
running regtest ww3_tp2.18 with gnu compiler

**Expected behavior**
with intel or mpt, the fillvalue value is kept from a previous step when reading input file attribute whereas with gnu compiler the value is initiliazed to a crazy value (due to a typo in the code)

**Comment by aliabdolali** [comment]
@mickaelaccensi can we close this?
