### ISSUE TITLE
Syntax error in cmplr.env (missing || operator)

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#415]
Line 163 of `cmplr.env` is missing a logical OR (`||`) operator on the end of the line:

https://github.com/NOAA-EMC/WW3/blob/9f76dd380270ed58a1cfcbd448225542d4472541/model/bin/cmplr.env#L162-L164

I should look like this:
```
     [ "$cmplr" == "wcoss_cray" ] || [ "$cmplr" == "wcoss_dell_p3" ] || [ "$cmplr" == "cheyenne.intel" ] || \
     [ "$cmplr" == "gaea.intel" ] || [ "$cmplr" == "jet.intel" ] || [ "$cmplr" == "wcoss2" ]  ||  \
     [ "$cmplr" == "stampede.intel" ]; then
```

**Comment by ukmo-ccbunney** [comment]
@aliabdolali  - would you like me to add a fix for this issue in my existing PR (which modifies cmplr.env): ukmo-waves/WW3/pull/21 ?

**Comment by aliabdolali** [comment]
@ukmo-ccbunney sure, I fixed it in one of my PRs, but your PR goes first, so please go ahead and fix it.
