### ISSUE TITLE
WAVEWATCH III Developers meeting, Wed June 5th 2019 10:30am

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#42]
Hello WAVEWATCH III Developers,

Wednesday is out first bi-monthly WAVEWATCH III Developers meeting since the transition to GitHub. The focus of this meeting will be on the transition to GitHub itself, a description of our new authoritative and trusted repositories, new milestones for v7, and recent developments. 

Highlights also include the presentation "Met Office WAVEWATCH III profiling and scale-ability activities" by Dr Andrew Saulter (UKMO), and an open forum where developers can discuss items of interest.

When: Wednesday, June 5th 2019, 10:30am EDT

Presentation material will be posted via google hangouts:
https://meet.google.com/egi-wopu-sqn

For audio, we will use the teleconference line: 1-877-953-0315
Passcode: 1262920# 

Let's go modeling!

Henrique,

For the WAVEWATCH III Development Group

@12cm103
@ajhenrique
@aliabdolali
@bauj0001
@brandaodeco
@breichl
@CarstenHansen
@Clarenburg
@emezac63
@erdc
@FCOO
@flampouris
@hellais
@hkershaw-brown
@huangynj
@j-gonzalezlopez
@jessicaborgesp
@JessicaMeixner-NOAA
@JoaoGRRodrigues
@lileipku00
@mickaelaccensi
@randobucci
@rickyspaceguy
@sahammhd
@seglion
@tiagofaro
@tomdurrant
@ukmo-ccbunney
@ukmo-waves
@umr-lops
@AndresSepulveda
@wavespotter
@XianwuXue-NOAA
@xuexianwu
@yuemaaa
@yuwana1989
@zhongtouwang2019

**Comment by ajhenrique** [comment]
Thanks to all who joined the meeting this week. In attachment please find the slides from the two presentations. I will be sending out an announcement soon with the date of our next meeting. Have a great weekend!

[opening_ww3developers.pdf](https://github.com/NOAA-EMC/WW3/files/3265964/opening_ww3developers.pdf)
[waves_MetOffice_NextGenProject_20190605.pdf](https://github.com/NOAA-EMC/WW3/files/3265965/waves_MetOffice_NextGenProject_20190605.pdf)

**Comment by hellais** [comment]
I could not manage to join the call, but I appreciate sharing the slides.

Will see if I can join the next one!
