### ISSUE TITLE
clean up .cvsignore files

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#421]
**Describe the bug**
In the ww3_tp2.14/input file, there are .cvsignore files which should be removed or converted to .gitignore 

@mickaelaccensi

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi should we remove these or change these to .gitignore?

**Comment by mickaelaccensi** [comment]
i've corrected it in coming PR (added in gitignore)

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi I think this was actually fixed in your last PR, can we close this issue now?
