### ISSUE TITLE
Syntax error in w3gridmd.ftn with PGI 19.10 compiler

### ISSUE THREAD

**Issue by sbrus89** [NOAA-EMC/WW3#422]
**Describe the bug**
Syntax error with PGI 19.10 in a `w3gridmd.ftn` format statement:

https://github.com/NOAA-EMC/WW3/blob/3740ba99caaa2822b5098bf32faeaf199a710a51/model/ftn/w3gridmd.ftn#L5969-L5975

The `I02` specifier in line 5975 should be `I2` to avoid the problem

**To Reproduce**
Run `./w3_grid ww3_grid` with PGI 19.10

**Comment by aliabdolali** [comment]
@sbrus89 would you like to put it in a PR?

**Comment by sbrus89** [comment]
@aliabdolali, of course.
