### ISSUE TITLE
Update wiki page with known not b4b regtests 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#423]
**Describe the section in the documentation that is missing or requires an update?**

On the wiki page here: https://github.com/NOAA-EMC/WW3/wiki/How-to-use-matrix.comp-to-compare-regtests-with-master#4-look-at-results there is a list of regression tests that are not b4b, however this list has changed since this was written.  An updated list would be helpful to keep track of what is expected to not compare when running matrix.comp

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA I just updated the list. Last week and with PRTIDE commit, I removed the ww3_tp2.18. Hopefully, the ww3_tp2.15 will be removed from the list after UKMET staging PR.

@ukmo-ccbunney @thesser1 @mickaelaccensi please let me know if you have additional non-b4b tests, specific on your hpc or with a specific compiler, so we can update the list and close this isse.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali I just ran the regtests from develop twice and this is the list of not b4b tests: 

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (6 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (8 files differ)
mww3_test_04/./work_PR3_UQ_f                     (1 files differ)
mww3_test_04/./work_PR3_UQ_g                     (1 files differ)
mww3_test_04/./work_PR3_UQ_a                     (1 files differ)
mww3_test_04/./work_PR3_UQ_MPI_NC_b_c                     (1 files differ)
mww3_test_04/./work_PR3_UQ_a_c                     (1 files differ)
mww3_test_04/./work_PR2_UQ_f                     (1 files differ)
mww3_test_04/./work_PR2_UQ_b                     (1 files differ)
mww3_test_04/./work_PR2_UQ_g                     (1 files differ)
mww3_test_04/./work_PR2_UQ_a                     (1 files differ)
mww3_test_04/./work_PR3_UQ_b                     (1 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (4 files differ)
ww3_tp2.15/./work_5km                     (1 files differ)
ww3_tp2.15/./work_MPI_5km                     (1 files differ)
ww3_tp2.17/./work_mc1                     (0 files differ)
ww3_ufs1.1/./work_b                     (0 files differ)
ww3_ufs1.2/./work_b                     (0 files differ)

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA I did the same test and here is my list:

**********************************************************************
********************* non-identical cases ****************************
**********************************************************************
mww3_test_03/./work_PR2_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR2_UNO_MPI_d2                     (7 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2_c                     (8 files differ)
mww3_test_03/./work_PR3_UQ_MPI_d2                     (9 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2_c                     (6 files differ)
mww3_test_03/./work_PR1_MPI_d2                     (10 files differ)
mww3_test_03/./work_PR3_UNO_MPI_d2                     (8 files differ)
mww3_test_07/./work_PR3_UQ                     (3 files differ)
ww3_tp2.10/./work_MPI_OMPH                     (5 files differ)
ww3_tp2.15/./work_5km                     (1 files differ)
ww3_tp2.15/./work_MPI_5km                     (1 files differ)
ww3_ufs1.1/./work_b                     (0 files differ)
ww3_ufs1.2/./work_anores                     (directory not found)
ww3_ufs1.2/./work_b                     (0 files differ)

note that **0 files differ** for **ww3_ufs1.1** and **ww3_ufs1.2**
We need to fix matrix.comp to not report them as different.

Could you check what files differ in **mww3_test_04**? from your comment, there is **1** different file.
