### ISSUE TITLE
[ww3_ounf] NetCDF compression sometimes not applied when using SMC grids

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#429]
**Describe the bug**
When using outputting netCDF NC4 files using `ww3_ounf` on an SMC grid the netCDF compression is not applied when creating variables in a new file.

**To Reproduce**
Run `ww3_ounf` on an SMC grid with NC4 switch.

**Expected behavior**
Some output variables will not have compression applied (you can verify this using `ncdump -h -s`

**Proposed fix**
Move `NF90_DEF_VAR_DEFLATE` statement on line 2423 and 2438 outside the `IF-ELSE-ENDIF` block so it is applied for both SMC and regular grids:

 https://github.com/NOAA-EMC/WW3/blob/3c4732490b8d1d4e1ca2af81e71d8cd30c1de950/model/ftn/ww3_ounf.ftn#L2411-L2425

**Comment by JessicaMeixner-NOAA** [comment]
This might be simpler to fix with/after PR https://github.com/NOAA-EMC/WW3/pull/411 
where the NC4 switch goes away and previously anything that had NC4 is modified to only have a "IF (NCTYPE.EQ.4)"

**Comment by ukmo-ccbunney** [comment]
@JessicaMeixner-NOAA Good point - and agreed. I'll wait until that PR has been merged.

**Comment by ukmo-ccbunney** [comment]
#436 raised as draft PR for now - can update after #411 if necessary.
