### ISSUE TITLE
[ww3_ounf] RTD pole information being generated for non-rotated pole grids

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#430]
**Describe the bug**
If a model is compiled with the `RTD` switch but is formulated on a standard pole* the `ww3_ounf` program incorrectly generates extra `standard_latitude` and `standard_longitude` variables.

_* e.g. for generation of rotated pole boundary conditions from standard pole model_

**To Reproduce**
Steps to reproduce the behaviour:
Run a model on a standard grid, but compile with the `RTD` switch

**Expected behaviour**
The `standard_latitude` and `standard_longitude` variables should not be genereted.
Additionally, the following attributes for `latitude` and `longitude` are incorrect:
```
longitude:long_name = "longitude in rotated pole grid" ;
longitude:standard_name = "grid_longitude" ;
```

They should be simply (similarly for latitude):
```
longitude:long_name = "longitude" ;
longitude:standard_name = "longitude" ;
```

**Comment by ukmo-ccbunney** [comment]
@aliabdolali Would you like me to add this fix to the UKMO staging_may2021 branch?

**Comment by aliabdolali** [comment]
@ukmo-ccbunney yes, please. We need to fix the problem and do the final test for the staging and merge it. I Hope Juan will fix the problems and then we are good to go.
