### ISSUE TITLE
The corner coordinates are not reproducible due to the R8 -> R4 conversion

### ISSUE THREAD

**Issue by uturuncoglu** [NOAA-EMC/WW3#434]
**Describe the bug**
The recent testing of CMEPS PR (https://github.com/ESCOMP/CMEPS/pull/216) under HAFS application revealed that the `MED_wav_area` field in mediator history file is not reproducible. The three-component configuration of HAFS application works fine and there is no answer change but this particular value is reported as changed with the CESM `cprnc` tool. There is no answer change because currently we are not using conservative type Regridding between atmosphere and wave components but this could be a issue when conservative type interpolation is used between them. 

The issue might be resolved by following approaches:
1. Force WW3 cap to use R8 rather than R4.
2. Create R4 version of the _GET\_SCRIP\_INFO\_STRUCTURED ()_ call - https://github.com/NOAA-EMC/WW3/blob/1f128e68372637d18e5d017b89d262aad55373c4/model/ftn/wmscrpmd.ftn#L863
3. Use appropriate type conversion in the WW3 cap to be sure that there is no answer change such as using _real()_ function provided by the Fortran itself. This needs to be implemented in two different place in the WW3 cap,
https://github.com/NOAA-EMC/WW3/blob/1f128e68372637d18e5d017b89d262aad55373c4/model/ftn/wmesmfmd.ftn#L3082
https://github.com/NOAA-EMC/WW3/blob/1f128e68372637d18e5d017b89d262aad55373c4/model/ftn/wmesmfmd.ftn#L3519

Currently, i am testing approach (3) first since it is very easy to implement and if that works I'll create very small fix PR for it.

**To Reproduce**
Steps to reproduce the behavior: Since the WW3 is coupled with CMEPs only under HAFS application at this point. Running three component configuration twice and comparing the `MED_wav_area` will reveal the issue. The HAFS workflow is able to run three component configuration at this point. So, it would be easy to reproduce the issue.

**Expected behavior**
There is a slight change in the `MED_wav_area` variable but there is no answer change.

```
MED_wav_area   (MED_wav_nx,MED_wav_ny,time)  t_index =      1     1
        167   397341  (     0,     9,     1) (     0,     1,     2) (     0,   223,     1) (    81,   441,     1)
              397341   6.084841554444137E+00   0.000000000000000E+00 5.5E+00  2.768168675503156E-01 2.6E-04  4.309843238733993E+00
              397341   6.084841554444137E+00   0.000000000000000E+00          5.818140359473252E+00          0.000000000000000E+00
              397341  (     0,     9,     1) (    81,   441,     1)
          avg abs field values:                      NaN    rms diff:     NaN   avg rel diff(npos):  2.6E-04
                                                     NaN                        avg decimal digits(ndif):  1.2 worst:  0.0
 RMS MED_wav_area                            NaN            NORMALIZED  0.0000E+00
```

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I'll let you know about the fix soon.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I tried to put real() conversion explicitly in the assignment part in the WW3 cap as following,

```
       ! Fill coordinates
       do iy = elb(2),eub(2)
         do ix = elb(1),eub(1)
           irec = (iy-1)*grid_dims(1)+ix
           rptrx(ix,iy) = real(xgrd_corner(1,irec))
           rptry(ix,iy) = real(ygrd_corner(1,irec))
         enddo
       enddo
```

but it does not help. 

Maybe the issue is in CMEPS because all the data that are written to mediator history is in double type. So, even if the coordinates in WW3 cap is R4 and use real() function to convert it from R8 to R4, the data pointer used in CMEPS side for area (extracted from the field returned from ESMF_FieldRegridGetArea call) is R8 and this could create a inconsistency in terms of the data type used in different sides of the modeling system (i.e. component vs. mediator). The easy fix or test would be to force WW3 cap run in R8 but as I know it is not an easy process. At this point I just wonder that can we test the cap in R8 mode. Let me know what do you think?

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I started working on this again. Here is the update about the steps that code follows. So, my plan is to look at each steps to see what is going on.

1. WW3 cap is working in R4 mode and the corner coordinates are converted from R8 to R4 in there. I think using real() function is fine to explicitly convert from R4 to R8 but this does not help. In any case we could add following to the cap.

`rptrx(ix,iy) = real(xgrd_corner(1,irec), kind=ESMF_KIND_RX)`

2. The area in CMEPS side is returned by the ESMF_FieldRegridGetArea(). Since we are not adding area explicitly in the WW3 cap, I think the ESMF call returns the area which is calculated internally. You could find the call in here,

https://github.com/esmf-org/esmf/blob/b4c535d3b3925f43ccad78191f40d6c51f6f2e7e/src/Infrastructure/Field/src/ESMF_FieldRegrid.F90#L2492

You could see that there is an explicit check for R8 in this call and it seems this routine only supports R8. This is fine because this is called by the CMEPS and the the used field in there has R8 type kind (I think).

https://github.com/ESCOMP/CMEPS/blob/307d2bee5f98e09041eb0fa229a5a8c304c89564/mediator/med.F90#L2615

The ESMF call, gets the grid attached to the field and convert it to mesh and then call ESMF_MeshGetElemArea(), so I think converting mesh also calculates the area in the background

https://github.com/esmf-org/esmf/blob/b4c535d3b3925f43ccad78191f40d6c51f6f2e7e/src/Infrastructure/Field/src/ESMF_FieldRegrid.F90#L2658

Then it returns this area to CMEPS. At this point, I am not sure what is going on inside of mesh conversion. I need to check it.

3. CMEPS uses R8 in everywhere and once it gets the grid area from the field using call in **Step 2** it uses R8 pointer and then it writes to the file. Basically the field returned by the ESMF_FieldRegridGetArea() needs to be R4 since WW3 cap performs on R4 mode but I think area calculation in ESMF side is in R8. So maybe there is something going on when ESMF when it is using R4 coordinates to calculate R8 area.

There is no answer change in the three component HAFS configuration and only area field in the mediator history file has the issue.

**Comment by JessicaMeixner-NOAA** [comment]
@uturuncoglu  I haven't had time to look into this in depth.  Based on your last comments I have two questions though: 
1. If we calculated the areas and sent them, would it solve the issue or is it better for CMEPS to calculate the areas? 
2. Instead of converting the R8 to R4 in the ESMF cap for WW3 explicitly, should we explicitly set those corner values to be R8  and stay at R8 or do we need to make this work with the R4 values?

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA Calculating areas explicitly might help to solve this issue I was looking into the WW3 code and there are some code in the SCRIP part such as `SCRIP_GridComputeArea()` call could help but I am not sure. 

I am not sure having R4 for center coordinates and R8 for corner in ESMF side. It might be possible. Let me try. I'll update you about it.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA it seems that the items in ESMF_Grid is in same type and it is not possible to use R4 for some part and R8 for another part. At least the API is designed like that. I could ask to Gerhard or Bob to get more information. One other thing that we could try is to push the WW3 grid part be R8. So, all those information can be consistent by this way. I think fields could still be R4. Anyway, I need to check couple of things before trying to make WW3 grid R8.

**Comment by JessicaMeixner-NOAA** [comment]
@uturuncoglu sounds good

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA Following tests are done to track the source of the issue. Here is the details,

**1.** `ESMF_FieldWrite()` is used to write field to disk just after `ESMFRegridGetArea()` call to eliminate possible R4->R8 conversion issue in mediator history phase. The two consecutive run showed that the area field for WW3 is different (other components are just fine - FV3 and HYCOM and both of them uses R8 in the cap). 
**2.** Tried to force WW3 cap to use R8 rather than R4 by keeping `#if defined(ESMF_R8)` section and comment out the part for R4. The model runs without any issue and now I could get same answer for WW3 area between two consecutive run. Also, note that in this case all the exchnage variables are also R8. We could isolate the changes to keep only R8 in grid definition and related fields but R4 for the rest.

It seems forcing cap to R8 is working. I just wonder what if we add grid area to the WW3 grid explicitly. Do you think that it is possible? Another test that I am trying is to create simple reproducer in ESMF side. If I could reproduce it then it proves that issue in ESMF side. At this point I am just creating grid with R4 and using same approach to get area (grid->mesh->pull area).

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I might fix the issue and I am performing couple of more test to be sure. I found an issue in the `ESMF_GridAddCoord()` call that is used to add corner coordinates. That was adding one more extra row and column to the corner coordinates and those extra region has no corresponding data in the data returned by the script call to calculate the corner coordinates. The dimension returning from ESMF call is 902x442 but scrip call returns 901x441. So. basically we need to add `staggerEdgeUWidth=(/0,0/)` to the `ESMF_GridAddCoord()` calls that include corner to WW3 import and export grids. This fixed the dimension issue and now I could get 901x441 as a dimension from ESMF pointers. If the tests go fine, I'll create very minor PR in WW3 to fix the issue.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA It turns out that we could not use `staggerEdgeUWidth=(/0,0/)` at this moment because it triggers another issue in the coupling like following,

```
20210728 170500.392 ERROR            PET1302 ESMCI_Array.C:6141 ESMCI::Array::tRedistStore() Invalid argument  - srcArray and dstArray must provide identical number of exclusive elements
20210728 170500.392 ERROR            PET1302 ESMCI_Array.C:5921 ESMCI::Array::redistStore() Invalid argument  - Internal subroutine call returned Error
20210728 170500.392 ERROR            PET1302 ESMCI_ArrayBundle.C:1010 ESMCI::ArrayBundle::redistStore( Invalid argument  - Internal subroutine call returned Error
20210728 170500.392 ERROR            PET1302 ESMCI_ArrayBundle_F.C:497 c_esmc_arraybundlerediststorenf( Invalid argument  - Internal subroutine call returned Error
20210728 170500.392 ERROR            PET1302 ESMF_ArrayBundle.F90:2530 ESMF_ArrayBundleRedistStoreNF() Invalid argument  - Internal subroutine call returned Error
20210728 170500.392 ERROR            PET1302 ESMF_FieldBundle.F90:15183 ESMF_FieldBundleRedistStoreNF Invalid argument  - Internal subroutine call returned Error
20210728 170500.392 ERROR            PET1302 WAV-TO-MED:src/addon/NUOPC/src/NUOPC_Connector.F90:7968 Invalid argument  - Passing error in return code
20210728 170500.392 ERROR            PET1302 WAV-TO-MED:src/addon/NUOPC/src/NUOPC_Connector.F90:5314 Invalid argument  - Passing error in return code
20210728 170500.392 ERROR            PET1302 EARTH Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:2723 Invalid argument  - Phase 'IPDv05p6b' Initialize for connectorComp 3 -> 4: WAV-TO-MED did not return ESMF_SUCCESS
20210728 170500.392 ERROR            PET1302 EARTH Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:1946 Invalid argument  - Passing error in return code
20210728 170500.392 ERROR            PET1302 EARTH Grid Comp:src/addon/NUOPC/src/NUOPC_Driver.F90:469 Invalid argument  - Passing error in return code
20210728 170500.392 ERROR            PET1302 MAIN_NEMS.F90:429 Invalid argument  - Aborting NEMS
```

Anyway, I implement another approach to solve the issue. In this case, I put the code to the cap that basically calculates the missing data in the corner coordinate (top-most row and right-most column) for both import and export grids. I test it under HAFS and it seems that ESMF calculated area issue is solved. So, I am getting bit-to-bit results in different runs even with the R4 mode. The following plot shows the upper right corner of the WW3 grid and red is the center and white is the corner coordinates. It seems that implemented approach is able to fill the missing data successfully. 

![Screen Shot 2021-07-29 at 12 20 28 AM](https://user-images.githubusercontent.com/1228999/127604050-7f160d9f-c60c-4b15-a419-02caed27baca.png)

Anyway, i am plaining to create draft PR in WW3 side and run all wave related regression tests to be sure that this new fix does not break anything in existing configurations.

**Comment by uturuncoglu** [comment]
@JessicaMeixner-NOAA I created draft PR - https://github.com/NOAA-EMC/WW3/pull/438 So, I'll initially run RTs and update the PR description. In the meantime, if you have time, please look at it to the changes and let me know if you need any change.

**Comment by JessicaMeixner-NOAA** [comment]
@uturuncoglu from your description this all seems like great news! I won't have time to look in detail at the code today, but will plan on doing that on Monday.
