### ISSUE TITLE
Change file name  "manual/run/aux.tex"

### ISSUE THREAD

**Issue by XiaqiongZhou-NOAA** [NOAA-EMC/WW3#435]
**Is your feature request related to a problem? Please describe.**
Windows 10 does not allow to clone the repository that has the file name with 'aux'.
 I got the error message in the windows OS when trying to checkout WW3:
"error: invalid path 'manual/run/aux.tex'"

**Describe the solution you'd like**
Can you change 'aux' to others?

**Comment by aliabdolali** [comment]
It is already changed to manual/run/sup.tex. Are you cloning the development branch?

**Comment by XiaqiongZhou-NOAA** [comment]
OK, I am checking out the version as the UFS's submodule.

**Comment by aliabdolali** [comment]
it is not sycnced with ufs-weather-model. so if you want to check it, you can either clone it from noaa-emc/ww3 repo or clone the PR 620 which is in the queue to be integrated to ufs-weather-model
https://github.com/ufs-community/ufs-weather-model/pull/620

**Comment by aliabdolali** [comment]
@XiaqiongZhou-NOAA the fix is now in ufs-weather-model.
