### ISSUE TITLE
Regtest tp2.17 failing to compile since #350

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#443]
**Describe the bug**
The ww3_tp2.17 regtest is failing since PR #350 due to an unknown intrinsic KNINT in ww3_grib.ftn.
#350 added ww3_grib.inp files to ww3_tp2.17 and these are being compiled with the NCEP2 switch.
The NCEP2 switch enables lines in ww3_grib.ftn that call the intrinsic KNINT, which is an unknown intrinsic.

**To Reproduce**
Run one of the tp2.17 regression tests, e.g.:
./bin/run_test -c ukmo_cray_gnu -S -s MPI -s NO_PDLIB -w work_a -g a -f -p mpiexec -n 16  -o all ../model ww3_tp2.17

**Expected behavior**
It fails when using the GNU compiler with `Error: Function 'knint' at (1) has no IMPLICIT type`

Interestingly, it DOES compile ok with the CrayFtn compiler, so is KINIT a non-standard extension? I have not managed to fine any reference to it online...

**Comment by JessicaMeixner-NOAA** [comment]
is this still an issue?

**Comment by ukmo-ccbunney** [comment]
@JessicaMeixner-NOAA - yes, the KNINT instrinsics are still in the ww3_grid.F90 code.
I think it is an Intel extension, perhaps? I eventually found this reference to it: https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/m-to-n/nint.html

It looks like KNINT returns an INT(8) as the result (instead of an INT(4)).

I wonder if we can use the more commonly available NINT instead with an optional KIND parameter:
```
RESULT = NINT(A [, KIND])
```

I will run some tests.

**Comment by JessicaMeixner-NOAA** [comment]
Is this closed or is this still an issue?  I did look for KNINT in all of WW3 but only saw it in ww3_grib, not ww3_grid.

**Comment by ukmo-ccbunney** [comment]
> Is this closed or is this still an issue? I did look for KNINT in all of WW3 but only saw it in ww3_grib, not ww3_grid.

Apologies - that was a typo: I meant ww3_grib, not ww3_grid.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks Chris, I just wanted to make sure!
