### ISSUE TITLE
Port to WCOSS2 for GEFSv12

### ISSUE THREAD

**Issue by XianwuXue-NOAA** [NOAA-EMC/WW3#445]
Port WW3 for GEFSv12 to Acorn/WCOSS2

**Comment by JessicaMeixner-NOAA** [comment]
@XianwuXue-NOAA will you be working on this or do you need help from me and/or @aliabdolali ? 

Do you know what modules will be used?

**Comment by XianwuXue-NOAA** [comment]
@JessicaMeixner-NOAA Thanks a lot. Currently, I can compile WW3 got get "WW3/model/obj_HYB/libww3_multi_esmf.a" and ten exe files on Acorn, however, please review my changes to see whether I did the proper changes. Currently, I encountered an issue when I try to compile FV3. "atmos_model.F90(336): error #8178: The procedure pointer and the procedure target must have matching arguments."

BTW, 1) for ESMF_F90ESMFLINKLIBS, I didn't use it because it is set "ESMF_F90ESMFLINKLIBS =-lesmf  -lfabric  -lmpifort_intel -cxxlib -lrt -ldl -lnetcdff -lnetcdf", but there is error "can not find fabric and mpifort_intel", I remote these two libs in "model/esmf/Makefile"; 2) I change fortran and gcc to ftn as requested on WCOSS2.

**Comment by XianwuXue-NOAA** [comment]
BTW, my work directory is located in "/lfs/h1/emc/ens/noscrub/Xianwu.Xue/gw/gw_feature_gefs_v12_github_port2acorn/sorc/fv3gfs.fd/WW3"

**Comment by JessicaMeixner-NOAA** [comment]
@XianwuXue-NOAA let me know when you've pushed the changes to a branch on GitHub or I'll see a PR come in to the production/GEFS.v12 branch.  Seems like you are working on this so I'll go ahead and assign the issue to you.

**Comment by XianwuXue-NOAA** [comment]
Thanks @JessicaMeixner-NOAA
