### ISSUE TITLE
linking error while processing ww3_prtide (compiling) 

### ISSUE THREAD

**Issue by DiegoGutierrez2210** [NOAA-EMC/WW3#449]
Hi everyone

I have this error and I think that It is a bug error, but I'm not sure: 
****Processing ww3_prtide
**---------------------**
ad3 : processing ww3_prtide 
      Linking ww3_prtide
      *** error in linking ***
 w3src6md.o: En la función `lfactor':
/home/dgeo/WW3/tmp/w3src6md.F90:761: referencia a `__w3wdatmd_MOD_time' sin definir
/home/dgeo/WW3/tmp/w3src6md.F90:761: referencia a `__w3wdatmd_MOD_time' sin definir
collect2: error: ld devolvió el estado de salida 1
 
make: *** [/home/dgeo/WW3/exe/ww3_prtide] Error 1****

Any idea about this? 

Regards

**Comment by Josue9740** [comment]
Hi @DiegoGutierrez2210. Did you manage to solve this problem? I have a similar one but when linking ww3_grib.

Regards

**Comment by JessicaMeixner-NOAA** [comment]
For the linking issue with ww3_prtide, it looks like __w3wdatmd_MOD_time is not defined and that you've previously compiled the model.  I might suggest doing a clean build and see if you still have issues.

**Comment by JessicaMeixner-NOAA** [comment]
@DiegoGutierrez2210 are you still having issue or can we close this issue?

**Comment by JessicaMeixner-NOAA** [comment]
@DiegoGutierrez2210 I'm going to close this issue, but please reopen if you are still having issues or create a new issue.
