### ISSUE TITLE
Looking for help with ww3_multi.

### ISSUE THREAD

**Issue by famarti** [NOAA-EMC/WW3#456]
Hi everyone,

We're having trouble when the model uses the ww3_multi program. From what we could check in the output, the wave model stops working when the WMINIT subroutine starts. 
The model writes "Initializing wave model..." and then we have a series of errors that we cannot understand why they are due to.
Here are the errors:

 Model number  1 [glob]
          Initializing wave model ...
 w3servmd MPI_ABORT, IEXIT=	     11
 w3servmd UNIT missing
 w3servmd MSG missing
 w3servmd FILE missing
 w3servmd LINE missing
 w3servmd COMM missing
 w3servmd MPI_ABORT, IEXIT=          11
 w3servmd UNIT missing
 w3servmd MSG missing
 w3servmd FILE missing
 w3servmd LINE missing
 w3servmd COMM missing
 w3servmd MPI_ABORT, IEXIT=          11
 w3servmd UNIT missing
 w3servmd MSG missing
 w3servmd FILE missing
 w3servmd LINE missing
 w3servmd COMM missing
 w3servmd MPI_ABORT, IEXIT=          11
 w3servmd UNIT missing
 w3servmd MSG missing
 w3servmd FILE missing
 w3servmd LINE missing
 w3servmd COMM missing

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 9469 RUNNING AT localhost.localdomain
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================

We've been dealing with this error for weeks without being able to solve it, any suggestion on this?

Regards

**Comment by mickaelaccensi** [comment]
Dear Facundo,
Could you please try to reproduce this error with the latest version of ww3 from the develop branch.
Another advice would be to disable the forcing fields (wind, current, ...) to check if the error comes from them.
Which compiler do you use and how have you compiled ww3 ?

**Comment by famarti** [comment]
Thanks for the answer Mickael, and sorry for the delay in my response. We're currently working with the 6.07 version of WW3. ifort was used in the compilation, and we used the following switch for the program ww3_multi:
F90 NCEP2 DIST MPI PR3 UQ LN1 FLX0 ST4 STAB3 NL1 BT1 DB1 MLIM TR0 BS0 XX0 WNX1 WNT1 CRX1 CRT1 IC0 IS0 REF0 O0 O1 O2 O3 O4 O5 O6 O7

We also tried disabling the forcing fields. Originally we tried to use the following: 
WND AST HS FP DP PHS PTP PDIR UST
But we disabled the forcing fields (WND, AST), so in the last attempt we used:
HS FP DP PHS PTP PDIR UST

But the error is quite similar to the previous one:
--------------------------------------------------
       Model number  1 [glob]
          Initializing wave model ...
 w3servmd MPI_ABORT, IEXIT=          13
 w3servmd UNIT missing
 w3servmd MSG missing
 w3servmd FILE missing
 w3servmd LINE missing
 w3servmd COMM missing
 w3servmd MPI_ABORT, IEXIT=          13
 w3servmd UNIT missing
 w3servmd MSG missing
 w3servmd FILE missing
 w3servmd LINE missing
 w3servmd COMM missing

=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 5883 RUNNING AT localhost.localdomain
=   EXIT CODE: 13
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES

**Comment by mickaelaccensi** [comment]
can you provide your ww3_multi.nml (or inp)

**Comment by ukmo-ccbunney** [comment]
Hi @famarti 
Do you have many lines of those error messages?
You might find that there is actually a sensible error message hidden in the middle of it all somewhere.
Try capturing the error output to a file and searching for "WAVEWATCH III ERROR" in the output. Probably there is a problem in your ww3_mutli.inp file.
Chris,.

**Comment by famarti** [comment]
Thanks Mickael and Chris for your answers. Indeed, we have had our suspicions about the ww3_multi.inp. To put this issue in context, we're trying to adapt to version 6.07 an enormous structure of bash/FORTRAN scripts that runs the WW3 model here in Argentina in the 3.14 version. The first step was downloading and compiling the 6.07 version, but then we had to generate new mod_def files, and eventually a new ww3_multi.inp. We believe that this last file, which I copy/paste below, could be the source of the error, and even more now that both of you point it out.

5 1 F 1 F T
gfs F F T T F F F
glob 'no' 'no' gfs gfs 'no' 'no' 'no'  1  1  0.0 1.00  F
aus 'no' 'no' gfs gfs 'no' 'no' 'no'  2  1  0.0 1.0  F
plat 'no' 'no' gfs no 'no' 'no' 'no'  3  1  0.0 1.00  F
lit 'no' 'no' gfs no 'no' 'no' 'no'  4  1  0.0 1.00  F
pam 'no' 'no' gfs no 'no' 'no' 'no'  5  1  0.0 1.00  F
  20210726 180000  20210731 000000
  T T
  20210726 190000  3600  20210731 000000
 N
HS FP DP PHS PTP PDIR
 20210727 000000  21600  20210731 000000
 -42.210 -23.630  31010
 -37.940 -16.000  31260
 -43.140 -22.920  31262
 -40.340 -20.320  31380
 -90.000 -55.000  34002
 150.340 -35.700  55014
 153.680 -28.870  55017
 153.270 -30.370  55018
 152.850 -31.830  55019
 150.190 -37.270  55020
 151.020 -34.470  55022
 151.410 -33.770  55024
 151.320 -33.900  55025
 145.050 -42.180  55026
 153.630 -27.490  55027
 153.270 -26.890  55030
 154.050 -27.830  55035
 152.500 -24.670  55038
 148.180 -38.600  55039
 136.620 -36.070  55040
 141.230 -38.370  55041
 142.780 -38.720  55043
 114.920 -30.300  56004
 115.400 -32.110  56005
 114.770 -33.530  56006
 121.900 -34.000  56010
 117.720 -35.200  56011
 115.570 -32.450  56014
 173.340 -43.760  NZBan
    0.0   0.0  STOPSTRING
     19680606 000000      0  19680606 013000
  20210727 000000  21600  20210728 000000
     19680606 000000      0  19680606 013000
     19680606 000000      0  19680606 013000
  plat  1
  20210726 190000  3600  20210731 000000
 N
HS FP DP PHS PTP PDIR UST
  plat  2
  20210726 190000  3600  20210731 000000
 -47.390 -28.510  31052
 -49.880 -31.570  31053
 -47.270 -27.410  31231
 -45.040 -25.440  31374
 -49.810  -31.520  31375
   -60.0 -49.5   MalvinasNo
   -55.17 -51.67   MalvinasOe
   -64.0 -56.0   FindelMund
   -51.75 -33.75   RioGranSUL
    0.0   0.0  STOPSTRING
  pam  1
  20210726 190000  3600  20210731 000000
 N
HS FP DP PHS PTP PDIR UST
  pam  2
  20210726 190000  3600  20210731 000000
   -60.17 -40.33   Rincon100m
   -56.33 -39.5   MardelPlat
   -54.83 -36.33   RiodelaPla
     0.0   0.0  STOPSTRING
 lit  1
  20210726 190000  3600  20210731 000000
 N
HS FP DP PHS PTP PDIR UST
  lit  2
  20210726 190000  3600  20210731 000000
   -61.33 -42.5   PeninsulaV
   -65.17 -45.67   GolfoSanJo
   -66.5 -50.67   PatagoniaS
     0.0   0.0  STOPSTRING
   the_end  0
   MOV 19680606 000000   5.  90.
   STP

**Comment by ukmo-ccbunney** [comment]
Did you find any error message in your stdout? It might be hidden amongst all the w3servmd error lines...

**Comment by ukmo-ccbunney** [comment]
I wonder - you are defining unified point output (UNIPTS=.TRUE.), but then you request output points for your separate grids later on.

I believe that if you use unified output, you can only define your output points (type 2 output) once at the top level - you cannot then redefine them for individual grids.

Perhaps that is the problem? If so, I imagine there is an error message stating that somewhere in all your output. Search for "WAVEWATCH III ERROR" in your stdout.

**Comment by JessicaMeixner-NOAA** [comment]
@famarti I'm going to close this issue, but feel free to reopen if you are still having issues or create a new issue.
