### ISSUE TITLE
ww3_tr1 bound I/O error

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#457]
**Describe the bug**
when running the regtest ww3_tr1 with ASCII spec boundaries, an I/O error occurs

**To Reproduce**
./bin/run_test -o both -f -S -T -c intel -i input_bndin -w work_bndin ../model ww3_tr1

**Expected behavior**
in ww3_bound.out :
IP, file, I/O error:    1, ../input_bndin/bnd1.spc,     0
IP and spectral dimensions:    1   13   24
IP, file, I/O error:    2, ../input_bndin/bnd2.spc,     0
IP and spectral dimensions:    2   13   24
IP, file, I/O error:    3, ../input_bndin/bnd3.spc,     0

**Comment by ukmo-ccbunney** [comment]
Hi @mickaelaccensi 
I don't think this is actually an error.
The IOSTAT return value is actually 0 - which is ok.
It is just some verbose output (from line 338 of ww3_bound.ftn).

Perhaps the working should be change from "I/O error" to "I/O Stat" to avoid confusion?

Chris.

**Comment by mickaelaccensi** [comment]
true, it would be good to change it to I/O Stat

**Comment by ukmo-ccbunney** [comment]
Are you happy to close this issue then?
