### ISSUE TITLE
ERA5 hourly wind to 

### ISSUE THREAD

**Issue by ahbarzandeh** [NOAA-EMC/WW3#492]
Hi
I'm new to WW3.
I want to input the ERA5 hourly wind data for one point during one months, run a 1D case, and get the wave output at that point.
I tried to modify ww3_ts1 regtest (Source term test, time limited growth) based on my target. First I wrote a MATLAB code [era5toWW3input.m.txt] to convert the ERA5 wind .nc in the text form that I think would be suite for WW3 inp file. [WND.txt]
[era5toWW3input.m.txt](https://github.com/NOAA-EMC/WW3/files/7317106/era5toWW3input.m.txt)
[WND.txt](https://github.com/NOAA-EMC/WW3/files/7317108/WND.txt)
Then I copied the [WND.txt] into the ww3_shel.inp
you can see my input folder:
[input.zip](https://github.com/NOAA-EMC/WW3/files/7317112/input.zip)
I used the run command: ./bin/run_test -c gnu -o netcdf ../model ww3_ts1/
but I got a error:  
*** WAVEWATCH III ERROR IN W3SHEL : ***
     TOO MANY HOMOGENEOUS FIELDS : WND  201
[log.txt](https://github.com/NOAA-EMC/WW3/files/7317115/log.txt)
however I don't want to reduce the number of my wind input.

I would be please if you have any comments and tips to resolve the error. Also, please let me know if you think I should do it in another way or use another regtest. In general, I want to improve my usage of WW3, for my next tasks and projects.

Kind regards,

Amir

**Comment by aliabdolali** [comment]
@ahbarzandeh 
Alternatively, you can you ww3_prep or ww3_prnc (if your input is netcdf) and read the wind from a file.
Also, I noticed your ww3_shel.inp needs some modifications  (i.e. 'STP' at the end). See https://github.com/NOAA-EMC/WW3/blob/develop/model/inp/ww3_shel.inp

**Comment by JessicaMeixner-NOAA** [comment]
@ahbarzandeh are you still having issue or can we close this issue?

**Comment by MatthewMasarik-NOAA** [comment]
Appears to be inactive, closing.  @ahbarzandeh you may re-open anytime.
