### ISSUE TITLE
Divide by zero errors in w3src4md 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#497]
**Describe the bug**
I get divide by zero errors in line https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/w3src4md.ftn#L1562 : 

SQRTCDM1 = MIN(WINDSPEED/USTAR,100.0)

**To Reproduce**
This was encountered when running the coupled ufs-weather-model tests in debug mode.  I believe we are getting to this point because the initial wind field when not using a restart file is zero. 

**Expected behavior**
We should have code protections for possible scenarios of divide by zero so that we can run in debug mode. 

**Suggested Solution**
The current block of [code](https://github.com/NOAA-EMC/WW3/blob/develop/model/ftn/w3src4md.ftn#L1562-L1568) is: 
```
      SQRTCDM1  = MIN(WINDSPEED/USTAR,100.0)
      Z0  = ZZWND*EXP(-KAPPA*SQRTCDM1)
      IF (USTAR.GT.0.001) THEN 
        CHARN = GRAV*Z0/USTAR**2
      ELSE 
        CHARN = AALPHA
        END IF
```
originally I thought a solution could be to instead do: 
```
      IF (USTAR.GT.0.001) THEN 
        CHARN = GRAV*Z0/USTAR**2
        SQRTCDM1  = MIN(WINDSPEED/USTAR,100.0)
        Z0  = ZZWND*EXP(-KAPPA*SQRTCDM1)
        CHARN = GRAV*Z0/USTAR**2
      ELSE 
        CHARN = AALPHA
     END IF
```

However, on second thought, that does not give us a value for Z0 here.  So I guess the question would then be, what do we set Z0 as in this case?

**Comment by JessicaMeixner-NOAA** [comment]
This fix: 
```
+++ b/model/src/w3src4md.F90
@@ -1647,13 +1647,19 @@
 !
 ! Determines roughness length
 !
-      SQRTCDM1  = MIN(WINDSPEED/USTAR,100.0)
-      Z0  = ZZWND*EXP(-KAPPA*SQRTCDM1)
       IF (USTAR.GT.0.001) THEN 
+        SQRTCDM1  = MIN(WINDSPEED/USTAR,100.0)
+        Z0  = ZZWND*EXP(-KAPPA*SQRTCDM1)
         CHARN = GRAV*Z0/USTAR**2
       ELSE 
+        IF (USTAR.GT.0) THEN 
+          SQRTCDM1  = MIN(WINDSPEED/USTAR,100.0)
+          Z0  = ZZWND*EXP(-KAPPA*SQRTCDM1)
+        ELSE 
+          Z0 = AALPHA*0.001*0.001/GRAV 
+        END IF 
         CHARN = AALPHA
-        END IF
+      END IF
 !
       RETURN
```


 had no changes except for the expected not b4b when running regression tests existing regression tests.  Need to confirm it still fixes the debug mode test that discovered this error.

**Comment by ukmo-ccbunney** [comment]
I've applied a fix similar to yours to the same issue that is occuring in the FLX5 module (ref #499) . However, the model still crashes as the USTAR value is used later on (in w3srcemd for example to calculate FHIGH) where a zero value again results in a "divide by zero" error.

Setting a minimum value for USTART (I put 1e-6) avoids this, but I just wanted to double check this is a sensible approach?

**Comment by JessicaMeixner-NOAA** [comment]
Okay, so for the FHIGH divide by zero issue (it's actually for a lot of the physics options).  It's the Max of: 

FHIGH  = MAX( (FFXFM + FAGE ) * MAX(FMEAN1,FMEANWS), FFXPM / USTAR) 

Maybe we just do: 

```
If USTAR>0 then 
   FHIGH  = MAX( calc1 , FFXPM / USTAR) 
else 
  FHIGH = calc1
end 
```

I don't know if a minimum ustar, or just choosing the other makes more sense?  And if we chose a minimum USTAR, what is the best value for that?

(I put calc1 b/c the physics options I think vary the calculation of "calc1").  I'm actually curious how I never ran into that error in my test where I was debugging the other divide by zero, b/c I'm pretty sure ustar=0 along with z0=0.

**Comment by ukmo-ccbunney** [comment]
Seeing as `USTAR` is used quite a few times as a denominator in w3srce and other modules, I wonder if it would be safest to force it to a very small non-zero value?

**Comment by JessicaMeixner-NOAA** [comment]
> Seeing as `USTAR` is used quite a few times as a denominator in w3srce and other modules, I wonder if it would be safest to force it to a very small non-zero value?

Sounds like a very reasonable and practical suggetsion.  What are we thinking if ustar=0 then 1e-8? Or something else?   @mickaelaccensi would you or Fabrice have recommendations for what a small non-zero minimum value of USTART for ST4 physics should be to avoid divide by zeros?

**Comment by mickaelaccensi** [comment]
well, it seems to not be an easy question because USTAR is initialized with different values depending on the part of the code....

looking in w3wdatmd.f90, UST is already initialized at 1e-5
`      WDATAS(IMOD)%UST   (0:NSEATM) = 1.E-5`

then in all w3src*md.F90, USTAR is set to at least 0.0001
`USTAR  = MAX ( 0.0001 , USTAR )`

but in w3srcemd.F90, USTAR is initialized at 0
`USTAR=0.`

and in w3wavemd.F90, it is set to 0.05 for the full array then at some locations at UNDEF where MAPSTA is not 1
`USTAR=0.05`
`UST   (ISEA) = UNDEF`


so for the problem of "divide by zero", it is already handle for U by setting a non-zero value of U if a division by U must be done, here is an example to illustrate it : 
        UNZ    = MAX ( 0.01 , U )
        CD     = (USTAR/UNZ)**2

so I think that we should do the same and set a non-zero value of USTAR before each division operation
USTARNZ  = MAX ( 0.0001 , USTAR )

**Comment by ukmo-ccbunney** [comment]
Thanks @mickaelaccensi - that sounds like a sensible solution. 

@JessicaMeixner-NOAA I will adopt a similar solution to your SRC4 fix above in the w3flx5md module to avoid zero values for Z0. I will also set non-zero values for USTART in w3srcemd to as Mickael suggests to get the `staging/ukmo-oct2021` branch working [#499]

EDIT: Actually, there are a lot of places in the code where USTAR is used as a denominator. Would it not be easier to set the minimum value in the FLX[x] modules where USTAR is calculated? That way we can assume that it will be non-zero in the rest of the code?

**Comment by aliabdolali** [comment]
Looking at variables like UST for i.e. st4, it has different min values to be used as a denominator (0.001, 0.0001, 0.000001). I'd suggest a consistent value at least for each src?
