### ISSUE TITLE
Looking for wind.nc with ww3_tp2.15 in regtests 

### ISSUE THREAD

**Issue by Agoni00** [NOAA-EMC/WW3#498]
In ww3_tp2.15, an input wind field (wind. nc) is needed, but I can't find the wind field file.

regtests/ww3_tp2.15/input/ww3_prnc.inp：

$ -------------------------------------------------------------------- $
$ WAVEWATCH III Field preprocessor input file                          $
$ -------------------------------------------------------------------- $
$ Mayor types of field and time flag
$   Field types  :  ICE   Ice concentrations.
$                   LEV   Water levels.
$                   WND   Winds.
$                   WNS   Winds (including air-sea temp. dif.)
$                   CUR   Currents.
$                   DAT   Data for assimilation.
$
$   Format types :  AI    Transfer field 'as is'. (ITYPE 1)
$                   LL    Field defined on regular longitude-latitude
$                         or Cartesian grid. (ITYPE 2)
$   Format types :  AT    Transfer field 'as is', performs tidal 
$                         analysis on the time series (ITYPE 6)
$                         When using AT, another line should be added
$                         with the choice ot tidal constituents:
$                         ALL or FAST or VFAST or a list: e.g. 'M2 S2'
$
$        - Format type not used for field type 'DAT'.
$
$   Time flag    : If true, time is included in file.
$   Header flag  : If true, header is added to file.
$                  (necessary for reading, FALSE is used only for
$                   incremental generation of a data file.)
$
  'WND' 'LL' T T
$
$ Name of dimensions ------------------------------------------------- $
$
 longitude latitude time
$
$ Variables to use --------------------------------------------------- $
$
  U V
$
$ Additional time input ---------------------------------------------- $
$ If time flag is .FALSE., give time of field in yyyymmdd hhmmss format.
$
$   19680606 053000
$
$ Define data files -------------------------------------------------- $
$ The input line identifies the filename using for the forcing field.
$
  '../input/wind.nc'
$
$ -------------------------------------------------------------------- $
$ End of input file                                                    $
$ -------------------------------------------------------------------- $

**Comment by aliabdolali** [comment]
@Agoni00 
The inputs files are available on ftp server
In your local copy from the top-level directory, run the script:
sh model/bin/ww3_from_ftp.sh
it will download the tar file and put files under regtest/*/input directories automatically.

**Comment by Agoni00** [comment]
@aliabdolali 

Thank you very much for your answer. I have found the NC file. But I have a new problem, when I use ww3_prnc to process the input field of nc file , I get the following warning:
*** WAVEWATCH III WARNING IN W3PRNC：
calendar ATTRIBUTE NOT DEFINED
IT MUST RESPECT STANDARD OR GREGORIAN CALENDAR

How can I resolve this warning?

![1634456017(1)](https://user-images.githubusercontent.com/92639723/137616844-7c77ba90-1289-431b-b61d-7aab0ac36b4b.jpg)

**Comment by aliabdolali** [comment]
@Agoni00 that's a warning and does not affect the test.

**Comment by Agoni00** [comment]
@aliabdolali 
In addition, I have a question about the setting of ww3_grid, one of which is the input boundary point and the excluded point. In regtests, I noticed that this item is not set in some cases, and some are set. I want to know under what conditions this item will be set, and based on what principle to set this item specifically. As shown in the figure, why and what is the significance of this setting?

$ Input boundary points and excluded points -------------------------- $
$    The first line identifies where to get the map data, by unit number
$    IDLA and IDFM, format for formatted read, FROM and filename
$    if FROM = 'PART', then segmented data is read from below, else
$    the data is read from file as with the other inputs (as INTEGER)
$
   10 3 1 '(....)' 'PART' 'mapsta.inp'
$
$ Read the status map from file ( FROM != PART ) --------------------- $
$
$ 3 3 3 3 3 3 3 3 3 3 3 3
$ 3 2 1 1 1 1 0 1 1 1 1 3
$ 3 2 1 1 1 1 0 1 1 1 1 3
$ 3 2 1 1 1 1 0 1 1 1 1 3
$ 3 2 1 1 1 1 0 0 1 1 1 3
$ 3 2 1 1 1 1 1 1 1 1 1 3
$ 3 2 1 1 1 1 1 1 1 1 1 3
$ 3 2 1 1 1 1 1 1 1 1 1 3
$ 3 2 1 1 1 1 1 1 1 1 1 3
$ 3 2 1 1 1 1 1 1 1 1 1 3
$ 3 2 1 1 1 1 1 1 1 1 1 3
$ 3 3 3 3 3 3 3 3 3 3 3 3
$
$ The legend for the input map is :
$
$    0 : Land point.
$    1 : Regular sea point.
$    2 : Active boundary point.
$    3 : Point excluded from grid.
$
$ Input boundary points from segment data ( FROM = PART ) ------------ $
$   An unlimited number of lines identifying points at which input
$   boundary conditions are to be defined. If the actual input data is
$   not defined in the actual wave model run, the initial conditions
$   will be applied as constant boundary conditions. Each line contains:
$     Discrete grid counters (IX,IY) of the active point and a
$     connect flag. If this flag is true, and the present and previous
$     point are on a grid line or diagonal, all intermediate points
$     are also defined as boundary points.
$
      2   2   F
      2  11   T
$

**Comment by aliabdolali** [comment]
@Agoni00 The open boundaries are defined where you want to impose the boundary conditions taken from a larger scale simulation or observations or when you nest grids within multi setups.  
i.e. In order to take into account the effect of swell (long distance generated) in regional scale setup, you need to run the global scale model and extract boundaries at the open boundaries of the regional scale domain.

**Comment by Agoni00** [comment]
@aliabdolali 
In terms of specific settings, for example, what is the meaning and effect of setting 2 2 F 2 11 F?

**Comment by aliabdolali** [comment]
> @aliabdolali In terms of specific settings, for example, what is the meaning and effect of setting 2 2 F 2 11 F?
Hi,
I would recommend you to take a look at the manual and model/inp directory. 
For example, the answer to your question is
https://github.com/NOAA-EMC/WW3/blob/develop/model/inp/ww3_grid.inp#L796-L804
If you could not find the answer or see a certain bug, you can create an issue here and we are more than happy to help.

**Comment by Agoni00** [comment]
@aliabdolali As a matter of fact, I have read this passage many times but have not understood it.I just started to study ww3 by myself, so my question may be simpler and more detailed.

**Comment by JessicaMeixner-NOAA** [comment]
@Agoni00 is this still an active issue or can we close it?

**Comment by MatthewMasarik-NOAA** [comment]
Closing as inactive.  @Agoni00 you are welcome to re-open anytime.
