### ISSUE TITLE
No rule to make target obj/wmscrpmd.o needed by obj/wmesmfmd.o

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/WW3#505]
**Describe the bug**
I'm trying to build WW3 and I'm getting this error: 

```
Processing ww3_multi_esmf
---------------------
No rule to make target obj/wmscrpmd.o needed by obj/wmesmfmd.o
```

Looking at this line:

https://github.com/NOAA-EMC/WW3/blob/dd317947d14e06cb4bc713f53197e194f5e88a65/model/bin/build_utils.sh#L858

Do I need to have `SCRIP` set or something so that wmscrpmd is added to the list of files?

Or should I not be building with ESMF at all?

**To Reproduce**
I run:

```
./model/bin/w3_setup model -c gnu -s NCEP_st4
cd model/bin
./w3_make
```

**Additional context**
Running on macOS using GNU 9.4.0 with the following modules:

```
Currently Loaded Modules:
  1) hpc/1.2.0       3) mpich/3.4.2       5) g2/3.4.3        7) png/1.6.35    9) netcdf/4.7.4  11) w3nco/2.4.1
  2) hpc-gnu/9.4.0   4) hpc-mpich/3.4.2   6) jasper/2.0.25   8) hdf5/1.10.6  10) bacio/2.4.1   12) esmf/8_2_0_beta_snapshot_14-debug
```

**Comment by aliabdolali** [comment]
Hi @kgerheiser 
Here are the steps I took and I was able to compile ww3_multi_esmf

**1) load modules and setenv**

  ```
module purge
  module use /scratch2/NCEPDEV/nwprod/hpc-stack/libs/hpc-stack/modulefiles/stack
  module load hpc/1.1.0
  module load hpc-intel/18.0.5.274
  module load hpc-impi/2018.0.4
  module load netcdf/4.7.4
  module load jasper/2.0.25
  module load zlib/1.2.11
  module load png/1.6.35
  module load hdf5/1.10.6
  module load bacio/2.4.1
  module load g2/3.4.1
  module load w3nco/2.4.1
  module load esmf/8_1_1
  setenv NETCDF_CONFIG $NETCDF_ROOT/bin/nc-config
  setenv METIS_PATH /scratch2/COASTAL/coastal/save/Ali.Abdolali/hpc-stack/parmetis-4.0.3
  setenv JASPER_LIB $JASPER_ROOT/lib64/libjasper.a
  setenv PNG_LIB $PNG_ROOT/lib64/libpng.a
  setenv Z_LIB $ZLIB_ROOT/lib/libz.a
  setenv ESMFMKFILE $ESMF_LIB/esmf.mk

```

**2) setup**
`./model/bin/w3_setup model -c hera.intel -s NCEP_st4`
I modified swtich and added _SCRIP SCRIPNC_
you also can copy _model/esmf/switch_ to _bin_
**3- compile**
```
cd model/bin/
./w3_make ww3_multi_esmf
```

I think setting ESMFMKFILE and adding SCRIPS to the switch is necessary.

**Comment by kgerheiser** [comment]
Is `switch_NCEP_st4` not meant to use ESMF, if `SCRIPS` is not already in `switch_NCEP_st4`? Or should I be running `w3_make ww3_grid`? Just trying to understand the proper workflow here.

**Comment by JessicaMeixner-NOAA** [comment]
@kgerheiser  I'd recommend using the switch file in model/esmf/switch to compile 
./w3_make ww3_multi_esmf

**Comment by JessicaMeixner-NOAA** [comment]
@kgerheiser Actually -- you found a bug that needs to be fixed.  I created an issue about this here: https://github.com/NOAA-EMC/WW3/issues/506
