### ISSUE TITLE
inconsistencies in group/field identifiers for RHO and TAU

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#514]
**Describe the bug**
TAU and RHO have been added in w3iogomd.ftn as group 1, field 9 and 10 but they should be field 11 and 12 as stated in ww3_shel.inp and ww3_shel.nml otherwise the error message from ww3 are not pointing the user to the correct variable.

**Screenshots**
error message from w3iorsmd : 
 *** WAVEWATCH III WARNING IN W3IORS :
     REQUESTED EXTRA RESTART GROUP 1 FIELD 9
     IS NOT PRESENT IN THE RESTART FILE.
     THIS MAY CAUSE INSTABILITIES IN COUPLED CONFIGURATIONS

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi 
TAU and RHO are Fields 8 and 9 respectively in `w3iogomd.F90`. This matches what is in `inp/ww3_shel.inp`
However, the entries in `nml/ww3_shel/nml` show them as fields 11 and 12, which is incorrect as you point out.

I'll raise a small PR to fix this. Thanks!

**Comment by mickaelaccensi** [comment]
I would think that it should be shifted to 11 and 12 otherwise it will make some inconsistencies like in w3iorsmd where field 9 is still linked to ICEF

                  IF ( FLOGRR(1,9) )                                  &
                    WRITE(NDSR,ERR=803,IOSTAT=IERR) ICEF(1:NSEA)

and in 

w3initmd : 

                  IF ( FLOGRR(1,9) )                                  &
                    WRITE(NDSR,ERR=803,IOSTAT=IERR) ICEF(1:NSEA)

**Comment by ukmo-ccbunney** [comment]
Ah - I see. Apologies, I had not spotted that the `ICEF` field was associated with Field=9 in the `w3iordmd` and `w3initmd` modules.

I would suggest modifying those modules so that `ICEF` is Field=11, rather than changing RHOAIR and TAU to be fields 11 and 12.

The reason for this being that RHOAIR and TAU were added as fields 8 and 9 so they didn't interfere with the calculation of the `NOGE` value in w3odatmd (due to the possible inclusion of extra fields due to `BT4` and `IS2` switches):

```
!
! 1) Forcing fields
!
      NOGE(1) = 9
#ifdef W3_BT4
      NOGE(1) = 10
#endif
#ifdef W3_IS2
      NOGE(1) = 12    ! CB
#endif
#ifdef W3_SETUP
    NOGE(1) = 13    ! CB
#endif
!
```

Do you agree?

**Comment by mickaelaccensi** [comment]
that's ok for me, but it may be good to check if it's not called in other subroutines

**Comment by ukmo-ccbunney** [comment]
> that's ok for me, but it may be good to check if it's not called in other subroutines

Agreed! I'll update the PR accordingly.

**Comment by JessicaMeixner-NOAA** [comment]
I already merged your earlier PR (Sorry @mickaelaccensi for not waiting long enough for your comments).  You'll need to make a new PR for the changes and we'll wait for @mickaelaccensi's okay before merging (FYI @aliabdolali )

**Comment by ukmo-ccbunney** [comment]
> I already merged your earlier PR (Sorry @mickaelaccensi for not waiting long enough for your comments). You'll need to make a new PR for the changes and we'll wait for @mickaelaccensi's okay before merging (FYI @aliabdolali )

No worries @JessicaMeixner-NOAA - I'll raise a new PR. The changes in the one you've merged still hold.
