### ISSUE TITLE
Issue when installing NetCDF

### ISSUE THREAD

**Issue by Josue9740** [NOAA-EMC/WW3#524]
Hi! I was following the Quick Start Guide for Users and I found the next error on Step 2 ("Download and expand large/binary/netcdf files"):

After 20 attempts trying to connect to _ftp://polar.ncep.noaa.gov/tempor/ww3ftp/ww3_from_ftp.v6.07.tar.gz_, the time expires and no connection nor download is carried out. I do not really know the possible source for this bug. Can anybody help me? Is there any other way to install NetCDF?

**Previous code:**
git clone -b 6.07.1 https://github.com/NOAA-EMC/WW3
cd WW3

**Code raising the error:** 
sh model/bin/ww3_from_ftp.sh

**Error message**
Connecting to polar.ncep.noaa.gov (polar.ncep.noaa.gov)[140.90.101.132]:21... failed: Connection time expired

**Comment by JessicaMeixner-NOAA** [comment]
@Josue9740 Two suggestions: 
1. Just try again (I just tried this myself and it worked.)
2. Make sure you do not have a firewall blocking from your end. 
Here's just the command to grab the file, if it's easier to do that outside of the script while trouble shooting: 

`wget ftp://polar.ncep.noaa.gov/tempor/ww3ftp/ww3_from_ftp.v6.07.tar.gz`
