### ISSUE TITLE
KNINT is an Intel extension and not portable

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/WW3#531]
**Describe the bug**
The intrinsic routine `knint`, which is a specific routine of `nint`, used in `ww3_grib` is an Intel extension and does not work with GNU compilers.

See: 

https://www.intel.com/content/www/us/en/develop/documentation/fortran-compiler-oneapi-dev-guide-and-reference/top/language-reference/a-to-z-reference/m-to-n/nint.html

`knint` takes a real32 argument and returns an int64.

The generic `nint` should be used instead, which is just the generic form on `knint`. Pretty sure`knint` can simply be replaced with `nint` and the compiler handles the overload automatically. I was able to build with gfortran with this change, but haven't actually tested the output.

**To Reproduce**

Attempt to compile ww3_grib with gfortran

**Expected behavior**
Code should be portable

**Comment by JessicaMeixner-NOAA** [comment]
This issue is related to: #443 as well
