### ISSUE TITLE
Problem when running ww3_grid with version 5.16 of WW3

### ISSUE THREAD

**Issue by emyrizzi11** [NOAA-EMC/WW3#546]
Good afternoon,

I have installed WW3 with mpif90 fortran compiler and gcc for the c compiler. 
The comp and link used for the compilation of the model are comp.gnu_debug and link.gnu_debug (also tried using comp.gnu and link.gnu). 
When trying to run the executable ww3_grid, this error comes up:

At line 202 of file w3triamd.F90 (unit = 90, file = 'emr_cmcc.msh')
Fortran runtime error: Bad integer for item 1 in list input

I have tried to put thr triad switch (TR) to 0, but the error still remains. Did anybody encountered the same problem and knows how to solve it?

Thanks in advance

**Comment by JessicaMeixner-NOAA** [comment]
Did you recompile after setting TR0?

**Comment by emyrizzi11** [comment]
yes already tried it.
At the end I have solved the problem by changing the first line of the .msh file into three integers and not a float and two integers

**Comment by JessicaMeixner-NOAA** [comment]
I'm gong to close the issue has been resolved.  Please re-open this or a new issue if you have additional issues.
