### ISSUE TITLE
ESMF cap error with UFS debug options -init=snan,arrays

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [NOAA-EMC/WW3#552]
**Describe the bug**
When running UFS in debug mode coupled to WW3, if the WW3 compile uses the UFS flags (+ "`-init=snan,arrays`"), then the run will crash during initialization due to a '`floating invalid`' error in the ESMF cap.

**To Reproduce**
* From `ufs-weather-model` select a run with `S2SW` compile and `DDEBUG=ON`.
* In **cmplr.env**:  
  * replace the `optc` assignment to WW3 debug options, with an assignment to the UFS + "-init=snan,arrays" options, i.e.,  `optc="$optc -O0 -check -check noarg_temp_created -check nopointer -warn -warn noerrors -fp-stack-check -fstack-protector-all -fpe0 -debug -ftrapuv -init=snan,arrays"`. (_Fig 1_)
  * Comment out the _optimization_ and _debugging_ blocks accordingly so the debug options will automatically be assigned to `optc`. (_Fig 1_)
  * Bypass a false error during the build of `ww3_grid` where the error checking is tripped by the substring 'error' in the filename `scrip_errormod.F90`, by replacing the `err_pattern` just below the header from `err_pattern='error'` to `err_pattern='[[:space:]]error[[:space:]]'`.  (_Fig 2_) @JessicaMeixner-NOAA discovered this bug and the reason it occurs.  This is a temporary fix that requires `error` to have some type of space (space, tab, end of line, carriage return) around it, so it will not get flagged if it is in a filename or part of a variable name, etc.  This error is expected to go away when the CMAKE build system is complete.

**Expected behavior**
* The compile will succeed.
* The run will fail during initialization when a `forrtl:  error (65):  floating invalid` error in `wmesmfmd.F90` causes the UFS simulation to terminate. (_Fig 3_)

**Screenshots**

_Fig 1_
![image](https://user-images.githubusercontent.com/86749872/144287081-a60ccc29-52f3-4997-81de-0d6ca31baefd.png)

_Fig 2_
![image](https://user-images.githubusercontent.com/86749872/144289297-0738eea2-444d-455b-81a5-047d29c68157.png)

_Fig 3_
![picture2](https://user-images.githubusercontent.com/86749872/144288796-6a6e76a5-965e-45f7-9706-0c275c6fb1d6.png)

**Additional context**
* N/A

**Comment by MatthewMasarik-NOAA** [comment]
**Update**:   The false positive error mentioned above no longer occurs.  The fix ([PR#555](https://github.com/NOAA-EMC/WW3/pull/555)) shown in _Fig 2._ above was merged into develop.

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA I wonder if you've tried to compile in debug mode after the cmake build was added to WW3. What I found is that the ``-DDEBUG=YES`` compile option for S2SW conflicts w/ various instances of the variable ``DEBUG`` in WW3. This appears to occur at the time of processing CPP flags. For example, on hera:

```
/apps/intel/parallel_studio_xe_2018.4.057/compilers_and_libraries_2018/linux/bin/intel64/fpp -DDEBUG=YES  w3gsrumd.F90>tmp.F90
```

shows the following replacement

```
!/
!/ ------------------------------------------------------------------- /
!/
      FUNCTION W3GSUC_PTR_R4( IJG, LLG, ICLO, XG, YG, &
                              NCB, NNP, YES ) RESULT(GSU)
!     Single precision pointer interface
      TYPE(T_GSU)         :: GSU
      LOGICAL, INTENT(IN) :: IJG
      LOGICAL, INTENT(IN) :: LLG
      INTEGER, INTENT(IN) :: ICLO
      REAL(4), POINTER    :: XG(:,:)
      REAL(4), POINTER    :: YG(:,:)
      INTEGER, INTENT(IN), OPTIONAL :: NCB
      INTEGER, INTENT(IN), OPTIONAL :: NNP
      LOGICAL, INTENT(IN), OPTIONAL :: YES
```

This pre-preprocessed code then fails at compile time. 

Note what I actually found in the compile log is that the instances of DEBUG were replaced by "1".

You can see a temporary fix which allowed me to compile using ``-DDEBUG=YES`` on cheyenne.intel https://github.com/DeniseWorthen/WW3/commit/40940b6227597b5f80fb7eb8d64f28a37c74c11c

**Comment by MatthewMasarik-NOAA** [comment]
Hi @DeniseWorthen , I haven't compiled in debug since CMAKE was added.  I will look into it and reply back.

**Comment by DeniseWorthen** [comment]
I've created a UFS issue (https://github.com/ufs-community/ufs-weather-model/issues/1133) since I'm unsure of where the fix will need to be made (UWM or WW3).

**Comment by DeniseWorthen** [comment]
@MatthewMasarik-NOAA I believe this issue can be closed. It looks like the fix was committed in https://github.com/ufs-community/ufs-weather-model/pull/1130

**Comment by MatthewMasarik-NOAA** [comment]
Hi @DeniseWorthen, I'm working to verify this.  Stayed tuned.

**Comment by MatthewMasarik-NOAA** [comment]
This issue can be closed as it has been resolved for S2SWA.  Thank you @DeniseWorthen.
