### ISSUE TITLE
regtest ww3_tp1.6 not b4b in regtests matrix

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#56]
Runs of the regtests matrix have indicated that test ww3_tp1.6 is not bit for bit comparable in independent runs of a given branch. Differences are seen in out_grd.ww3 and out_ont.ww3 files. This should be investigated, as pointed out by @ajhenrique, @aliabdolali and @JessicaMeixner-NOAA .

**Comment by mickaelaccensi** [comment]
@ajhenrique I think you can close this issue. I opened 2 other issues for b4b reproducibility on mw3_test_03
