### ISSUE TITLE
Localization of the arrays for implicit scheme/domain decomposition

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#574]
**Is your feature request related to a problem? Please describe.**
The global array should be localized in order to speed up the efficiency of WW3 on unstructured meshes using the domain decomposition parallelization and the implicit numerical solver, 

**Describe the solution you'd like**
The solution is provided and tested in the scalability branch. Following git-flow, this feature is isolated and will be integrated into the development after passing the regtests.

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali what is the branch for this update and what are the current regtest issues?

**Comment by aliabdolali** [comment]
> @aliabdolali what is the branch for this update and what are the current regtest issues?

https://github.com/erdc/WW3/tree/scal_local
The tests with OMP switches are failing.
