### ISSUE TITLE
correcting Fortran indexing of the multidimensional arrays for implicit scheme/domain decomposition

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#575]
**Is your feature request related to a problem? Please describe.**
Clear indexing is required for the multidimensional arrays for implicit scheme and domain decomposition, using PDLIB switch.

**Describe the solution you'd like**
The solution is provided and tested in the scalability branch. Following git-flow, this feature is isolated and will be integrated into the development after passing the regtests.

**Comment by aronroland** [comment]
this should be closed

**Comment by aronroland** [comment]
no this is done, sorry for not beeing exact!
