### ISSUE TITLE
parametric group velocity calculation for implicit scheme/domain decomposition

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#576]
**Is your feature request related to a problem? Please describe.**
A new parametric function for the calculation of the group velocity is required for the WW3 on unstructured meshes(applicable for the structured part as well).  Such implementation provides enough precision for the group velocity. The calculation is localized, therefore the group velocity and wave number arrays will be removed from the global array. As a result, memory usage is reduced. 

**Describe the solution you'd like**
The solution is provided and tested in the scalability branch. Following git-flow, this feature is isolated and will be integrated into the development after passing the regtests.

**Comment by JessicaMeixner-NOAA** [comment]
Close with merge of PR #888
