### ISSUE TITLE
update ww3_from_ftp 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#578]
**Is your feature request related to a problem? Please describe.**

Make ww3_from_ftp.sh not an interactive script. 

**Describe the solution you'd like**
Instead of having an interactive script for ./model/bin/ww3_from_ftp.sh I recommend updating it's use to: 

./model/bin/ww3_from_ftp.sh model [-k] 

the -k option is an optional argument that will keep the tar files instead of deleting them.  This way the set-up is just one command.  

**Describe alternatives you've considered**
Open to any suggestions for something different.  Thought about something with just the regression tests, but I think there's other files in there too.  Thoughts @aliabdolali @ukmo-ccbunney @mickaelaccensi @thesser1 

**Additional context**
This is a change and disruptive, but maybe it's a good time for this with all the cmake changes coming.

**Comment by aliabdolali** [comment]
I like the idea. It still requires the path (where to download it) on local machine, can we add path, like `./model/bin/ww3_from_ftp.sh` model <path> [-k], then everything is embedded in the command.
