### ISSUE TITLE
OpenMPI iogomd error

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#63]
@micahdavid reported

I was receiving the following error using OpenMPI:

At line 394 of file w3iogomd.F90
Fortran runtime error: Unit number is negative and unit was not already opened with OPEN(NEWUNIT=...)

Making the fix to w3iogomd.ftn on line 404 alleviated this error:
FROM:
IF (IFJ .LT. NOGE(IFI)) WRITE(NDSEN,1007) IFI
TO:
IF (NDSEN .GE. 0 .AND. IFJ .LT. NOGE(IFI)) WRITE(NDSEN,1007) IFI

**Comment by mickaelaccensi** [comment]
better to use test IF (IAPROC.EQ.NAPOUT) as it's already in other parts of the code

**Comment by mickaelaccensi** [comment]
see commit in umr-lops/develop : https://github.com/umr-lops/WW3/pull/7/commits/11facefe5405fcfc783a5e8233a377903f4ea5df

**Comment by ajhenrique** [comment]
Issue resolved, closing.
