### ISSUE TITLE
separate out namelist default changes from other scalability branch updates

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#644]
**Is your feature request related to a problem? Please describe.**

The scal_local PR https://github.com/NOAA-EMC/WW3/pull/637 ends up having regression test changes for every single regression test due to updates in w3grid.  These updates should be made separately so it's easy to identify what changes and why. 

**Describe the solution you'd like**

Suggested separate update: https://github.com/jessicameixner-noaa/ww3/tree/bug/updatedefaults 

**Describe alternatives you've considered**

Reverting any of these changes as needed. 

**Additional context**
This will help simplify the PR#637 code review process.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland @aliabdolali @thesser1 @maryanderson64 can you please look at these diffs: 
[matrixCompFull.txt](https://github.com/NOAA-EMC/WW3/files/8327856/matrixCompFull.txt)
[matrixCompSummary.txt](https://github.com/NOAA-EMC/WW3/files/8327857/matrixCompSummary.txt)
[matrixDiff.txt](https://github.com/NOAA-EMC/WW3/files/8327858/matrixDiff.txt)

I update the matrix.comp to ignore all of the grid.out files that have differences such as: 
```
***
/scratch2/NCEPDEV/climate/Jessica.Meixner/PR_WW3/smallfix/regtests/output/ww3_ta1/work_UPD2_U/ww3_grid.out_diff.txt
***
169c169
<   &UNST UGBCCFL =  F, UGOBCAUTO =  T, UGOBCDEPTH = -10.000, UGOBCFILE=unset                                                       ,
---
>   &UNST UGBCCFL =  T, UGOBCAUTO =  T, UGOBCDEPTH = -10.000, UGOBCFILE=unset,

```

but I'm wondering if these few setting updates are really making the big differences in the scal_local PR? The tp2.7 regtests diffs stood out to me in particular.  The others seem to be mod_def differences due to the setting change but not necessarily answer changes.   Let me know if I should go ahead and open a PR with these changes or hold off, etc.

**Comment by JessicaMeixner-NOAA** [comment]
Any thoughts @aronroland @aliabdolali @thesser1 @maryanderson64  ? I can try to revert the two changes for: 
JGS_NORM_THR and SOLVERTHR_SETUP?  And see the impact of that alone?  I know this is a high priority item so please let me know how I can help.

**Comment by aronroland** [comment]
Thanks, we will work on that one.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland I'd like to help, so please let me know what I can do.  Absent specific suggestions, I will try reverting  GS_NORM_THR and SOLVERTHR_SETUP and go from there.

**Comment by JessicaMeixner-NOAA** [comment]
I ran tests with the values of JGS_NORM_THR= SOLVERTHR_SETUP =1.E-20 as it is in the develop branch.  I then realized that my original run w/these values changed to the values in the scal_local did not have the netcdf output, so I'm re-running that.  However, I think there's enough to say that it's likely the change in defaults not these two values that might be the real cause of differences.   I'm wondering if the change in the initialization of the default should or should not be changed, or if we do change those, that we should in fact be specifying in some of the regression test nameless to use the now non-default values.  That way, the output of the regression tests would be the same.

**Comment by JessicaMeixner-NOAA** [comment]
I have confirmed that it's not the change of JGS_NORM_THR= SOLVERTHR_SETUP =1.E-20 that causes the answer differences.  It's the change in the defaults.    @aronroland @aliabdolali have you looked at the updates here: https://github.com/jessicameixner-noaa/ww3/tree/bug/updatedefaults yet?  Are these the correct subset of changes?  Should we be subsequently changing some values in regression tests?

**Comment by JessicaMeixner-NOAA** [comment]
Trying to understand answer differences that are still persisting, I believe that the following if statement in w3gridmd needs to be included in the bug/updatedefaults branch: 

```
        IF ((EXPFSN .eqv. .FALSE.).and.(EXPFSPSI .eqv. .FALSE.)     &
            .and.(EXPFSFCT .eqv. .FALSE.)                           &
            .and.(IMPFSN .eqv. .FALSE.)                             &
            .and.(EXPTOTAL .eqv. .FALSE.)                           &
            .and.(IMPTOTAL .eqv. .FALSE.)) THEN
          EXPFSN=.TRUE. ! This is the default scheme ...
        END IF
```

Getting answers to the following questions will be very useful in attempts to continue to help to make progress with PR#637: 

1. Should these two variables be the defaults: 
JGS_TERMINATE_NORM = .FALSE.
EXPFSN = .FALSE. 
? 

2. Should they be initialized to their default value as well as be set to the default in "initialisation of logical related to unstructured grid"? 

3.  Assuming the above should be changed, should regression tests be updated to retain their current answers by explicitly setting JGS_TERMINATE_NORM and EXPFSN to true in regression tests where required?

**Comment by aronroland** [comment]
Hi Jessica, 

thanks for looking into that and sorry for letting u wait for the answer. As for the default values, yes u r right, we should update them and add this in a separate branch. I will today discuss the default settings in our group and then we will let u know. 

Many thanks again for helping and looking into that. 

Cheers

Aron

**Comment by JessicaMeixner-NOAA** [comment]
The scal_local branch was merged reverting these changes.  Therefore I'm closing this issue.   @aronroland please create a new issue about updating the defaults if the defaults are still planned to be changed.
