### ISSUE TITLE
SIGSEGV segmentation fault error when adding currents with specific model resolution

### ISSUE THREAD

**Issue by EmilioEchevarria** [NOAA-EMC/WW3#649]
Hello there, 

I am trying to run some WAVEWATCH III simulations with current forcing, and I'm getting this error:
`forrtl: severe (174): SIGSEGV, segmentation fault occurred` 

I tried the usual approaches, reducing the time steps, disabling the current-induced k-shift, trying different compilation options, but nothing worked. I can see that the model breaks when there's high winds, and the traceback points to the `CALC_USTAR` subroutine in `w3src4md`:

```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
ww3_shel           0000000000698D73  Unknown               Unknown  Unknown
libpthread-2.28.s  00002B0EEDB1D730  Unknown               Unknown  Unknown
ww3_shel           00000000004E7D47  w3src4md_mp_w3spr        1465  w3src4md.F90
ww3_shel           00000000004E03AB  w3srcemd_mp_w3src         525  w3srcemd.F90
ww3_shel           00000000004A3102  w3wavemd_mp_w3wav        1202  w3wavemd.F90
ww3_shel           0000000000413654  MAIN__                   1782  ww3_shel.F90
ww3_shel           000000000040C9E2  Unknown               Unknown  Unknown
libc-2.28.so       00002B0EEDB5009B  __libc_start_main     Unknown  Unknown
ww3_shel           000000000040C8EA  Unknown               Unknown  Unknown
```

Line 1465 in `w3src4md.F90` in my case is `DELJ1   = MIN(1.,XJ - REAL(J))` (https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3src4md.F90#L1643) . Any idea what might be the issue here?

Also, the resolution of my grid is 0.4°, and I don't see this issue with a 0.5° resolution grid (same bathy). 

I also tried implementing the recent change to prevent a possible divide by zero with ustar (https://github.com/NOAA-EMC/WW3/commit/b3462bab8518d1326e728c10e3136a40d9dfc21c), but didn't help, the problem occurs when ustar is big. Any advice would be greatly appreciated. 

Regards,
Emilio

**Comment by GM-Ling** [comment]
Hi Emilio @EmilioEchevarria ,

Did you solve your issue?
I also encountered a similar error when running ADCIRC coupling with WW3 (ADCIRC passes water level and currents to WW3). The model runs fine for stand alone ww3, but when couple with currents, it ran 2 days then blew up with `forrtl: severe (174): SIGSEGV, segmentation fault occurred`.
I found the index for stress table(INT(XJ)) became a very large negative value -2147483648 in the following lines of 'w3src4md.F90':
` J = MIN ( JUMAX-1, INT(XJ) )
  DELJ1   = MIN(1.,XJ - REAL(J))`
, and this results in the segfault error.
Here are the error messages:
![image](https://user-images.githubusercontent.com/48800504/176330529-bed47d5d-f587-4261-b870-a0fc8d4afc78.png)

Please let me know if anyone has any clues for this issue.
Thank you!

**Comment by aliabdolali** [comment]
@aronroland could you take a look at this?

**Comment by aronroland** [comment]
ya, when the model blows up it always shows that, when using ST4, in the table computation. Debugging of this is not really fun. It would need the full setup and so on ... normally the left hand side of the equation should neuer blow up. So we remain at the source term but as i said it needs the full setup and we should add better debugging option for this kind of cases.

**Comment by EmilioEchevarria** [comment]
Hi @GM-Ling , No I haven't really fixed the issue yet...
Thanks @aronroland for the insight, any idea why this would be the case only when there's surface current forcing in the model?

**Comment by aronroland** [comment]
hi all, sorry to get just back now to u, we had some major update in the develop branch maybe u like to try again ...

**Comment by mickaelaccensi** [comment]
Dear @EmilioEchevarria  and @GM-Ling ,

the latest version of ww3 now allow to disable the lookup table in SIN4, see parameter SINTABLE which can be set at F to not precompte lookup table and save a lot of memory.

I close this issue, but feel free to open it if needed.

Best,
