### ISSUE TITLE
Coupling and driving data update in different time steps

### ISSUE THREAD

**Issue by ukmo-juan-castillo** [NOAA-EMC/WW3#651]
**Is your feature request related to a problem? Please describe.**
At the moment, when running a coupled configuration, it is necessary that the coupling exchange (in particular the couple receive) happens at the same time step as when the driving data is read from file. If this is not the case in some cases the run crashes in OASIS because the receive coupling calls are skipped. This results in a lack of flexibility in coupled configurations. Furthermore, the behavior depends on the order in which driving data, either from file or coupled, is obtained. 

**Describe the solution you'd like**
This issue was discovered at the Met Office using a regional ocean/wave configuration, where driving winds available at 30 minutes of each hour (eg. 0:30, 1:30, 2:30, etc) are read from file, and ocean currents were coupled at 0 minutes each hour (eg. 0:00, 1:00, 2:00, etc). The solution is simple and consists in calculating ID_OASIS_TIME (used to determine when a coupling step needs to take place) and DTTST (used to determine in driving data needs to be updated) properly in coupled configurations in the ww3_shel.ftn file, which will affect only the coupled configurations. 

This solution was tested in a backported branch (ukmo_ps45-1) with local changes, and worked in the aforementioned configuration that was failing. It was also tested using: a couple frequency of 10 minutes instead of an hour;  winds updated at 0 minutes each hour matching the oasis receive times; in atmosphere/wave and atmosphere/ocean/wave coupled configurations; and non-coupled configurations driven by winds and currents when the update of the driving data happens at the same time, and when it does not.

A branch with the solution has already been created called **fb_driving-data-frequency**. The oasis ww3_tp2.14 tests could not be run at the Met Office, but the rest of the regtests are successful.

**Describe alternatives you've considered**
The easier solution would be making sure that coupling exchanges take place at a time step when driving data is updated, but this rests flexibility to the program and complicates scripts generating driving data.

**Additional context**

**Comment by mickaelaccensi** [comment]
Hi Juan, could you explain why you can't run ww3_tp2.14 ?

**Comment by ukmo-juan-castillo** [comment]
It has to do with the change to cmake and how the netcdf libraries are installed in our HPC. I am sure Chris can give you more details if needed.

Regards,

JuanMa

**Comment by ukmo-ccbunney** [comment]
> Hi Juan, could you explain why you can't run ww3_tp2.14 ?

The `prep_env.sh` script is calling cmake, even if the regtest is compiled using gmake (i.e. via `run_test`, rather than `run_cmake_test`).

At the moment, cmake builds with netCDF are not working correctly on the Met Office Cray XC. I have a separate issue raised for this #656
