### ISSUE TITLE
remove cases from ftp

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#653]
**Describe the request**
The cases are no longer tested and synced with the latest features of the code. They are machine specific and out of date. 
 
**Expected behavior**
It can be cleaned from the tar file on ftp server, so it will not downloaded and untared when the model/bin/ww3_from_ftp.sh is executed.

**Comment by mickaelaccensi** [comment]
done

**Comment by alexandrefierro** [comment]
Thank you for your quick response!
Since the WW3 documentation is not very exhaustive and clear about this: Could you please provide pointers on how to run a real test case with this model and where to obtain the input data for it (akin to WRF).
Thank you!

**Comment by JessicaMeixner-NOAA** [comment]
@alexandrefierro we recommend following the regression tests, there are several great examples in there that can be extended to your particular use case.

**Comment by alexandrefierro** [comment]
For real cases: Which regtest(s) would you recommend and which switch(es) should I use? 
Perhaps a naive question: Why are these called regression tests? I thought that WW3 would solve iteratively via finite differencing the primitive eqs of motion (akin to WRF)?
Thank you again!

**Comment by JessicaMeixner-NOAA** [comment]
Regtests -> regression tests are used to insure code does not break when new features are added, but also provide examples of how to use the code.   Each test has an "info" that will tell you a bit about it, or you can find over-views in the manual.

**Comment by alexandrefierro** [comment]
Ok. thank you. Would you have a switch to recommend? I am very familiar with WRF and atmospheric numerical models in general but this model is structured quite differently from most models I worked with and the documentation provided is not very exhaustive and lacks clear examples.

I have also tried to compile it with netcdf4 but to no avail. I have all the requirements met & env variables set for building the code with netcdf but get:
ad3 : processing w3nmlprncmd 
mv: cannot stat ‘w3nmlprncmd.o’: No such file or directory
ad3 : processing ww3_prnc 
mv: cannot stat ‘ww3_prnc.o’: No such file or directory
      Linking ww3_prnc
      *** file ww3_prnc.o not found ***
      *** file w3nmlprncmd.o not found ***
*** Missing object files ***

nc-config --version
netCDF 4.9.0
nc-config --has-nc4
yes

WWATCH3_NETCDF=NC4
NETCDF_CONFIG=/home/user/packages/pnetcdf4//bin/nc-config

**Comment by JessicaMeixner-NOAA** [comment]
I'd recommend going through the regression tests and using that as a basis to learn what switch might be best for you case.
