### ISSUE TITLE
CMake can't find NetCDF libraries on Cray XC

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#656]
**Describe the bug**
On the Cray XC, CMake cannot find the NetCDF libraries.
I believe this is due to the nature of the library installations on the Cray.

The NetCDF installation directory contains a `bin` directory as expected, but not a `lib` or `include` directory.
Instead, the `lib` and `inlcude` directories are in separate subdirectories for each supported compiler (Cray, GNU, Intel, etc).
The cray compiler uses a wrapper script that sets the correct lib and include compiler flags based on the currently loaded programming environment.

However, this seems to be confusing CMake. If I set the `NetCDF_ROOT` env var relevant compiler sub-directory, CMake reports that it cannot run nc-config:

```
CMake Error at cmake/FindNetCDF.cmake:225 (message):
  Unable to properly find NetCDF.  Found static libraries at:
  /opt/cray/netcdf/4.6.1.3/CRAY/8.6/lib/libnetcdf.a but could not run
  nc-config:
Call Stack (most recent call first):
  model/src/CMakeLists.txt:102 (find_package)

CMake Error at cmake/FindNetCDF.cmake:225 (message):
  Unable to properly find NetCDF.  Found static libraries at:
  /opt/cray/netcdf/4.6.1.3/CRAY/8.6/lib/libnetcdff.a but could not run
  nc-config:
Call Stack (most recent call first):
  model/src/CMakeLists.txt:102 (find_package)
```

However, `nc-config` does exist, in the bin directory two levels up.

Furthermore, if CMake does manage to find nc-config, then running `nc-config --flibs` will not yield the correct result (it is empty in fact as there are 4 different sets of compile flags to chose from depending on the compiler selected).

My workaround for the moment is to disable the `find_package` call for NetCDF. Ideally, I don't want CMake to try and find the netCDF libraries and set the compiler flags - the compiler wrapper script handles all this so it is not technically required.

Perhaps I am misunderstanding something obvious (I am a bit of a cmake noob)?! So happy to be put right regarding my assumptions above!

Directory structure of my netCDF installation, in case it is useful:
```
netcdf/4.6.1.3
|-- bin
|-- CRAY
|   `-- 8.6
|       |-- include
|       `-- lib
|-- GNU
|   |-- 5.3
|   |   |-- include
|   |   `-- lib
|   `-- 7.1
|       |-- include
|       `-- lib
|-- INTEL
|   `-- 16.0
|       |-- include
|       `-- lib
```

**To Reproduce**
Run CMake on Cray XC with `NetCDF_ROOT=/opt/cray/netcdf/4.6.1.3/CRAY/8.6"
Relevant modules loaded:
 - cmake/3.21.3
 - PrgEnv-cray/5.2.82
 - cce/8.7.7(default)
 - cdt/18.12
 - cray-hdf5/1.10.2.0(default)
 - cray-netcdf/4.6.1.3(default)

**Expected behavior**
Should find netCDF library specific to currently loaded netCDF library and compiler environment, but fails with an error running nc-config.

**Screenshots**

**Additional context**

**Comment by kgerheiser** [comment]
This is a tough problem. FindNetCDF operates on the basis that `nc-config`/`nf-config` provide the correct paths. If the installations have been manually moved around and they don't point to anything then it won't work.

If the compiler handles the flags then there needs to be some sort of option to enable NetCDF without using `find_package`. This isn't ideal, but it's an easy workaround.

**Comment by ukmo-ccbunney** [comment]
@kgerheiser Here is my solution:
https://github.com/ukmo-waves/WW3/commit/118f0c02a221accb79682102fa6a7c48365f29bd

It provides a new command line option `-D EXCLUDE_FIND="list;of;libraries"` that allows the user to specify libraries that are have compiler flags configured by the compiler/wrapper. Currently, it only supports "netcdf" as an option, but I've made it a list in case we need to add other libraries to "not search for".

In this commit is also the compiler flags for the Cray Fortran compiler.

If you agree with my proposed solution, I will raise it as a PR.

**Comment by kgerheiser** [comment]
I think your solution is good. I just added one comment about using `if(TARGET NetCDF::NetCDF_Fortran)`.
