### ISSUE TITLE
comp file

### ISSUE THREAD

**Issue by Rafikow** [NOAA-EMC/WW3#666]
rafik@rafik-Latitude-3500:~/Desktop/WW3$ ./model/bin/w3_setup model -c comp -s switch
 
                *****************************
              ***   WAVEWATCH III setup     ***
                *****************************
 
 
[INFO] local env file wwatch3.env found in /home/rafik/Desktop/WW3/model/bin/wwatch3.env
   Setup file /home/rafik/Desktop/WW3/model/bin/wwatch3.env found
      Source directory            : /home/rafik/Desktop/WW3/model
      Scratch directory           : /home/rafik/Desktop/WW3/model/bin
      Save source code            : yes
      Save listings               : yes
   Update settings ? [y/n] n
 
   Setup comp & link files

ERROR: /home/rafik/Desktop/WW3/model/bin/comp.comp not found

![Screenshot from 2022-04-20 06-43-12](https://user-images.githubusercontent.com/104049486/164162639-9805e90f-f4b4-48d8-a640-2a94d3d9765b.png)

i didn't found this file .

**Comment by JessicaMeixner-NOAA** [comment]
@Rafikow does the file /home/rafik/Desktop/WW3/model/bin/comp.comp exist?

**Comment by Rafikow** [comment]
@JessicaMeixner-NOAA i don't know i found this problem and didn't know how to fix it

**Comment by JessicaMeixner-NOAA** [comment]
@Rafikow try in your terminal: 
ls /home/rafik/Desktop/WW3/model/bin/comp.comp

Which compiler are you trying to use?  My guess is that your issue is that you need to modify: 
./model/bin/w3_setup model -c comp -s switch
to be: 

./model/bin/w3_setup model -c intel  
or 
./model/bin/w3_setup model -c gnu 

depending on if you want intel or gnu.  

Then you need to decide which switch file you would like to use and make sure it exists at: 
/home/rafik/Desktop/WW3/model/bin/switch

**Comment by Rafikow** [comment]
@JessicaMeixner-NOAA  Your Email please !

**Comment by JessicaMeixner-NOAA** [comment]
@Rafikow communication through GitHub is preferred.

**Comment by Rafikow** [comment]
@JessicaMeixner-NOAA  what is the next step please !

**Comment by JessicaMeixner-NOAA** [comment]
> Which compiler are you trying to use?

**Comment by Rafikow** [comment]
intel

**Comment by JessicaMeixner-NOAA** [comment]
Try this command instead: 
`./model/bin/w3_setup model -c intel`

**Comment by Rafikow** [comment]
![Screenshot from 2022-04-22 17-48-33](https://user-images.githubusercontent.com/104049486/164759025-402e043d-dc26-4029-b73f-2c2f29836cc8.png)
i had this

**Comment by JessicaMeixner-NOAA** [comment]
Great, glad to see things are working.  I'm closing this issue. Please see the wiki page for more information: https://github.com/NOAA-EMC/WW3/wiki

**Comment by Rafikow** [comment]
thank you
