### ISSUE TITLE
Remove ifdefs around IC4METHOD = 8 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#676]
**Is your feature request related to a problem? Please describe.**
Remove the ifdefs around IC4METHOD = 8 so that this option can be used for non CESMCOUPLED cases. 

**Additional context**
This is part of merging https://github.com/NOAA-EMC/WW3/pull/641 to the develop branch, but should be submitted to the develop branch as it's own self-contained PR.

**Comment by JessicaMeixner-NOAA** [comment]
@JessicaMeixner-NOAA will check if this is still an issue and provide more info.  There might be a update for this in a branch from @DeniseWorthen

**Comment by DeniseWorthen** [comment]
My working branch is [feature/wave_ice_only](https://github.com/DeniseWorthen/WW3/tree/feature/wave_ice_only).

**Comment by MatthewMasarik-NOAA** [comment]
Thank you @DeniseWorthen

**Comment by JessicaMeixner-NOAA** [comment]
This is taken care of @DeniseWorthen branch see: https://github.com/DeniseWorthen/WW3/blob/feature/wave_ice_only/model/src/w3sic4md.F90#L523 where it's commented out.  Thanks @DeniseWorthen !

**Comment by JessicaMeixner-NOAA** [comment]
Completed in PR #780
