### ISSUE TITLE
Create ww3_shel.inp file and remove set_shel_inp 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#678]
**Describe the bug**
@MatthewMasarik-NOAA  will provide a ww3_shel.inp file that CESM can use and remove the need for the set_shel_inp routine.  This will allow users of the CESM coupled system to have additional flexibility without recompiling the code. 

**Additional context**
This is part of merging https://github.com/NOAA-EMC/WW3/pull/641 to the develop branch

**Comment by mvertens** [comment]
@JessicaMeixner-NOAA - is this needed for PR #641 - or can we put an #ifdef W3_CESMCOUPLED in for now. @alperaltuntas - I think that once a new ww3_shel.inp file is created it would be easy to read it in if its ascii. But we need to have the mechanism to recreate it on our end flexibly for the different use cases. How hard do you think that is going to be?

**Comment by JessicaMeixner-NOAA** [comment]
@mvertens this is not needed for PR #641 which is going into the dev/ufs-weather-model branch.  This will need to be addressed before the contents of PR #641 can be merged into the develop branch though.

**Comment by mvertens** [comment]
@JessicaMeixner-NOAA - thanks for the clarification.

**Comment by MatthewMasarik-NOAA** [comment]
@JessicaMeixner-NOAA , it doesn't look like I have permissions to add myself as an assignee to this issue.  Would you be able to add me?

**Comment by MatthewMasarik-NOAA** [comment]
[ww3_shel_mesh.inp.txt](https://github.com/NOAA-EMC/WW3/files/9055146/ww3_shel_mesh.inp.txt)

**Comment by MatthewMasarik-NOAA** [comment]
Corrected (blank lines removed).
[ww3_shel_mesh.inp.txt](https://github.com/NOAA-EMC/WW3/files/9055254/ww3_shel_mesh.inp.txt)
