### ISSUE TITLE
Regtest run multiple times with the same input

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/WW3#707]
**Describe the bug**

This regtest is run multiple times with the same input. Should the `grdset` be different? Or can the extras be deleted?

https://github.com/NOAA-EMC/WW3/blob/b19156fe1581e6a5851f567411a4238d5115de97/regtests/bin/matrix.base#L325-L332
**To Reproduce**

**Comment by JessicaMeixner-NOAA** [comment]
I wonder if the grdset should be b c and d for the others as this is an earlier line in the matrix: 
```
      echo "$rtst -s PR2_UNO -w work_PR2_UNO_a -m grdset_a $ww3 mww3_test_02" >> matrix.body
      echo "$rtst -s PR2_UNO -w work_PR2_UNO_b -m grdset_b $ww3 mww3_test_02" >> matrix.body
      echo "$rtst -s PR2_UNO -w work_PR2_UNO_c -m grdset_c $ww3 mww3_test_02" >> matrix.body
      echo "$rtst -s PR2_UNO -w work_PR2_UNO_d -m grdset_d $ww3 mww3_test_02" >> matrix.body 
```

**Comment by kgerheiser** [comment]
@JessicaMeixner-NOAA @aliabdolali there's a few more instances of this in `matrix.base`

https://github.com/NOAA-EMC/WW3/blob/b19156fe1581e6a5851f567411a4238d5115de97/regtests/bin/matrix.base#L822-L829

https://github.com/NOAA-EMC/WW3/blob/b19156fe1581e6a5851f567411a4238d5115de97/regtests/bin/matrix.base#L604-L611

https://github.com/NOAA-EMC/WW3/blob/b19156fe1581e6a5851f567411a4238d5115de97/regtests/bin/matrix.base#L631-L638

**Comment by JessicaMeixner-NOAA** [comment]
Thank you - I'm reopening this issue so we can take care of all of these cases.

**Comment by JessicaMeixner-NOAA** [comment]
I have a branch here: https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/regtests if anyone wants to help look it over.  I found a few more spots where we had duplicative answers.
