### ISSUE TITLE
WW3 Developer Call (Tuesday 28 June 2022 10:00am ET) 

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#715]
### WW3 Developer Call

**Tuesday 28 June 2022 10:00am ET**

During this meeting, we will have two presentations, first by Lewis Sampson from UKMET focusing on WW3 configuration to run on GPU and then John Warner (USGS) will present ROMS–WW3 coupling. 

We will also present a summary of recent developments. The meeting will end with an open forum where all developers can express their ideas and suggestions as well as ask any questions relevant to the development community. 

This meeting will be hosted by NCEP.

**Google Meet**
WAVEWATCH III Developer Meeting
Tuesday, June 28 · 10:00 – 11:00am
Google Meet joining info
Video call [link](https://meet.google.com/hes-gnjw-exa) 
Or dial: ‪(US) +1 617-675-4444‬ PIN: ‪866 312 056 0715‬#
More phone numbers: https://tel.meet/hes-gnjw-exa?pin=8663120560715
 

### Agenda

- Review of recent and upcoming changes (5 min)
- Presentation
1. Lewis Sampson and Chris Bunney (20 min), Porting of a full WW3 configuration to run on GPU: Performance, changes required and key difficulties.”
2. John Warner and Hernan Arango (20 min), ROMS and  WAVEWATCH III Model Coupling
- Open discussion (15 min)

**Porting of a full WW3 configuration to run on GPU: Performance, changes required and key difficulties.”** (Lewis Sampson and Chris Bunney, UKMET)
[slides](https://github.com/NOAA-EMC/WW3/files/9008847/UK_MetOffice_GPU_Port_WW3_Dev_Meeting.pptx)

Discussion section on porting WW3 to GPU: https://github.com/NOAA-EMC/WW3/discussions/736

Then the abstract: “As part of a two year project we have been investing the requirements for limited configurations (based on regression tests) of WW3 to run on GPU and analysing the performance. We then moved on to a full configuration using one of the Met Offices’ operational domains and have applied the same porting process. This presentation will talk about our understanding of the requirements for porting the WW3 code, the performance we can achieve with manual acceleration and the challenges that we may face when integrating this with the WW3 pre-process and build cycle. We will discuss the steps needed before we can understand the full potential of GPU parallelism, and the directions we will research so that we can advance the portability, including: PSyclone code generation, reworking the Source-Term looping structure, and changing basic coding standard to be more favourable for nvfortran and OpenACC.
 

**ROMS and  WAVEWATCH III Model Coupling** (John Warner, USGS, Hernan G. Arango (Rutgers)
[slides 1](https://github.com/NOAA-EMC/WW3/files/9011980/warner_noaaww3_developers_28june2022_nomovie.pdf)
[slides 2](https://github.com/NOAA-EMC/WW3/files/9011979/ROMS_NUOPC_coupling.pdf)

Coupling between a coastal circulation model and a wave model is necessary to properly simulate ocean environments. The wave model requires updates of currents, water levels, and changing bathymetry. The ocean model requires updates of waves for computation of enhanced bottom stress, wave-driven flows, and surface mixing. Here we describe the coupling of ROMS with WaveWatchIII using an existing approach via the Model Coupling Toolkit,  demonstrate with applications along the US east coast, and discuss next path for coupling via the NUOPC cap.

Please contact Ali if you are interested in showing your work at the next WW3 Development calls.

**Comment by hga007** [comment]
Thank you. Unfortunately, we didn't have any time to discuss any of the presentations. If there are such time constraints, perhaps I suggest concentrating on a single topic. On the other hand, if the presentation and discussions do not take an hour, it is perfectly fine to finish earlier. After all, it is a developer's meeting, and the feedback is essential.
