### ISSUE TITLE
Update NCEP regression tests to use newer intel 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#718]
**Is your feature request related to a problem? Please describe.**
The ufs-weather-model updated the modules and version of intel used.  In addition it has previously been recommended by RDHPCS to move to the newer versions of intel. 
 
**Describe the solution you'd like**
Update the version of intel used in the NCEP matrix regression tests to use the same same version of intel as ufs-weather-model (https://github.com/ufs-community/ufs-weather-model/pull/1221). 

**Additional context**
 It is expected that answers will change. The branch should be run twice and the list of known not b4b regression tests should be updated.

**Comment by aliabdolali** [comment]
I made a branch and I am testing new versions on Hera and then on Orion, I will make the PR if everything went well.

**Comment by aliabdolali** [comment]
There is a dependency for tests with ww3_grib to png/1.6.35 library, which only hpc-intel/18.0.5.274 has it.
```
module spider png

--------------------------------------------------------------------------------------------
  png: png/1.6.35
--------------------------------------------------------------------------------------------
    Description:
      PNG library


     Other possible modules matches:
        libpng

    You will need to load all module(s) on any one of the lines below before the "png/1.6.35" module is available to load.

      hpc/1.1.0  hpc-gnu/9.2.0
      hpc/1.1.0  hpc-intel/18.0.5.274
      hpc/1.2.0  hpc-gnu/9.2.0
      hpc/1.2.0  hpc-intel/18.0.5.274

```

**Comment by JessicaMeixner-NOAA** [comment]
Please see: https://github.com/ufs-community/ufs-weather-model/pull/1221/files#diff-604fbc7b745d7249a571c8484dbe95132d8b915a7e726c72365ed799ef2895b8 with the relevant changes in the screen shot here:

![Screen Shot 2022-05-23 at 1 06 11 PM](https://user-images.githubusercontent.com/22549231/169871727-efa13599-8c33-47ee-a2c2-71d5c069ad4e.png)

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA thanks, i was looking for it but couldn't find it.
