### ISSUE TITLE
cmake fails with intel mpi library 

### ISSUE THREAD

**Issue by mickaelaccensi** [NOAA-EMC/WW3#722]
**Describe the bug**
cmake fails with an error message when compiling with intel mpi library

**To Reproduce**
```
module load intel-mpi/2018.1.163
cmake
make
make install
```

produce the following error message :
```
b47f:edada740: 683 us(683 us):  open_hca: device mlx5_0 not found
[0] MPI startup(): dapl fabric is not available and fallback fabric is
not enabled

```
**Expected behavior**
to avoid this error, the workaround is to disable the environment variable I_MPI_DEVICE by doing either : 
```
unsetenv I_MPI_DEVICE
export -n I_MPI_DEVICE
```

**Comment by mickaelaccensi** [comment]
I close the issue, as discussed with @JessicaMeixner-NOAA it would be nice to add it to the FAQ

**Comment by JessicaMeixner-NOAA** [comment]
Let's not close it until it gets put on the FAQ page.

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi  It's been added to FAQ here: 
https://github.com/NOAA-EMC/WW3/wiki/FAQs-page#how-to-avoid-common-cmake-error-with-intel-impi-20181163

Let me know if you think we should add any edits to this.
