### ISSUE TITLE
Problem about the output along track (track_i.ww3)

### ISSUE THREAD

**Issue by ffayalac** [NOAA-EMC/WW3#732]
### Discussed in https://github.com/NOAA-EMC/WW3/discussions/731

<div type='discussions-op-text'>

<sup>Originally posted by **FrankAyalaC** June 23, 2022</sup>
Hi everyone,

We are currently modelling a test case in the Caribbean, and we are trying
to get the spectra along a hurricane track. According to what we
understand, firstly, the track points and their corresponding dates must be
specified in the track_i.ww3 file; secondly, the dates and the flag (T)
must be activated in the ww3_shel.inp and finally, ww3_trnc.inp (or
ww3_trck.inp) must be edited.

We follow these steps and get a .nc file with the information described in
the user guide; however, the longitude and latitudes in this file don't
match with the location data in track_i.ww3. In fact, the lats and lons in
the .nc file seem to be in accordance with the specified resolution in
ww3_grid, and it seems as if we had to interpolate them.

What should it be the correct process to obtain spectra along a track? Can
we get spectra for locations in the track that do not match with the
spatial resolution (e.g. spatial resolution of 0.25 and a point in the
track with lon and lat of 273.653 and 15.247, respectively)?
</div>

**Comment by mickaelaccensi** [comment]
Dear ffayalac,

This is actually the expected behaviour of ww3, the output track is provided at the 4 grid points arount the provided location and not at the track exact location. You need to then choose either to interpolate it or choose the nearest point, or any other method
