### ISSUE TITLE
Unitialised variable in oasis coupler causing differences in ww3_tp2.14 regtest

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#737]
**Describe the bug**
The `clinfo` character variable in `mod_oasis_namcouple.F90` is unintialised when its value is printed out to a log file
This is causing differences in the `nout.000000`  file in regression test runs of the ww3_tp2.14 test.

Pertinent lines:
https://github.com/NOAA-EMC/WW3/blob/0bf17910a71365770d520a52ded0c5f8ea22a9ef/regtests/ww3_tp2.14/input/oasis3-mct/lib/psmile/src/mod_oasis_namcouple.F90#L1636

https://github.com/NOAA-EMC/WW3/blob/0bf17910a71365770d520a52ded0c5f8ea22a9ef/regtests/ww3_tp2.14/input/oasis3-mct/lib/psmile/src/mod_oasis_namcouple.F90#L1848-L1849

**To Reproduce**
This behaviour was noted when running the regression test comparisons for the PR #612.
As this is an unitialised variable, this may not be consistently reproducible.

**Expected behavior**
A consistent initialised value should be written to the output file

**Screenshots**
Output from matrixDiff.txt for the above PR:
```
***
/home/d02/frey/WW3/TEST_WW3/regtests/output/ww3_tp2.14/work_OASACM6/nout.000000_diff.txt
***
46c46
< * ===>>> : The information mode is activated ? ==> ��I
---
> * ===>>> : The information mode is activated ? ==> h�I
```

**Comment by ukmo-ccbunney** [comment]
@mickaelaccensi I am not sure what the "information node is activated" message means here, but can I simply initialise `clinfo='no'`?

**Comment by mickaelaccensi** [comment]
yes you can just set it to no
