### ISSUE TITLE
Problem with ww3_shel

### ISSUE THREAD

**Issue by DiegoGutierrez2210** [NOAA-EMC/WW3#74]
Hi,

I am receiving the following error in my simulation, when using ww3_shel

....
     Type 6 : Partitioned wave field data   
      -----------------------------------------
            From     : 1968/06/06 00:00:00 UTC
            To       : 2001/01/02 00:00:00 UTC
            Interval :            01:00:00

            output dates out of run dates : Track point output deactivated
            output dates out of run dates : Nesting data deactivated
            output dates out of run dates : Partitioned wave field data deactivated
       Wave model ...
corrupted size vs. prev_size

Program received signal SIGABRT: Process abort signal.

The same configuration ran ok in my laptop. Any idea what it could be?

Attached are the output, switch and ww3_shel.inp files

[error.log](https://github.com/NOAA-EMC/WW3/files/3412151/error.log)
[ww3_shel.inp.txt](https://github.com/NOAA-EMC/WW3/files/3412157/ww3_shel.inp.txt)

[switch.txt](https://github.com/NOAA-EMC/WW3/files/3412166/switch.txt)

**Comment by CarstenHansen** [comment]
@DiegoGutierrez2210 This looks like the bug in ww3_shel opened as issue #13 by @AndresSepulveda. It was merged into the master hotfix #54

**Comment by ajhenrique** [comment]
Issue resolved, closing.
