### ISSUE TITLE
Syntax Error "error #6592: This symbol must be a defined parameter, an enumerator, or an argument of an inquiry function that evaluates to a compile-time constant.   [ENDIANNESS]       character(*), parameter :: FILE_ENDIAN = ENDIANNESS

### ISSUE THREAD

**Issue by aronroland** [NOAA-EMC/WW3#742]
**Describe the bug**

Fortran Syntax Error

**To Reproduce**
Steps to reproduce the behavior. 

Does not compile with the error in the header. Code must follow the Fotran syntax 

**Expected behavior**

Able to compile without error 

**Screenshots**

Syntax Error "error #6592: This symbol must be a defined parameter, an enumerator, or an argument of an inquiry function that evaluates to a compile-time constant.   [ENDIANNESS]       character(*), parameter :: FILE_ENDIAN = ENDIANNESS

**Additional context**

Solution:

ENDIANNESS must be defined as a character parameter. Since it is used for the defining the endianess in the open command with the convert context. The code should be self contained and not depending on the makefile system. E.g. we have coupled WW3 to SHYFEM and SCHISM and in this context it needs to compiling without dependencies on the makefile system.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland we compile WW3 in other coupled systems and this is fine.   You should be able to use the WW3 cmake build to make a library and then use that in your fully coupled executable and not have the issue with endianness.

**Comment by ukmo-ccbunney** [comment]
If suppose if we really wanted to make endian selection not dependent on CMake, we could do so with a normal CPP directive. This would then work with any build system. E.g.
```
#if ENDIAN == "big"
 character(*), parameter :: FILE_ENDIAN = "big_endian"
#elif ENDIAN == "little"
 character(*), parameter :: FILE_ENDIAN = "little_endian"
#else
 character(*), parameter :: FILE_ENDIAN = "native"
#endif
```

Although with the Gmake build about to be retied, the only build system for WW3 will be Cmake...

**Comment by aronroland** [comment]
Hi All, 
let me 1st thank u for the fast answers. Generally, the correctness of the code should not depend on any kind of build system. However, this is something we can also discuss during a developer meeting in a larger context. I am still strict against it. Moreover, as we are hard coupling ww3 to SCHISM or SHYFEM we are not interested in the build system of WW3. We are using the Build system of the certain models that can be anything. Therefore, the code should be self-contained and correctly compiling in any build system. Build system is just a tool and should not be influencing correctness of the code itself. This is at least my opinion. I appreciate your fix given above.

**Comment by ukmo-ccbunney** [comment]
@aronroland - is the solution above using CPP directives acceptable to you? If so, I could look at getting it implemented and tested. AFAIK the CPP directives are the responsibility of the compiler, rather than the "build system", so I think that would make it "build system agnostic"... 

EDIT: Although looking a bit closer at the CPP marcros, it might not be as clean a solution as I described above as you cannot do CPP comparisons against string constants...

**Comment by aronroland** [comment]
Hi @ukmo-ccbunney, 

as I said above, I appreciate your fix and would be very thankful if u do so. I had absolutely the same in mind. This is a good way to proceed. 

Cheres

Aron

**Comment by ukmo-ccbunney** [comment]
@aronroland Great. I will have a look at adding something.

**Comment by ukmo-ccbunney** [comment]
Actually, I think there is a simpler solution by adding this to the top of `constants.F90`:

```
#ifndef ENDIANNESS
#define ENDIANNESS "native"
#endif
```

That will keep the CMake functionality the same (it is just setting a -D flag on the compiler anyhow) but sets a default of "native" endian in the case where it is not set by the build system.

This can still be set via -D flags in the normal way in any other build system, e.g.
`-DENDIANNESS='"big_endian"'` (notice the double and single quotes).

**Comment by aronroland** [comment]
I think this solution is much better! Great!
