### ISSUE TITLE
fix automatic tests after w3emc pr

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#751]
**Describe the bug**
After PR https://github.com/NOAA-EMC/WW3/pull/745 the automatic tests need to be updated with the module updates as the automatic tests failed. 

**Expected behavior**
Automatic tests should pass.

**Comment by aliabdolali** [comment]
Although w3nco is changed to w3emc in [spack.yaml](https://github.com/NOAA-EMC/WW3/blob/develop/model/ci/spack.yaml), cmake still searches for w3nco in github action:


```
CMake Error at model/src/CMakeLists.txt:188 (find_package):
  By not providing "Findw3nco.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "w3nco", but
  CMake did not find one.

  Could not find a package configuration file provided by "w3nco" with any of
  the following names:

    w3ncoConfig.cmake
    w3nco-config.cmake

  Add the installation prefix of "w3nco" to CMAKE_PREFIX_PATH or set
  "w3nco_DIR" to a directory containing one of the above files.  If "w3nco"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by JessicaMeixner-NOAA** [comment]
@kgerheiser are we missing something here to fix the github actions?

**Comment by kgerheiser** [comment]
Yes, it's a very simple fix. The build was cached and unless the key was manually changed it wouldn't rebuild the dependencies. I have made a PR to use the hash of the `spack.yaml` in the cache key so if it's changed a build will trigger.

**Comment by aliabdolali** [comment]
Thanks @kgerheiser for doing this fix. Does it mean every time we have a change in the modules/libraries, we need to trigger it manually or everything is automated with your PR?

**Comment by kgerheiser** [comment]
It's automated now (base on `spack.yaml` changes), but should you need to refresh the cache manually you just have to change the `cache_key` variable. As you can see the key is onto `gnu5` now (I usually just append a number).

**Comment by aliabdolali** [comment]
@kgerheiser I see, thanks for the clarification and we will keep it as a reference for the future.
