### ISSUE TITLE
error in ww3_shel

### ISSUE THREAD

**Issue by JMSnyder1980** [NOAA-EMC/WW3#771]
I have been getting tthis same issue as well.  Does anyone know how to resolve this issue.  Please advise on how to handle this issue or what is being done to fix this bug.  I need information as soon as possible on how to resolve this please.

### Discussed in https://github.com/NOAA-EMC/WW3/discussions/570

<div type='discussions-op-text'>

<sup>Originally posted by **ppokhrel1** January  6, 2022</sup>
I am gettting the following error with Katrina T03 Tutorial.

                     *** WAVEWATCH III Program shell ***      
               ===============================================

  Comment character is '$'

At line 923 of file ww3_shel.F90 (unit = 10, file = './ww3_shel.inp')
Fortran runtime error: Bad repeat count in item 2 of list input

Error termination. Backtrace:
#0  0x7f16e9d1d32a
#1  0x7f16e9d1ded5
#2  0x7f16e9d1e69d
#3  0x7f16e9e8b005
#4  0x7f16e9e8b098
#5  0x7f16e9e8dd02
#6  0x7f16e9e8f379
#7  0x555fe8f2a5ed
#8  0x555fe8f29e08
#9  0x7f16e937cbf6
#10  0x555fe8f29e39
#11  0xffffffffffffffff

I am using 6.07.1 version. Could anyone please help? 

Shel input file:
$ -------------------------------------------------------------------- $
$ WAVEWATCH III shell input file                                       $
$ -------------------------------------------------------------------- $
$ Define input to be used with flag for use and flag for definition
$ as a homogeneous field; four input lines.
$ 1) Water levels
$ 2) Currents
$ 3) Winds
$ 4) Ice concentrations (cannot be homogeneous).
$ 5,6,7)  Assimilation data
F F
F F
T F
F
F
F
F
$
$ Time frame of calculations ----------------------------------------- $
$ - Starting time in yyyymmdd hhmmss format.
$ - Ending time in yyyymmdd hhmmss format.
$
20050828 120000
20050830 000000
$
   1
$
$ Define output data ------------------------------------------------- $
$ Five output types are available (see below). All output types share
$ a similar format for the first input line:
$ - first time in yyyymmdd hhmmss format, output interval (s), and
$   last time in yyyymmdd hhmmss format (all integers).
$ Output is disabled by setting the output interval to 0.
$
$          Fields of mean wave parameters
$          Standard line and line with flags to activate output fields
$          as defined in section 2.4 of the manual. The second line is
$          not supplied if no output is requested.
$                               The raw data file is out_grd.ww3,
$                               see w3iogo.ftn for additional doc.
$
   20050828 120000  3600  20050830 000000
$
  N
  HS FP DP
$
$         Point output
$          Standard line and a number of lines identifying the
$          longitude, latitude and name (C*10) of output points.
$          The list is closed by defining a point with the name
$          'STOPSTRING'. No point info read if no point output is
$          requested (i.e., no 'STOPSTRING' needed).
$                               The raw data file is out_pnt.ww3,
$                               see w3iogo.ftn for additional doc.
$
   20050828 120000  3600  20050830 000000
$
  N
  HS FP DP
$
$         Point output
$          Standard line and a number of lines identifying the
$          longitude, latitude and name (C*10) of output points.
$          The list is closed by defining a point with the name
$          'STOPSTRING'. No point info read if no point output is
$          requested (i.e., no 'STOPSTRING' needed).
$                               The raw data file is out_pnt.ww3,
$                               see w3iogo.ftn for additional doc.
$
   20050828 120000  3600  20050830 000000
$
    271.774 29.208 'NDBC42040'
     0.0   0.0  'STOPSTRING'
$
$ Output along  track.
   20050828 120000     0  20050830 000000
$ Restart files (no additional data required). The data file is restartN.ww3, see w3iors.ftn for additional doc.
   20050830 000000     0  20050830 000000
$ Boundary data (no additional data required). The data file is nestN.ww3, see w3iobp.ftn for additional doc.
   20050828 120000     0  20050830 000000
$ Separated wave field data (dummy for now)
   20050828 120000     0  20050830 000000
$
   'STP'
$ -------------------------------------------------------------------- $
$ End of input file                                                    $</div>

**Comment by CarstenHansen** [comment]
Hmm, I think you should check if the three lines that are repeated for output fields, are actually present in your ww3_shel.inp file.  https://github.com/ppokhrel1 actually made this correction to discussion #570, but didn't tell if was a possible solution or not. If this is not the error, a possible step to resolve is to identify which line in the ww3_shel.ftn contains the failing READ (line 923 of file ww3_shel.F90 found in one of the two TMP_{MPI,SEQ} catalogues).

**Comment by JessicaMeixner-NOAA** [comment]
I'm going to assume that @CarstenHansen comments here helped you get passed this error.  If not, please feel free to post more in the discussion https://github.com/NOAA-EMC/WW3/discussions/570
