### ISSUE TITLE
cmake is not integrated to the test framework

### ISSUE THREAD

**Issue by MathieuDutSik** [NOAA-EMC/WW3#779]
**Describe the bug**
It has apparently been decided that from now on the cmake is the framework for compilation. The problem is that this has not been integrated with the testing framework.

**To Reproduce**
Run "./bin/run_test                        -s PDLIB ../model ww3_tp2.6"
and see
[ERROR] comp file /Users/mathieu/GITall/GIT/WW3/model/bin/comp not found
        Please run /Users/mathieu/GITall/GIT/WW3/model/bin/w3_setup <main_dir> -c <comp> -s <switch>

which is symptomatic of the run_test referring to the old framework.

**Expected behavior**
I expect the run_test to integrate smoothly with the cmake. Before once you had comp/link you were good to go. It should be the same for the run_test.

**Screenshots**
None

**Additional context**
This applies to all the tests.

**Comment by mickaelaccensi** [comment]
Hi Mathieu,
you should use now run_cmake_test
I should be detailed soon in the manual...
Mickael

**Comment by JessicaMeixner-NOAA** [comment]
@MathieuDutSik yes, we will soon be updating the manual and wiki pages.  At that time run_cmake_test will be moved to run_test (See PR here: https://github.com/NOAA-EMC/WW3/pull/726) 
Let me know if you have any issues running the run_cmake_test by reopening this issue or creating another issue.
