### ISSUE TITLE
Update white spaces via automatic scripts

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#797]
**Is your feature request related to a problem? Please describe.**
A PR will be coming that will delete trailing white space and fix the indentation so that "ifs" line up with "end-ifs". 2 spaces will be used to delineate this change.  This is following the https://github.com/NOAA-EMC/WW3/wiki/WW3-Code-Style-Standards 

This is a disruptive change, and a two week period (starting today Oct 21, 2022) will be given for anyone to submit PRs before this change.  

**Describe the solution you'd like**
A PR to the develop branch which will update the white spacing in the source code.  This will be done after https://github.com/NOAA-EMC/WW3/issues/796 

**Describe alternatives you've considered**
This is following the code style standards created from the [code standards discussion](https://github.com/NOAA-EMC/WW3/discussions/551)

**Additional context**
The script/tools used to do this will be shared so that others can employ this on in-progress code to help with merging if necessary.

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen I know you shared the auto-formatting scripts, but I can't seem to find them anywhere in the PR or this issue.  I found this: https://github.com/NOAA-EMC/WW3/discussions/551#discussioncomment-3478721 which referenced an emacs command: 

`emacs --batch <filename> -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer`

Is that is or was there another command as well?

**Comment by DeniseWorthen** [comment]
The way I ended up doing this is to save this file as ``.emacsloc``

[emacsloc.txt](https://github.com/NOAA-EMC/WW3/files/10992533/emacsloc.txt)

and then using the command

emacs --batch -l .emacsloc **_filename_** -f mark-whole-buffer -f f90-indent-subprogram -f save-buffer

in a shell script.

The issue as I remember is that the batch command can't reference the normal configuration location for emacs, but someone w/ more emacs experience than me might have a better solution.

**Comment by JessicaMeixner-NOAA** [comment]
Thank you @DeniseWorthen!

**Comment by mickaelaccensi** [comment]
To remove extra white spaces, I had to do : 
for iterations in $(seq 1 50); do for file in $(ls *.F90); do echo $file; sed -i "s/ #ifdef/#ifdef/g" $file; done; done
for iterations in $(seq 1 50); do for file in $(ls *.F90); do echo $file; sed -i "s/ #endif/#endif/g" $file; done; done

Now when I try to do a git merge, it remains the issue with all the lines starting with   !> 
it creates conflicts instead of adding the sections for doxygen

**Comment by JessicaMeixner-NOAA** [comment]
@mickaelaccensi  - As I said offline, I'm happy to help with this process early next week.  Given that it's not just updating for the white space, but 6+ months of code, at this point you might unfortunately be looking at: 
1. seeing what can be automatically merged, if you haven't edited a file, it should be easy to just choose whatever is in the develop branch. 
2. Perhaps just re-making your updates in a new branch of updated code.  

But hopefully it will not come to that.   I'm going to re-close this issue as this has been updated in the code, but feel free to add more comments here.
