### ISSUE TITLE
Netcdf gridded output to file with fixed name

### ISSUE THREAD

**Issue by ajhenrique** [NOAA-EMC/WW3#8]
NCEP operations require that ounf output to a fixed-name file. Currently a quick-fix is used in ww3_ounf.ftn:

! For NCEP application, requires fixed netcdf file name
            FNAMENC='ww3.gridded.nc'

This issue is a request for a feature to allow users choosing that in ounf.inp.

**Comment by ajhenrique** [comment]
@mickaelaccensi : I've already had this request a few months ago, an easy feature to implement would be to set the number of characters in date [4(yearly),6(monthly),8(daily),10(hourly)] to 0 to not have any time specification in the filename.
That's easy to implement so I can do it on a feature branch

**Comment by mickaelaccensi** [comment]
@ajhenrique Do you want me to implement it on this branch or is better if I create a new feature branch to implement it ?

**Comment by ajhenrique** [comment]
> @ajhenrique Do you want me to implement it on this branch or is better if I create a new feature branch to implement it ?

As we discussed, please implement on a feature branch. Thanks!

**Comment by mickaelaccensi** [comment]
@ajhenrique, is it ok for you if setting ndates=0 in ww3_ounf.inp or ww3_ounf.nml to define the output filename as a fixed name by replacing the date by 'field', for example ww3.field.nc or ww3.field_hs.nc ?

**Comment by ajhenrique** [comment]
Continued in issue #23, closing.
