### ISSUE TITLE
Error in wmupdtmd.ftn / wmupds

### ISSUE THREAD

**Issue by clementcal** [NOAA-EMC/WW3#80]
In line 1876- 1878 (wmupds subroutine)

              IF ( FLAGLL ) THEN
                  IF ( ICLOSE.NE.ICLOSE_NONE ) JJ = 1 + MOD(J-1,NXI)
                  IF ( JJ.LT.1 .OR. JJ.GT. NXI ) CYCLE

This leads to a crash if no closure is used as JJ is not defined before being called.

I think it should be like this instead, copying what is done in line 1835

              IF ( FLAGLL .AND. ICLOSE.NE.ICLOSE_NONE ) THEN
                  JJ =  1 + MOD(J-1,NXI)
                  IF ( JJ.LT.1 .OR. JJ.GT. NXI ) CYCLE

It might have been reported before, maybe in the mailing list, but the version here still has the error.

**Comment by ajhenrique** [comment]
Hi @clementcal could you provide the error output for you case? We would like to have a closer look at that issue. Thanks!

**Comment by clementcal** [comment]
Hi @ajhenrique,

You can find the error message below:

forrtl: severe (194): Run-Time Check Failure. The variable 'wmupdtmd_mp_wmupds_$JJ' is being used in 'wmupdtmd.F90(1701,32)' without being defined
Image              PC                Routine            Line        Source             
ww3_multi          0000000000A64609  wmupdtmd_mp_wmupd        1701  wmupdtmd.F90
ww3_multi          0000000000A0EDC7  wmupdtmd_mp_wmupd         827  wmupdtmd.F90
ww3_multi          00000000009D139D  wmupdtmd_mp_wmupd         296  wmupdtmd.F90
ww3_multi          000000000080438F  wmwavemd_mp_wmwav         397  wmwavemd.F90
ww3_multi          000000000040CB75  MAIN__                    149  ww3_multi.F90
ww3_multi          000000000040C15E  Unknown               Unknown  Unknown
libc-2.17.so       00002B503CB35495  __libc_start_main     Unknown  Unknown
ww3_multi          000000000040C069  Unknown               Unknown  Unknown

After looking into the code a bit more and trying to stick with what was done in previous loops I think it is only a missing line defining JJ:

+          JJ = J
          IF ( FLAGLL ) THEN
              IF ( ICLOSE.NE.ICLOSE_NONE ) JJ = 1 + MOD(J-1,NXI)
              IF ( JJ.LT.1 .OR. JJ.GT. NXI ) CYCLE

Both fix work for me anyway.

Regards

**Comment by ajhenrique** [comment]
Thanks. We will have to look into this with some more detail. Can you describe the test case you are running that you get that error? If possible, can you provide the multi.inp and indicate what types of grids you are using? Thanks.

**Comment by clementcal** [comment]
I'm using a rectangular grid for the Atlantic ocean, forced with wind, sea level and current defined each on their own grid. You can see attached my switch and multi.nml files, and the script I'm using to give you an idea of my application.

[Prepare_atl.txt](https://github.com/NOAA-EMC/WW3/files/3648200/Prepare_atl.txt)

[ww3_multi.txt](https://github.com/NOAA-EMC/WW3/files/3648185/ww3_multi.txt)

[switch_atl.txt](https://github.com/NOAA-EMC/WW3/files/3648190/switch_atl.txt)

**Comment by ajhenrique** [comment]
Thanks @clementcal . Are any of your input grids identical/same resolution as the wave model grid?

**Comment by ajhenrique** [comment]
Hi @clementcal can you add a write statement before that line, recompile and check the value of ICLOSE?

**Comment by clementcal** [comment]
Hi @ajhenrique, by luck I've just found out that the error/crash is only happening in debug mode, when compiling without the debug options I have no issues at all.

To answer your question I have ICLOSE = -1 (in both debug and normal mode).

And it might help you understand how the code is behaving, below are my compil options:
debug mode: opt="-c $list -O0 -assume byterecl -g -traceback -check all -warn all  -heap-arrays -module $path_m"
normal mode: opt="-c $list -O3 -assume byterecl -ip -heap-arrays -module $path_m"

**Comment by ajhenrique** [comment]
@mickaelaccensi could you help figure this one out? I looked the code over and have the impression this may be related to not initializing the grid closure type: this is forced to happen when using the .inp file, but if unspecified in the .nml file, there is no default in the current code?

**Comment by aliabdolali** [comment]
Hi @clementcal is this still an issue for you with the develop branch? or can we close it?
