### ISSUE TITLE
remove FP1 and THP1

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#803]
**Is your feature request related to a problem? Please describe.**
@benoitp-cmc recommends removing FP1 and THP1 from the code as these variables are not used.  FP1 is calculated locally in w3src2md, but this will not change that.  This will also hopefully resolve issues that were encountered with PR #741. 

**Describe the solution you'd like**
Removal of FP1 and THP1 

**Describe alternatives you've considered**
Could update the calculations to avoid errors seen in debug, but as these variables are not used, removal would clean up the code.  Additionally, there's a note in the code that these are "Old parameters not yet in new structure ..." so its likely these are not used at all but not deleted. 

**Additional context**
See PR #741 for additional info on the reason this issue was discovered.

**Comment by JessicaMeixner-NOAA** [comment]
@benoitp-cmc I do see that FP1 is used in the calculation of: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3iogomd.F90#L2315-L2318
```
          IF ( FP1(JSEA).NE.UNDEF) THEN
              ETX(JSEA) = ETX(JSEA) + A(ITH,IKP1(JSEA),JSEA)*ECOS(ITH)
              ETY(JSEA) = ETY(JSEA) + A(ITH,IKP1(JSEA),JSEA)*ESIN(ITH)
            END IF
```
And ETX,ETY is used in the calculation of THM, which is an output/used variable.  There's probably a way to remove this dependency, but this might be an issue.

**Comment by benoitp-cmc** [comment]
That won't be an issue. Looking closer, ETX and ETY is calculated 3 times, once for THM, once for THP0 and once for THP1.

**Comment by benoitp-cmc** [comment]
Is it me or there is a lot of INIT_GET_ISEA that are useless in that routine?

**Comment by JessicaMeixner-NOAA** [comment]
There might be, but every time you have a new loop you have to call that routine again.  Any specific call you are thinking about?

**Comment by benoitp-cmc** [comment]
Is there any need for it if the loop does not explicitly use ISEA. For example this call seems useless to me:
https://github.com/NOAA-EMC/WW3/blob/cae97a93451cb53c9cc9349d5b68e80cdfde84a8/model/src/w3iogomd.F90#L2276

**Comment by JessicaMeixner-NOAA** [comment]
That does indeed does seem useless... also I now have seen places where we should be calling INIT_GET_ISEA and we are not, such as: 
https://github.com/NOAA-EMC/WW3/blob/cae97a93451cb53c9cc9349d5b68e80cdfde84a8/model/src/w3iogomd.F90#L1779-L1784 
https://github.com/NOAA-EMC/WW3/blob/cae97a93451cb53c9cc9349d5b68e80cdfde84a8/model/src/w3iogomd.F90#L1754
