### ISSUE TITLE
Update gint to regrid restart files as well as output files

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#829]
**Is your feature request related to a problem? Please describe.**
Need restart files from global models for regional models. 

**Describe the solution you'd like**
Update ww3_gint to regrid restart files.  This assumes that the frequency range is the same. 

**Describe alternatives you've considered**
Use netcdf restarts and have offline regridding available. 

**Additional context**
This has been done in feature branches and needs to be reintegrated to the develop branch.

**Comment by ukmo-ccbunney** [comment]
That would be a very useful addition!

**Comment by JessicaMeixner-NOAA** [comment]
Need to investigate this: https://github.com/NOAA-EMC/WW3/issues/940 

But otherwise, should have a PR for this next week, see branch: https://github.com/jessicameixner-noaa/ww3/tree/gintupdatewrstdevelop
