### ISSUE TITLE
Unstructured Grid Namelist Documentation

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#830]
The documentation of the namelist for &UNST in ww3_grid.inp here: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/inp/ww3_grid.inp#L306-L331

have a few misisng variables from what is listed in w3gridmd: https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3gridmd.F90#L1072-L1090

Can someone (@thesser1 @aronroland @MathieuDutSik or @aliabdolali) help fill in the variable descriptions for the following variables which appear to not have definitions: 

```
UGOBCFILE,          
UGBCCFL, 
JGS_LIMITER,                               
JGS_NLEVEL,                                
JGS_SOURCE_NONLINEAR,     
```

**Comment by aronroland** [comment]
Hi @JessicaMeixner-NOAA, I will update the Manual these days ...

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland I've been looking at the documentation which is largely updated now, but I have a question: 

Based on the code (https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3gridmd.F90#L2430-L2447) I know that only one of: 
EXPFSN, EXPFSPSI, EXPFSFCT, IMPFSN, IMPTOTAL and EXPTOTAL 
can be selected. 

All of these variables are declared as false when defining the variables: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3gridmd.F90#L900-L929

But then EXPFSN is set to true before we call the namelist: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3gridmd.F90#L2379-L2412

Is it intended for EXPFSN to be the "default" and if you want to run EXPFSPSI, EXPFSFCT, IMPFSN, IMPTOTAL or EXPTOTAL  you need to also set EXPFSN=FALSE? 

Also a few of the variables are different in the declaration versus the section right before calling the namelinst, is that intentional or should these be made to be consistent?  I'm assuming if we do that we change the values selected when declaring the variables or just remove that from the declaration/definition.

**Comment by aronroland** [comment]
Yes, EXPFSN is the default scheme and if u want to run the others then indeed u need to set EXPFSN to FALSE. 
Declaration and initialization could be merged and should be consistent.

**Comment by JessicaMeixner-NOAA** [comment]
I am running regtests with removing the values of the variables in the declaration since what's being used later is actually what is being used in the code.  I'll sumbit a PR assuming regtests pass.   Then, I'll work on updating the documentation of the namelists in &UNST in ww3_grid.inp
