### ISSUE TITLE
Namelist SIN4 in model/inp/ww3_grid.inp

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#831]
The SIN4 namelist is not explicitly in ww3_grid.inp (not even to say "same as SIN3").  This should likely be added for completeness.   Moreover, SWELLF6 and SWELLF7 are not defined.  

Any thoughts @mickaelaccensi ?

**Comment by JessicaMeixner-NOAA** [comment]
Also the case for SDS4 namelist looking at 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3gridmd.F90#L1027-L1034 
versus 
https://github.com/NOAA-EMC/WW3/blob/develop/model/inp/ww3_grid.inp#L170-L186

The following need to be defined: 

```
SDSBCHOICE, , FXPM3, FXFM3, &
       FXFMAGE,, SDSCUM, SDSSTRAIN, SDSSTRAINA,  &
       SDSSTRAIN2,, SDSFACMTF, SDSNMTF,SDSCUMP,  &
       , SDSBT,, SDSISO,       &
       SDSBCK, SDSABK, SDSPBK, SDSBINT, SDSHCK,        &
      , SDSCOS, SDSBRF1, SDSBRFDF,  SDSNUW,     &
       SDSBM0, SDSBM1, SDSBM2, SDSBM3, SDSBM4,         &
       WHITECAPWIDTH, WHITECAPDUR, SDSMWD, SDSMWPOW, SDKOF
```

**Comment by mickaelaccensi** [comment]
You're right, it should be added

**Comment by mickaelaccensi** [comment]
namelists have been updated in PR #1181
