### ISSUE TITLE
Running multiple run_test simultaneously

### ISSUE THREAD

**Issue by Liu-Jincan** [NOAA-EMC/WW3#844]
Hi, everyone! 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

- The version of WaveWatchⅢ is v6.07.  I always use the script `run_test` in the `regtests/bin` folder to run model. An example for one experiment is as follow, 
    ```Shell
    WW3-6.07.1/regtests/bin/run_test \
                -i input_maine_P125 \
                -c Gnu \
                -s ST4 \
                -p mpirun \
                -n 8 \
                -f \
                -r ww3_shel \
                -N \
                -w work_maine_P125 \
                -o netcdf \
                WW3-6.07.1/model/ \
                work_global_area
    ```
    The  `run_test` applys the `model/bin/w3_make` to generate the executable program in the `model/exe`. The problem is,  when running multiple `run_test` for different experiments simultaneously, the executable may be confusing and stop running the model.

**Describe the solution you'd like**

- If it is possible that the `run_test` applys the `model/bin/w3_make` to generate the executable program in the customized folders, such as `model/exe_**` ?

**Describe alternatives you've considered**

**Additional context**

**Comment by aliabdolali** [comment]
Hi @Liu-Jincan 
regtests/bin/run_cmake_test does the job for you and compiles executables in regtests/<test>/work/exe directory

**Comment by Liu-Jincan** [comment]
Very thanks for your reply @aliabdolali !
Maybe I should try to do the job with the latest model version~~
