### ISSUE TITLE
ww3_ta1 : Something wrong in ww3_uprstr when the switch contains MPI

### ISSUE THREAD

**Issue by Liu-Jincan** [NOAA-EMC/WW3#847]
Hello!

**Describe the bug**

- The version of WaveWatchⅢ is the latest development. The example test is `regtests/ww3_ta1/input_UPD2_U_cap`. 
    Using the default switch file `switch_ST4`, everything is ok when running the commnd 
    ```
    ./bin/run_cmake_test -i input_UPD2_U_cap -s ST4 -w work1  ../model/ ww3_ta1`
    ```
  However, if the switch contains MPI (`switch_ST4_MPI`), something is wrong in the process of `ww3_uprstr` when running the commnd 
    ```
    ./bin/run_cmake_test -i input_UPD2_U_cap -s ST4_MPI -w work2  ../model/ ww3_ta1
    ``` 
    ![image](https://user-images.githubusercontent.com/73934823/200103270-66b76b36-8d02-43ef-a268-6ce7854bc70d.png)

- `switch_ST4`
    ```
    NOGRB SHRD PR0 FLX0 LN1 ST4 NL1 BT1 DB1 TR0 BS0 IC0 IS0 REF0 WNT1 WNX1 CRT1 CRX1 O0 O1 O2 O3 O4 O5 O6 O7 O10 O11
    ```
- `switch_ST4_MPI`
    ```
    NOGRB DIST MPI PR0 FLX0 LN1 ST4 NL1 BT1 DB1 TR0 BS0 IC0 IS0 REF0 WNT1 WNX1 CRT1 CRX1 O0 O1 O2 O3 O4 O5 O6 O7 O10 O11
    ```

**To Reproduce**
Steps to reproduce the behavior. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JessicaMeixner-NOAA** [comment]
@Liu-Jincan apologies for the slow response.  The first thing to try is to run with the -f flag: 

./bin/run_cmake_test -i input_UPD2_U_cap -s ST4_MPI  -f -w work2  ../model/ ww3_ta1

This way appropriate programs that are not intended to be MPI programs are build with SHRD.

**Comment by Liu-Jincan** [comment]
@JessicaMeixner-NOAA Very thanks for your suggestion. Everything is ok now.
