### ISSUE TITLE
ifdef statements in pr 851 are not evaluated as expected

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/WW3#855]
**Describe the bug**
The change to allow charn to be reset for st3 or st4 does not produce the expected code.

**To Reproduce**

Found by testing the UWM model after updating to develop, which does not reproduce. 

Can also be found by using cpp directly on code:

``cpp -DW3_IC0 -DW3_ST4 w3updtmd.F90``

```
            VA(:,JSEA) = 0.
#ifdef W3_ST3 || defined(W3_ST4)
            CHARN(JSEA) = AALPHA
#else
            CHARN(JSEA) = 0.
#endif
```

produces 

```
          VA(:,JSEA) = 0.



          CHARN(JSEA) = 0.
```

**Expected behavior**

When IC0 and ST4 are active, cpp should produce
```
          VA(:,JSEA) = 0.



          CHARN(JSEA) = AALPHA
```

The expected behaviour can be produced with:

#if defined W3_ST3 || defined(W3_ST4)

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for reporting @DeniseWorthen  I'll get this fixed ASAP.

**Comment by MatthewMasarik-NOAA** [comment]
pr #851

**Comment by JessicaMeixner-NOAA** [comment]
Regression tests have been started: https://github.com/JessicaMeixner-NOAA/WW3/tree/bug/charnifdef
A PR will be raised when they've been completed, likely will be tomorrow.

**Comment by DeniseWorthen** [comment]
you've got a typo in your fix (defind).

**Comment by DeniseWorthen** [comment]
```
diff --git a/model/src/w3updtmd.F90 b/model/src/w3updtmd.F90
index b3dcc707..b1c7bebf 100644
--- a/model/src/w3updtmd.F90
+++ b/model/src/w3updtmd.F90
@@ -1836,7 +1836,7 @@ CONTAINS
          NSPEC, FICEN
     USE W3WDATMD, ONLY: TIME, TICE, ICE, BERG, UST
     USE W3ADATMD, ONLY: NSEALM, CHARN
-#if defind W3_ST3 || defined(W3_ST4)
+#if defined W3_ST3 || defined(W3_ST4)
     USE W3GDATMD, ONLY: AALPHA
 #endif
     USE W3IDATMD, ONLY: TIN, ICEI, BERGI
@@ -1947,7 +1947,7 @@ CONTAINS
                  ICEI(IX,IY), 'SEA (NEW)'
 #endif
             VA(:,JSEA) = 0.
-#ifdef W3_ST3 || defined(W3_ST4)
+#if defined W3_ST3 || defined(W3_ST4)
             CHARN(JSEA) = AALPHA
 #else
             CHARN(JSEA) = 0.
```
