### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#860]
**Describe the bug**
When the cache is updated for intel and the CI requires to build new versions of the dependent libraries, the CI will fail.  

**To Reproduce**
Update cache_key in .github/workflows/intel.yml 

**Expected behavior**
CI tests should pass 

**Additional context**
* will move to using noaa-emc spack stack 
* Need to create new model/ci/spack.yaml for intel and add %intel to it.  
* Should also create a gcc file 

This issue has been reported by several, and several people have worked to fix it! Thanks especially to @AlexanderRichert-NOAA and @aerorahul

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA for the spack.gnu.yaml or spack.gcc.yaml file, what is the equivalent %intel that should be there? 



Note fixes from @AlexanderRichert-NOAA and @aerorahul are here: https://github.com/JessicaMeixner-NOAA/WW3/tree/fixci and probably in others branches as well.

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA in the SCOTCH PR you mentioned: 
'''
When my CI run finally moved on to the build-oasis stage, it immediately failed because apparently the "nvm" line in ~/.bash_profile (which I think is there by default?) doesn't like getting double-run. Workaround for this was to add sed -i 's|\(.*NVM.*\)|#\1|' ~/.bash_profile to the end of the previous step. Alternatively, if NVM isn't necessary, it might be just as well to revert to the default shell (no use of .bash_profile) and add the . /opt/intel/... line to the steps as needed. 
''' 
Do you have a branch with this implemented somewhere?   I've tried to remove the bash_profile line, but I'm not sure where to add the /opt/intel lines and am getting more errors than before.

**Comment by AlexanderRichert-NOAA** [comment]
> @AlexanderRichert-NOAA for the spack.gnu.yaml or spack.gcc.yaml file, what is the equivalent %intel that should be there?
> 
> Note fixes from @AlexanderRichert-NOAA and @aerorahul are here: https://github.com/JessicaMeixner-NOAA/WW3/tree/fixci and probably in others branches as well.

The equivalent there is 'gcc'.

**Comment by AlexanderRichert-NOAA** [comment]
> @AlexanderRichert-NOAA in the SCOTCH PR you mentioned: ''' When my CI run finally moved on to the build-oasis stage, it immediately failed because apparently the "nvm" line in ~/.bash_profile (which I think is there by default?) doesn't like getting double-run. Workaround for this was to add sed -i 's|(._NVM._)|#\1|' ~/.bash_profile to the end of the previous step. Alternatively, if NVM isn't necessary, it might be just as well to revert to the default shell (no use of .bash_profile) and add the . /opt/intel/... line to the steps as needed. ''' Do you have a branch with this implemented somewhere? I've tried to remove the bash_profile line, but I'm not sure where to add the /opt/intel lines and am getting more errors than before.

It should theoretically be as simple as putting "source /opt/..." at the beginning of that step, but I'll play around with this in the next little while and let you know.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @AlexanderRichert-NOAA  I've updated to have a specific gnu yaml file and will wait for your help on the other.  Thanks for helping with this! It's greatly appreciated.

**Comment by JessicaMeixner-NOAA** [comment]
> > @AlexanderRichert-NOAA for the spack.gnu.yaml or spack.gcc.yaml file, what is the equivalent %intel that should be there?
> > Note fixes from @AlexanderRichert-NOAA and @aerorahul are here: https://github.com/JessicaMeixner-NOAA/WW3/tree/fixci and probably in others branches as well.
> 
> The equivalent there is 'gcc'.

Any obvious reason why this should break the ci for gnu which was working before?

**Comment by AlexanderRichert-NOAA** [comment]
Not that I can think of. As long as it was compiling with gcc already then I don't know why it would be an issue. I can try it. Is there a certain error you're getting?

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA I must have had a typo or didn't clear cache because the GNU is working now.   Intel is still failing with the bash profile issue.  Branch is still here: https://github.com/JessicaMeixner-NOAA/WW3/tree/fixci

**Comment by AlexanderRichert-NOAA** [comment]
Cool, I've also got GNU running successfully through the setup stage. Take a look at https://github.com/AlexanderRichert-NOAA/WW3/blob/ww3_scotch/.github/workflows/intel.yml (note that I've made one or two irrelevant tweaks of my own, namely in the spack commands). I've taken out the default shell setting at the top, removed the command adding intel to .bash_profile, and added `. /opt/intel/oneapi/setvars.sh` at the beginning of the install-dependencies-with-spack and build-oasis steps. Another alternative would be to just replace ">>" with ">" when adding the intel setup to .bash_profile, on the assumption that you don't want whatever is in there by default.

**Comment by JessicaMeixner-NOAA** [comment]
You are more of an expert on this than me, so if there are other updates we "should" do even if not "necessary" persay, let me know.  I'm planning to do a PR with just the CI changes separate from the SCOTCH PR or I'd just pull in these changes from you directly.

**Comment by AlexanderRichert-NOAA** [comment]
Fair enough. For now I'd say if we can get it working by calling the intel setup directly and scrapping the .bash_profile, then let's do that but otherwise minimize changes.

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA okay I've gone back and looked at your branch and compared to my branch and there are a lot of differences and my branch https://github.com/JessicaMeixner-NOAA/WW3/tree/fixci is still not working.   Did I miss a needed  '. /opt/intel/oneapi/setvars.sh' or something else?   One attempt I completed the dependency builds but the WW3 builds failed, the latest attempt the dependencies didn't even build.   Should I just take your whole .github/workflows/intel.yml at this point?  I know we wanted to minimize the changes if possible.  Also I noticed you were using the ubuntu-latest instead of ubuntu-20.04 ?  Should I switch back to -latest?

**Comment by AlexanderRichert-NOAA** [comment]
Yes, it's best to use -latest as much as possible. The only tweak I had to make in changing that for the GCC workflow was adding gfortran 12 (or you can just tell spack to use some other version of GCC). Let me try your setup and see how it goes.

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA the GCC is working, but the intel workflow is not.

**Comment by AlexanderRichert-NOAA** [comment]
@JessicaMeixner-NOAA Just looking at your intel.yml there are a couple things to look at. These lines:
```
defaults:
  run:
    shell: bash -leo pipefail {0}
```
will cause issues at least with ubuntu 22.04, so I would recommend removing those.

Uncomment `#. /opt/intel/oneapi/setvars.sh` in install-dependencies-with-spack.

Remove these lines in the build stage:
```
      - name: install-intel
        run: |
          echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile
```

**Comment by JessicaMeixner-NOAA** [comment]
Okay still failing: https://github.com/JessicaMeixner-NOAA/WW3/actions/runs/3648673052/jobs/6162368549 

Should I be going back to ubuntu-latest?  I went to 22.04 to fix errors because it wasn't working.  Should we just go for the bigger changes at this point to get this running again?

**Comment by AlexanderRichert-NOAA** [comment]
Yeah it's best to use ubuntu-latest and try to make it work. Also, IMO it would also be best to add "--fail-fast" to the spack install command, that way it'll fail ASAP if it's going to fail, and it's easier to read the output because the errors will be at the end.

The reason it's currently crashing is that it's looking under /usr/local for one or two libraries, and it's picking up on versions that we don't want to use (there's a ton of useless stuff installed in there, like android SDK). Try adding "sudo mv /usr/local /usrlocal_renamed" at the beginning of the spack installation step and that should do the trick.

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA at this point should I just grab this whole file: https://github.com/AlexanderRichert-NOAA/WW3/blob/ww3_scotch/.github/workflows/intel.yml

**Comment by AlexanderRichert-NOAA** [comment]
Not yet-- we can do that if it comes to it, but there were one or two things I was experimenting with that I'm not 100% sure about. If it doesn't work this time around, then I can clean up my files and we can do a wholesale copy.

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA I've started to test this again today, and don't recognize an error of something to fix: https://github.com/JessicaMeixner-NOAA/WW3/actions/runs/3676636953/jobs/6217538332 for my latest run, branch is still: https://github.com/JessicaMeixner-NOAA/WW3/tree/fixci 

Any updates on your end about just copying the full .github/workflows/intel.yml from your branch?

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA does GitHub delete the cache automatically after a period of time?  I'm noticing we no longer have any saved cache no noaa-emc/ww3 so even if a PR didn't specifically changed the cahche-key the CI jobs are failing.

**Comment by AlexanderRichert-NOAA** [comment]
That's odd about the cache. It should last 7 days (with a 10GB limit).

For https://github.com/JessicaMeixner-NOAA/WW3/actions/runs/3676636953/jobs/6217538332, it appears to be the error I was seeing related to cmake feature checks in hdf5 dying on account of it picking up incorrect libraries from /usr/local. I don't know if there's a cleaner way to deal with this, but I solved it by putting "sudo mv /usr/local /usr_local_mv" in the installation step prior to the "spack install" command.

**Comment by JessicaMeixner-NOAA** [comment]
It had been over 7 days and perhaps some of the recent PRs pushed it over 10GB too? I don't know.  

The latest error is "==> Error: ProcessError: /usr/local/bin/cmake: No such file or directory
12754
 
which doesn't quite make sense to me?  https://github.com/JessicaMeixner-NOAA/WW3/actions/runs/3677981427/jobs/6220661134 but perhaps from the "sudo mv" command I just added?  I'll start looking at the diffs between mine and your intel.yml file, although I guess yours is failing in the oasis build so I can't just copy that right now either.

**Comment by AlexanderRichert-NOAA** [comment]
Sorry I should have clarified-- try putting the "sudo mv" at the beginning of that whole workflow step. Right now, "spack external find" is picking up on the cmake in that location, but then it's gone when "spack install" runs. So the move needs to happen before "spack external find".

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @AlexanderRichert-NOAA -- I looked at your intel.yml file  for where to add that command, and I got further.  The current error is: 

```
2022-12-12T18:16:23.5225868Z icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
2022-12-12T18:16:23.5232320Z 
2022-12-12T18:16:23.5246436Z --------------------------------------------------------------
2022-12-12T18:16:23.5259329Z Preprocessor version:
2022-12-12T18:16:23.5263627Z make: gcc: Permission denied
2022-12-12T18:16:23.5265478Z make: *** [makefile:88: script_info] Error 127
2022-12-12T18:16:23.5600544Z ==> Error: ProcessError: Command exited with status 2:
2022-12-12T18:16:23.5601109Z     'make' '-j2'
2022-12-12T18:16:23.6026215Z 
2022-12-12T18:16:23.6026509Z 2 errors found in build log:
2022-12-12T18:16:23.6027107Z      36    Copyright (C) 1985-2022 Intel Corporation.  All rights reserved.
2022-12-12T18:16:23.6027479Z      37    
2022-12-12T18:16:23.6027821Z      38    icpc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is depr
2022-12-12T18:16:23.6028225Z            ecated and will be removed from product release in the second half o
2022-12-12T18:16:23.6028630Z            f 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommen
2022-12-12T18:16:23.6029043Z            ded compiler moving forward. Please transition to use this compiler.
2022-12-12T18:16:23.6029503Z             Use '-diag-disable=10441' to disable this message.
2022-12-12T18:16:23.6029800Z      39    
2022-12-12T18:16:23.6030202Z      40    --------------------------------------------------------------
2022-12-12T18:16:23.6030556Z      41    Preprocessor version:
2022-12-12T18:16:23.6030862Z   >> 42    make: gcc: Permission denied
2022-12-12T18:16:23.6031198Z   >> 43    make: *** [makefile:88: script_info] Error 127
2022-12-12T18:16:23.6031428Z 
2022-12-12T18:16:23.6031594Z See build log for details:
2022-12-12T18:16:23.6032365Z   /tmp/runner/spack-stage/spack-stage-esmf-8.3.0b09-b3bs7ikswtxkrrzztxtnygaxyoxtudl7/spack-build-out.txt
2022-12-12T18:16:23.6032738Z 
2022-12-12T18:16:23.6851639Z ==> Warning: Skipping external package: pkg-config@0.29.2%intel@2021.7.1+internal_glib build_system=autotools arch=linux-ubuntu22.04-x86_64/nv6emqg
2022-12-12T18:16:23.8241393Z ==> Error: Terminating after first install failure: ProcessError: Command exited with status 2:
2022-12-12T18:16:23.8247461Z ==> Updating view at /home/runner/work/WW3/WW3/spack/var/spack/environments/ww3-intel/.spack-env/view
2022-12-12T18:16:23.8247833Z     'make' '-j2'
2022-12-12T18:16:23.9100999Z ##[error]Process completed with exit code 1.
```
I had to download the logs to find it as it was too big.  Unfortunately it took 40 minutes to get to the fail point.  I looked at your https://github.com/AlexanderRichert-NOAA/WW3/blob/ww3_scotch/.github/workflows/intel.yml and you at least get past the dependecy build before failing.  Should I start with this and work through the oaises build failure? I know there were parts of it you wanted to refine further, but we're at a stand-still since the cache got cleared plus this is really needed to make more progress on SCOTCH.  I'm hoping I can try to resolve this somehow today.

**Comment by AlexanderRichert-NOAA** [comment]
Okay. I'm going to revert one or two changes in mine and get it to a point where you should be able to copy it over. I'll let you know when it's ready.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks @AlexanderRichert-NOAA that'd be great.  In the meantime I'm going to change icc-> icx to see if I have success with those warning messages.

**Comment by AlexanderRichert-NOAA** [comment]
@JessicaMeixner-NOAA Try my intel.yml and spack_intel.yaml now and see how it goes. I'm still working on figuring out the best resolution for that ESMF build issue (it's a combined problem of gmake, esmf, and spack that I've run into about a thousand times now...), but for now I have _a_ workaround in place (the "ln -s" line).

**Comment by JessicaMeixner-NOAA** [comment]
@AlexanderRichert-NOAA I'm struggling to get this to work.  I think there are other changes I might need to make? Do you have a branch based on develop we could just make a PR from?

**Comment by AlexanderRichert-NOAA** [comment]
No but I will shortly.

**Comment by AlexanderRichert-NOAA** [comment]
Okay, I've created a PR off of current develop branch that passes CI tests: https://github.com/NOAA-EMC/WW3/pull/865
