### ISSUE TITLE
remove files from regtests comparison

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#87]
The profile output gmon.out and time_count.txt should be removed from the regtests/bin/matrix.comp script so that they are not included in regression test comparisons.

**Comment by JessicaMeixner-NOAA** [comment]
I already have a fix for it.

**Comment by ajhenrique** [comment]
> I already have a fix for it.

Thanks @JessicaMeixner-NOAA . Where is the fix?
