### ISSUE TITLE
Issue when installing NetCDF

### ISSUE THREAD

**Issue by oaeen** [NOAA-EMC/WW3#880]
Hi! I was following the Quick Start Guide for Users and I found the next error on Step 2 ("Download and expand large/binary/netcdf files"), it looks like the files on the site have been deleted. Is there any other way to install NetCDF?

**Previous code:**
git clone -b main https://github.com/NOAA-EMC/WW3
cd WW3

**Code raising the error:**
`wget ftp://polar.ncep.noaa.gov/tempor/ww3ftp/ww3_from_ftp.v6.07.tar.gz` in `sh model/bin/ww3_from_ftp.sh`

**Error message**
No such directory ‘tempor/ww3ftp’.

**Comment by aliabdolali** [comment]
please try develop instead of dev. 
git clone -b develop https://github.com/NOAA-EMC/WW3

**Comment by oaeen** [comment]
Thanks
