### ISSUE TITLE
Difficulty creating unresolved obstacles for large unstructured grids

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#889]
When using alphaBetalab its been difficult to create the unresolved obstacles for large unstructured meshes due to the program timing out in queue times or running out of memory.

**Comment by aliabdolali** [comment]
@JessicaMeixner-NOAA could you explain why we need obstruction for GFSv17 mesh?

**Comment by JessicaMeixner-NOAA** [comment]
So we can use UOST if needed.  This is a feature we have in structured grids we potentially need for GFSv17.  We can always run with and without for the final targeted grid and chose what to do based on results, but at the moment I haven't been able to generate them for the larger global grids.

**Comment by aliabdolali** [comment]
The strength of unstructured meshes is that one does not need obstruction, The statistics in the paper by Lorenzo also showed obstruction could not improve results.  It is only good for very coarse meshes which are appropriate for climate and long-term studies, not what we deal with here in GFS scale (like tp2.21 regtest). 
In the summer, we investigated if the alphabetalab can be utilized, and the conclusion was it is simpler if we make the mesh finer near obstacles. In fact, the mesh generation tool, I have developed, can do that with tiny additional elements near islands that are not resolved. I had it in mind when I initially checked alphabetalab for unstr meshes. Also, the obstruction might add computational demands, which we are trying to avoid. 
As the designer of the wave component and technical lead for the science of GFS wave, I believe the path forward is clear. 

We can certainly ask Lorenzo to see if alphabetalab can handle our large meshes (it has parallel capabilities), or ask for NOVEL queue permission and run it for a longer time on Hera. It can be a test to be conducted, with low priorities compared to the number of directions or spatial resolution requirements, ... . Hopefully, it was helpful. 

FYI: @AvichalMehra-NOAA

**Comment by JessicaMeixner-NOAA** [comment]
@aliabdolali -  I've been in contacted with Lorenzo.   Priorities for GFSv17 will be determined via other venues.  

This issue is not related to the WW3 code itself.  I'm working on tracking this and other issues through another more appropriate venue.  This issue will be closed here and reopened elsewhere.

**Comment by aronroland** [comment]
@aliabdolali, @JessicaMeixner-NOAA,

it is all true but Lorenzo did his work for time scales, which are beyond operational. There is pro/con from each of your viewpoints. However, understanding the nature of fractal geometries of our coastlines my feeling is that we can gain from having obstruction on global. It is all about the spatial and temporal scales we are looking it. I would like to have it working with the help of Lorenzo. Maybe we can taylor still something with Arun & Avichal.
