### ISSUE TITLE
ww3 v7.14 does not compile 

### ISSUE THREAD

**Issue by JMSnyder1980** [NOAA-EMC/WW3#894]
w3_setup crashes

I have installed ww3 version 7.14 and followed the instructions on the quick start guide and afterwards ran w3_automake and w3_make and both crash.

**Expected behavior**
The w3_make should compile producing in exe ww3_grid.exe, ww3_prep.exe, ww3_shel.exe, etc.  These are not producing.

**Screenshots**

*****
 
 Exporting WWATCH3_ENV=/home/ww3/WW3/model/bin/wwatch3.env
Shared Object     : No
 
[INFO] list of the programs selected : ww3_strt ww3_bound ww3_outf ww3_outp ww3_trck ww3_grib ww3_gint gx_outf gx_outp ww3_uprstr ww3_systrk ww3_gspl ww3_prep ww3_shel
 
[INFO] SEQ progs :  ww3_strt ww3_bound ww3_outf ww3_outp ww3_trck ww3_grib ww3_gint gx_outf gx_outp ww3_uprstr ww3_systrk ww3_gspl ww3_prep  ww3_shel
 
 
                *****************************
              ***   WAVEWATCH III make      ***
                *****************************
 
Main directory    : /home/ww3/WW3/model
Scratch directory : /home/ww3/WW3/model/tmp
Save source codes : yes
Save listings     : yes
Shared Object     : No
 
[INFO] list of the programs selected : ww3_strt ww3_bound ww3_outf ww3_outp ww3_trck ww3_grib ww3_gint gx_outf gx_outp ww3_uprstr ww3_systrk ww3_gspl ww3_prep ww3_shel
Making makefile ...
 
                *****************************
              ***   WAVEWATCH III makefile  ***
                *****************************
 
switch = /home/ww3/WW3/model/work_SEQ/switch.SEQ
   Checking all subroutines for modules (this may take a while) ...
(crash occurs here)

All the files I have in exe are these:

ls ../exe/
switch  switch.SEQ

**Additional context**

**Comment by JMSnyder1980** [comment]
I was able to build using cmake and another issue popped up which I already made an bug report for.

**Comment by Jialunx** [comment]
Hi, may I know how you solve this?
Many thanks

**Comment by mickaelaccensi** [comment]
Hi Jialunx,

The official installation procedure is described in the README file. Using cmake instead of w3_make solved the issue.
