### ISSUE TITLE
Enhancement: Consolidation and performance improvements of wave setup computation on structured and unstructured grids.

### ISSUE THREAD

**Issue by aronroland** [NOAA-EMC/WW3#900]
**Describe the bug**
Enhancement: I had some ideas how to improve the performance in parallel. E.g. reduce all_reduce calls by omitting every n-th iteration, reordering of the array accesses to reduce cache dismisses . 

**To Reproduce**
It runs faster ... 

**Expected behavior**
should run faster ...

**Screenshots**
no

**Additional context**
no

**Comment by JessicaMeixner-NOAA** [comment]
Close with merge of PR #888
