### ISSUE TITLE
Enhancement: Improve shallow-water source term integration for explicit source terms within the unstructured downscaling approach.

### ISSUE THREAD

**Issue by aronroland** [NOAA-EMC/WW3#902]
**Describe the bug**
For the explicit schemes we just omit the limiter by introducing proper functional derivatives for the diagonal part of the source terms.

**To Reproduce**
Compare to Boers case

**Expected behavior**
Good results for the Boers case

**Screenshots**
no

**Additional context**
no

**Comment by JessicaMeixner-NOAA** [comment]
Close with merge of PR #888
