### ISSUE TITLE
Boers 1996 regtest

### ISSUE THREAD

**Issue by aliabdolali** [NOAA-EMC/WW3#903]
**Describe the new regtest**
For most of the nearshore parts of WW3, there is no laboratory case as a benchmark, therefore enhancements by the introduction of new limiters, or physics like depth breaking, and triad interaction, ... cannot be tested properly. 
A setup based on Boers 1996 experiments is now prepared as regtests/ww3_tp2.19 to check the performance of WW3 on unstructured meshes with Domain Decomposition/Implicit schemes with Neumann Boundary Conditions for Depth Breaking and Triad source terms and wave setup.

**Comment by aliabdolali** [comment]
The test is about to be finalized after a few tiny changes before we push it to WISE [PR#888](https://github.com/NOAA-EMC/WW3/pull/888)

**Comment by JessicaMeixner-NOAA** [comment]
Close with merge of PR #888
