### ISSUE TITLE
Coastal reflection for the implicit schemes on unstructured grids

### ISSUE THREAD

**Issue by aronroland** [NOAA-EMC/WW3#905]
**Describe the bug**
Introduce coastline reflection for the implicit scheme, and homogenization within the new wetting & drying scheme.

**To Reproduce**
No reflection when using implicit schemes. 

**Expected behavior**
Reflection when using implicit schemes. 

**Screenshots**
no

**Additional context**
I have tested it in terms of increased directional spreading and difference in Hs infront of Finistere. It looks plausible, future will show ...

**Comment by JessicaMeixner-NOAA** [comment]
Close with merge of PR #888
