### ISSUE TITLE
regtest ww3_tp2.10 instability

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#93]
The Lake Erie SMC propgagtion only regtest (ww3_tp2.10) is going unstable (at least on our Cray system). Output fields after the initial timestep are full of "NaN", "Inf" or unrealistically large values. This is causing problems for comparison of regtest suites.

**Comment by ukmo-ccbunney** [comment]
Fixed with reduction of CFL timestep to 60 seconds:
https://github.com/ukmo-waves/WW3/commit/a71df3d719312cf6a57022991c99c4d70a998d84

**Comment by ajhenrique** [comment]
Thanks @ukmo-ccbunney , will close this issue.
