### ISSUE TITLE
Typo in WMINITMD with MPRF switch

### ISSUE THREAD

**Issue by clementcal** [NOAA-EMC/WW3#94]
line 3268 it is:
!/MPRF      USE W3SERVMD, ONLY: PRINIT, PRTIME

It should be:
!/MPRF      USE W3TIMEMD, ONLY: PRINIT, PRTIME

**Comment by ajhenrique** [comment]
Good eye @clementcal we will include a fix in an upcoming update to the develop branch.

**Comment by ukmo-ccbunney** [comment]
@clementcal I've added this fix to our UKMO bf_ukmo_cray development branch. I will be raising a PR for this soon.

**Comment by ajhenrique** [comment]
Thanks, @ukmo-ccbunney for adding this to you dev PR bundle.
