### ISSUE TITLE
w3iors NSEAL vs NSEA in non-MPI portions of read/write 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/WW3#940]
**Describe the bug**
Not 100% sure this is a bug, but this should be investigated.  While working on https://github.com/NOAA-EMC/WW3/issues/829

I found that in the non-MPI sections of the read/write of the restart we are using: 

DO JSEA=1, NSEAL 

In the following lines of code: 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3iorsmd.F90#L631 
and 
https://github.com/NOAA-EMC/WW3/blob/develop/model/src/w3iorsmd.F90#L788

In standalone mode, perhaps we've already defined NSEAL=NSEA and this is fine, but I found I had to set NSEAL=NSEA when trying to read/write this from ww3_gint.   

To test if this is a bug or not, my plan is to: 
* run the regression tests with these NSEAL->NSEA and see if they work 
* See if there are differences, and make sure to test a non-mpi case for a restart run and make sure everything is working as expected.

**Comment by MatthewMasarik-NOAA** [comment]
This does sound like a good thing to investigate.  Good find @JessicaMeixner-NOAA

**Comment by JessicaMeixner-NOAA** [comment]
All regression tests except the usual passed.  Next step is running a restart case for non-mpi with the develop and this branch and see how that goes.

**Comment by ukmo-ccbunney** [comment]
So - my opinion on this is that it aught to be changed to `NSEA`.

Using `NSEAL` makes the assumption that setting `NSEAL = NSEA`  is always handled by whatever code is calling this.
In the wave model, this is always the case (handled via `w3parall.f90:SET_UP_NSEAL_NSEALM`), but as in this case it is not always the wave model calling this module so we should not make assumptions. `NSEA` will _always_ be defined, but AFAIK `NSEAL` is only ever valid in an MPI case so we should no expect it to be defined by the calling routine in SHRD mode.

Assuming that changing it does not impact the results (I can't see why), then I advocate defensive programming and changing it to NSEA.

There might be other places in the code where this assumption on NSEAL being defined is also made...

**Comment by JessicaMeixner-NOAA** [comment]
@ukmo-ccbunney okay -- I will proceed with this code-fix.  Should have a PR up soon... that's a good question about other places in the code about the assumption on NSEAL.  Should we make a new issue for that?

**Comment by MatthewMasarik-NOAA** [comment]
I find @ukmo-ccbunney suggestion compelling.

**Comment by ukmo-ccbunney** [comment]
> @ukmo-ccbunney okay -- I will proceed with this code-fix. Should have a PR up soon... that's a good question about other places in the code about the assumption on NSEAL. Should we make a new issue for that?

Perhaps not a bad idea so it is logged and someone can then put some time aside to look through the code.

**Comment by ukmo-ccbunney** [comment]
I'm running regression tests now.

**Comment by JessicaMeixner-NOAA** [comment]
New issue: https://github.com/NOAA-EMC/WW3/issues/956 for general case
