### ISSUE TITLE
output history fields of ust,ustdir and asf are incorrect when running with unstructured mesh with domain decomposition

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/WW3#942]
**Describe the bug**

UST, USTDIR and ASF are dimensioned as NSEALM*NAPROC. When added to the Arrexch in ``do_output_exchanges``, the index ``jsea`` is used. It should be ``isea``. 

**To Reproduce**

The following figures demonstrates the issue in three test cases using the mesh-based cap. This is work under development for use in UFS (see issue [#1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)). It uses a branch of dev/ufs-weather-model and couples ATM-WW3. All three cases utilized run-time generation of netCDF history files.

Also, all cases were run with the restart frequency set > run length to avoid the issue reported in [#1556](https://github.com/ufs-community/ufs-weather-model/issues/1556) with the corruption of fields at the restart frequency.

For reference, the domain decomposition for the domain on 10PEs is

![emesh decomp 10pe](https://user-images.githubusercontent.com/40498404/224507535-afd7cf34-5446-4683-85e2-38e21f978d70.jpg)

The three test cases in the figures below are 

- unstructured mesh with domain decomposition (top)
- identical unstructured mesh with card-deck (middle). This case does not use ``do_output_exchanges``.
- a structured grid over the same domain (bottom). This case does not use ``do_output_exchanges``.

The ``Z0`` exported to the atmosphere (*1e3) in the three cases is

![nofix wavImp_Sw_z0_2021-03-22-28800](https://user-images.githubusercontent.com/40498404/224508104-bc5015a4-654c-4480-b6cf-a3dbe83876ce.jpg)

For the domain decomposition case, the ``Z0`` field is clearly corrupted on ``NAPROC-1`` (in this case PE=9)

This is because of corrupted ``UST,USTDIR`` fields after the ``output_exchange`` step.  This shows the ``USTX`` field for the three cases using the current code

![nofix USTX_2021-03-22-28800](https://user-images.githubusercontent.com/40498404/224504419-87c63cea-60b0-4403-a0bb-ef3d43158b00.jpg)

Changing the index of UST,USTDIR and ASF to ``isea`` when filling Arrexch produces the following:

![fix USTX_2021-03-22-28800](https://user-images.githubusercontent.com/40498404/224504727-ed935ef3-05ae-4d65-84ba-3995719d7d61.jpg)

And the ``Z0`` field exported the the ATM is no longer corrupted

![fix wavImp_Sw_z0_2021-03-22-28800](https://user-images.githubusercontent.com/40498404/224508114-91e19966-1175-44ae-ba25-c74e467c5dd1.jpg)

**Comment by aronroland** [comment]
Catch of the week!--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 3/11/23, 7:13 PM Denise Worthen ***@***.***> wrote:

   
  Describe the bug UST, USTDIR and ASF are dimensioned as NSEALM*NAPROC. When added to the Arrexch in do_output_exchanges, the index jsea is used. It should be isea. 
  To Reproduce 
  The following figures demonstrates the issue in three test cases using the mesh-based cap. This is work under development for use in UFS (see issue #1556). It uses a branch of dev/ufs-weather-model and couples ATM-WW3. All three cases utilized run-time generation of netCDF history files. 
  The three cases are 
   
   unstructured mesh with domain decomposition (top) 
   identical unstructured mesh with card-deck (middle). This case does not use do_output_exchanges. 
   structure grid over the same domain (bottom). This case does not use do_output_exchanges. 
   
  This shows the USTX field for the three cases using the current code 
   
  Changing the index of UST,USTDIR and ASF to isea when filling Arrexch produces the following:
