### ISSUE TITLE
Erroneous commas in w3uostmd and w3iogrmd

### ISSUE THREAD

**Issue by ukmo-ccbunney** [NOAA-EMC/WW3#95]
There is an inccorrectly placed comma on line 432 of w3uostmd.ftn:

https://github.com/NOAA-EMC/WW3/blob/92cb41f70e91da97be9e5cd8bfee1de0a569f676/model/ftn/w3uostmd.ftn#L432

and line 1263 of w3iogrmd.ftn:

https://github.com/NOAA-EMC/WW3/blob/92cb41f70e91da97be9e5cd8bfee1de0a569f676/model/ftn/w3iogrmd.ftn#L1263

In both cases, there should not be comma after closing bracket following the READ or WRITE keyword. Whilst the GNU and IFORT compilers silently ignore this, it is not syntactically correct and the Cray compiler throws an error.

**Comment by ajhenrique** [comment]
@ukmo-ccbunney could you please create a HF branch to get this on board the master and develop branches across repositories? @mickaelaccensi please let me know if there are any bugfix commits in your develop PRs that should also go to the WW3 mater. Thanks.
