### ISSUE TITLE
when coupled with ice model, pdlib case does not reproduce with different decompositions 

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/WW3#961]
**Describe the bug**

This is work associated with UFS Issue [#1556](https://github.com/ufs-community/ufs-weather-model/issues/1556)

For UFS, PR #949 resolved the lack of reproducibility for changes in domain decomposition for the case of ATM-WAV case. But in the fully coupled (ATM-OCN-ICE-WAV), changes in WW3 domain decomposition still break reproducibility. 

The test case uses the same mesh as before (still using explicit) with the fully coupled case running on either 10PEs or 5PEs for WW3. When fully coupled, WW3 exports the partitioned stokes drift to the OCN in addition to Z0 to the ATM. It imports the ice fraction from the ICE model. 

On the 4th time-step, WW3 has received identical values from all other components at the start of the timestep but sends back a different value at a single point for the 3rd partition of stokes drift (both x and y), depending on decomposition. The cause is a difference in the last two (k=32,33) frequencies of array ``a``. 

The non-reproducing point is located on the edge of one domain element in the 10PE case. The same point is in the interior of a domain element in the 5PE case. The location is shown below in green, where black and red are the points on adjacent domains.

<img width="449" alt="Screen Shot 2023-03-27 at 2 55 29 PM" src="https://user-images.githubusercontent.com/40498404/228039464-ea5666e6-1973-4b46-9483-7f9901c2536d.png">

The issue appears associated with the imported ice fraction. For timesteps 1,2,3 the imported ice fraction at this point is zero. On the 4th timestep, it is 0.49 (ficen = 0.75). Mapsta is 1.0 at the non-reproducing point and does not change.

A test was made with the imported ice fraction set to a constant value (0.15). In that case, the fully coupled case can be integrated 24 hours and results are B4B using two different WW3 decompositions.

A second test was made with the exported stokes drift set to a constant value and allowing the ice concentration to change. In that case, differences are found in the WW3 history files at the same location, in arrays ``TAUWNX,Y`` and ``TAUWI,X``.

**To Reproduce**
Steps to reproduce the behavior. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JessicaMeixner-NOAA** [comment]
@DeniseWorthen !!!!   Great find.  Am I reading this correctly to assume that the issue is that MAPSTA doesn't get updated to go from an "ice" point to an "active sea point" in this case?   I know that this commit had been in question before: https://github.com/NOAA-EMC/WW3/commit/ddbe94446279c89643a05a8e77012586899067e2 but it almost seems that this w3uice routine needs to be called versus this commit being an issue?  I  don't know if reverting this commit was ever tried or not.  But maybe I'm not reading this correctly.

**Comment by DeniseWorthen** [comment]
I actually do not think the issue is the w3uice. In this case, FICEN=FICE0=0.75 and the suspect point has mapsta=1 always, since the ice concentrations below the cutoff. 

The commit you're pointing to is a change we made for restart reproducibility. This case restart reproduces but does not reproduce when changing decomposition.

**Comment by JessicaMeixner-NOAA** [comment]
Okay, so we should look more towards TAUWNX,Y and TAUWI,X then?   If so I have a couple of ideas of things to try, in terms of trying FLD1 instead of FLD2 or not FLD1 or FLD2 and also looking at cos/sin calculations because I've seen lack of reproducibility with those terms in the past for going to/from u/v components of wind versus speed/direction.  I can test this in the coupled test case if you can share your set-up or I will investigate in an uncoupled test case if you agree this is a good path forward to look into @DeniseWorthen

**Comment by DeniseWorthen** [comment]
I don't think it is in the sin/cos terms, since the difference I see is in the ``a`` array itself w/in the stokes drift calculation. I also don't think it is the sin/cos because I get bit identical USSPX,Y in the ATM-WAV only case. 

Given the location on the edge of a domain, my hunch is that it has to do w/ the ghost cell update of the array ``a``. 

I think until I can commit the unstructured mesh work it is probably easiest if you debug in the standalone case.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for your insights @DeniseWorthen I'll share if I can figure anything out on my end.

**Comment by JessicaMeixner-NOAA** [comment]
I have used the following WW3 regression test: 
```
./bin/run_cmake_test -b slurm -o all -S -T -s MPI -s PDLIB -i input_unstr -w work_unstr_b24 -g b -f -p srun -n 24 ../model ww3_ufs1.1
./bin/run_cmake_test -b slurm -o all -S -T -s MPI -s PDLIB -i input_unstr -w work_unstr_b40 -g b -f -p srun -n 40 ../model ww3_ufs1.1

```
and confirmed we start seeing differences in output after the ice input is updated at hour 12.  The model blew up if I tried to take out the ice input all together but everything reproduces up until hour 12 where the ice is updated which to me seems to point to an issue in how the ice field is getting updated, which is consistent with previous reports of the MPI reproducibility issues, even with the block explicit which the above test should be using.  Another thing of note is that the restarts are different for all hours.  @aronroland - is there anything in the restart file that is dependent on the number of MPI tasks and therefore different restart files should be expected?

**Comment by aronroland** [comment]
Hi, @JessicaMeixner-NOAA, no there is no core count dependency in general. The whole code should be b4b except the Block Gauss-Seidel solver, which cannot be b4b.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland okay this test case is using block explicit from my understanding: 
https://github.com/NOAA-EMC/WW3/blob/develop/regtests/ww3_ufs1.1/input_unstr/ww3_grid_b.inp#L62-L87 

So looks like we have two issues: 
* the difference in output for ice which happens after the ice values are updated 
* why restarts are different in this case. 

@DeniseWorthen I believe you are getting differences in output almost immediately so we'd expect the restarts to be different in your case, but I just wanted to double check if this is something you're also seeing in the coupled case.

**Comment by aronroland** [comment]
> @aronroland okay this test case is using block explicit from my understanding: https://github.com/NOAA-EMC/WW3/blob/develop/regtests/ww3_ufs1.1/input_unstr/ww3_grid_b.inp#L62-L87
> 
> So looks like we have two issues:
> 
> * the difference in output for ice which happens after the ice values are updated
> * why restarts are different in this case.
> 
> @DeniseWorthen I believe you are getting differences in output almost immediately so we'd expect the restarts to be different in your case, but I just wanted to double check if this is something you're also seeing in the coupled case.

Basically, what has to be done is follow @DeniseWorthen. She has found most of the bugs that result in b4b problems within any explicit scheme in the context of the DD approach. 

I would actually do similar work to trace this down involving also the *COHERENCY* work that @MathieuDutSik  and me have put in the code (see the certain cpp pragma in the code) to sort out the cpu coherency issues that may evolve in the active development of the code. Of course, the *COHERENCY* part of the code needs to be extended to the features where it is not present so far e.g. ICE and others.

However, this needs of course also test cases on *COHERENCY* as suggested in #969. As far this is not implemented I see those cases increasingly popping up and no convergent development.

**Comment by DeniseWorthen** [comment]
@JessicaMeixner-NOAA The coupled model has never had b4b ww3 restart files. See [Issue 739](https://github.com/ufs-community/ufs-weather-model/issues/739#issuecomment-983550204). That is why we do not compare the WW3 restart files in the UFS RTs. Since the entire model does reproduce, my assumption has always been that there are differences in non-data fields which do not matter but which cause the binary comparison to fail. But w/ binary restart, I never investigated.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland it indeed would be great to update the regression test system, but at this time at least from the EMC side,  efforts are towards solving this issue and the scotch issue.  After that maybe we can collectively update the regression test system to help us keep these issues solved. Can you point me to where in PDLIB the ice or other input is updated for ghost nodes after an update? 

@DeniseWorthen - I remember this now.  Thanks for reminding me.

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland two questions for you: 
1. What are IOBP_LOC, IOBPD_LOC, IOBPA_LOC, IOBDP_LOC ?   One seems to be for water depth, another for if you have input coming from a boundary.  I'm not sure about the others, but I'm wondering if one of these variables needs to be updated in w3uice when we update MAPSTA? 
2. From the routine PDLIB_MAPSTA_INIT it seems like PDLIB is not really using MAPSTA but uses MAPSTA to set other variables that are then used.  If this is the case, and in w3uice we update MAPSTA, what here would/should also get updated? 


@DeniseWorthen - while I can run the standalone test case to get the MPI issues, we'd still be interested in getting the branch and test case on hera if you can share that at some point.

**Comment by aronroland** [comment]
Hi @JessicaMeixner-NOAA, i took a look at the code (invested quite some resources to see what is going on there) and I would say that the ICE part is neither streamlined within the domain decompostion nor I can see that this is even consistently implementend within the UG approach. I found several parts of the code that needs to be extened and further developed to get the ICE properly working within the UG and then of course within the DD.

Of course this needs also some regtest to test and see where we are and what has to be done. Sometimes it is helpfull to take some steps back before going forward. Have a nice weekend!

**Comment by JessicaMeixner-NOAA** [comment]
@aronroland we have at regtest that shows at this issue.  While addressing all issues for all regression tests is probably not realistic right now, if there are other regression tests that are needed to better diagnose this problem please let me know and we can likely prioritize those updates to help us solve this issue. 

In the meantime, can you help me by answering the two following questions repeated from above: 
* What are IOBP_LOC, IOBPD_LOC, IOBPA_LOC, IOBDP_LOC ? One seems to be for water depth, another for if you have input coming from a boundary. I'm not sure about the others, but I'm wondering if one of these variables needs to be updated in w3uice when we update MAPSTA?
* From the routine PDLIB_MAPSTA_INIT it seems like PDLIB is not really using MAPSTA but uses MAPSTA to set other variables that are then used. If this is the case, and in w3uice we update MAPSTA, what here would/should also get updated?

I can set up a meeting to go through code together and go over these questions if that would be easier.

**Comment by DeniseWorthen** [comment]
I attempted to get something set up on Hera late last week, but nothing was moving through the queue for me. I wanted to make sure my cleanup debug branch was working before handing it off. 

In the meantime though, I tried a different tack. I set up a second case where I kept the imported CX constant (and CY=0). That also produced a single point which did not reproduce in ``VA`` when changing decomp. This point was also located along the boundary of one domain. The ice concentration was nearly constant at this point though through the first several hours (~0.74, with CICE0=CICEN=0.75).

Tracking that single point showed that the answers diverged only after the call to the block explicit scheme. Debugging that routine gave me a fix for the domain decomposition reproducibility in the coupled case. I'll have a PR later this afternoon that you can test in the standalone. All the changes are in ``PDLIB_EXPLICIT_BLOCK``

**Comment by MatthewMasarik-NOAA** [comment]
> I attempted to get something set up on Hera late last week, but nothing was moving through the queue for me. I wanted to make sure my cleanup debug branch was working before handing it off.
> 
> In the meantime though, I tried a different tack. I set up a second case where I kept the imported CX constant (and CY=0). That also produced a single point which did not reproduce in `VA` when changing decomp. This point was also located along the boundary of one domain. The ice concentration was nearly constant at this point though through the first several hours (~0.74, with CICE0=CICEN=0.75).
> 
> Tracking that single point showed that the answers diverged only after the call to the block explicit scheme. Debugging that routine gave me a fix for the domain decomposition reproducibility in the coupled case. I'll have a PR later this afternoon that you can test in the standalone. All the changes are in `PDLIB_EXPLICIT_BLOCK`

Awesome!!  I look forward to testing your fix in standalone.

**Comment by aronroland** [comment]
@DeniseWorthen this sounds good. Let's see what u have found in the block explicit solver ...

**Comment by aronroland** [comment]
> @aronroland two questions for you:
> 
>     1. What are IOBP_LOC, IOBPD_LOC, IOBPA_LOC, IOBDP_LOC ?   One seems to be for water depth, another for if you have input coming from a boundary.  I'm not sure about the others, but I'm wondering if one of these variables needs to be updated in w3uice when we update MAPSTA?

As I said I have no idea about the ice and I would need to look more into it. Otherwise where I can help is to explain the variables below .. 

These are all local variables that control the boundary and the wetting and drying: 

IOBP = boundary value for using different boundary conditions
IOBPD = boundary pointer for the spectra. E.g. 0 when it is dry or waves are coming from land ... 
IOBDP = depth pointer for wetting & drying 
IOBPA = some pointer for the boundary forcing 
> 
>     2. From the routine PDLIB_MAPSTA_INIT it seems like PDLIB is not really using MAPSTA but uses MAPSTA to set other variables that are then used.  If this is the case, and in w3uice we update MAPSTA, what here would/should also get updated?
> 
AR: I do not know I would need to look at this. Generally I try to get rid of MAPSTA in the PDLIB part. 
> 
> @DeniseWorthen - while I can run the standalone test case to get the MPI issues, we'd still be interested in getting the branch and test case on hera if you can share that at some point.
